### ISSUE TITLE
VSode codewind projects view not refreshing effectively

### ISSUE THREAD

**Issue by NikCanvin** [eclipse/codewind#1999] opened 2020-02-04 09:12 UTC
**Codewind version:** 0.8.0
**IDE extension version: 0.8.0
**IDE version:** vscode 1.41.1

**Description:**
Codewind behaves normally, then when I awake my Mac from sleep (starting work in morning), the list of projects under 'codewind/local' is missing. When I tried to bind the projects I was previously working with, an error reports the project name already in use (docker is still running the project applications). To fix it, I needed to 'right-click' codewind/local and hit refresh. This first happened yesterday and as a Codewind user I did not know what to do (Toby figured it out), but it just happened again this morning.

**Steps to reproduce:**
see above

**Workaround:** 
see above

**Comment by tobespc** [comment] 2020-02-04 09:16
I'm also hitting this quite frequently.  Is there something we can do to resolve this @tetchel

**Comment by tetchel** [comment] 2020-02-04 14:06
I'm not sure if there's a way I can refresh when your computer wakes from sleep, but I haven't seen this, so maybe it is because of a change I made.

**Comment by tetchel** [comment] 2020-02-04 14:45
do you see "connection lost" in place of a list of projects, or do you see "no projects (create a new project)"?

**Comment by tetchel** [comment] 2020-02-11 21:27
I can't reproduce this so I am going to need a screen recording and/or logs

**Comment by tetchel** [comment] 2020-02-20 03:55
Closing because I have not seen this and there is not enough info to work off of

**Closed** 2020-02-20 03:54 UTC
Labels: area/vscode-ide, kind/bug

**Comment by NikCanvin** [comment] 2020-03-13 10:35
I've not see this issue recently either, so good to close
