### ISSUE TITLE
SVT : Eclipse :  Installer installs inconsistent set of drivers

### ISSUE THREAD

**Issue by mmulholl** [eclipse/codewind#752] opened 2019-10-21 16:08 UTC
**Codewind version:** 0.5.0
**OS:** linux

**Che version:**
**IDE extension version:**
**IDE version:** Eclipse
**Kubernetes cluster:**

**Description:**
If I install, for example 0.5.0 into eclipse from https://download.eclipse.org/codewind/codewind-eclipse/0.5.0/latest/repository/, but when I started eclipse I had CW_TAG=latest, I don't get 0.5.0 at all. I get latest. This should at least flag a warning, if not fail. 

**Steps to reproduce:**

**Workaround:**

**Comment by tetchel** [comment] 2019-10-21 18:13
there's no reason a user would set the CW_TAG env variable, it's your responsibility to make sure your environment is set up correctly.

```
You can work with different versions of the Codewind images by adding the CW_TAG environment variable in the Environment tab. Set it to latest to get the latest images or to a specific tag such as 0.3.
```
https://github.com/eclipse/codewind-eclipse#developing-codewind-for-eclipse

**Comment by jopit** [comment] 2019-10-21 18:19
The CW_TAG env variable is only for use in the development of the eclipse plugin itself.  A user of the eclipse plugin should not be setting this variable at all.

**Comment by mmulholl** [comment] 2019-10-22 18:37
This is an open source project so there is nothing to stop a user from running the latest driver with the tag set and then change to a pre-release version.

**Comment by mmulholl** [comment] 2019-10-22 18:56
Use of CW_TAG is publicly documented here: https://github.com/eclipse/codewind-eclipse

**Comment by rajivnathan** [comment] 2019-10-23 14:43
I think I fit the target demographic for a user of CW_TAG so thought I'd share my input as well. CW_TAG is for development purposes and is only documented under the *Developing* section on each of the vscode and eclipse repos so an end user would not have this issue. If you set `CW_TAG=latest` you're effectively telling the IDEs the image tags you want it to work with , irrespective of the version of the extension in the IDE, so it's working as designed. I don't think it should be an error or warning.

**Comment by mmulholl** [comment] 2019-10-23 17:06
personally, I don't understand the objection, I uninstall codewind from eclipse, install from the 0.5.0 latest download, and eclipse tells me 0.5.0 is installed, but 0.5.0 is not installed at all, under the covers codewind installer has installed something completely different. Not sure how that can be WAD.

**Comment by rtaniwa** [comment] 2019-10-23 17:48
My two cents if I am understanding this all correctly. I think what folks are saying is if you choose to over-ride using CW_TAG, then it is up to you to manage the tag usage and the impact it has on your environment. That variable specifically allows you to over-ride the images and use something other than what was expected via the install. So in that case, a mismatch is more or less expected. What behaviour are you looking for @mmulholl ? That if a user is doing an install, we first check to see if that variable is set and then warn them?

**Comment by mmulholl** [comment] 2019-10-24 18:50
So in my opinion the CW_TAG thing is totally flawed:

Want to run latest of 0.5.0 - tell eclipse to install from here : https://download.eclipse.org/codewind/codewind-eclipse/0.5.0/latest/repository/ but don't set the tag.

Want to run latest of master, tell eclipse to install from here: https://download.eclipse.org/codewind/codewind-eclipse/master/latest/repository/ but you need the tag.

Why can't the installer just install what I told eclipse to install?

But with the tag, if I tell eclipse what I want to install and eclipse says that is what I am running I expect to get it no matter the tag. Maybe the codewind explorer view, where it says to double click to finish installation it should mention what version will be installed. For example:

Codewind [Installation incomplete] (double click to download the codewind 0.5.0 images]

or   

Codewind [Installation incomplete] (double click to download the codewind latest development 
images]

Then when codewind is running, for example: "Codewind 0.5.0 [Running]"

Also don't forget we are an open source project which means we hope users will download and run development images, maybe make a few pull requests, so to suggest a user could never hit the issue just seems wrong.

**Comment by jopit** [comment] 2019-10-25 17:37
Three comments

1. We could probably do some magic in the IDE builds to set the tag for which docker images to install/run based on the branch being built.  Maybe have the IDEs read the tag from a .properties or .json file that by default specifies `latest` but have the build overwrite it if on a release branch.  This also means we wouldn't need to change the tag value in the IDE source code for every release.

2. Speaking as a developer of the Codewind IDE plugins, I still want the ability to set the tag when I'm developing, because I've found it useful.  But since people developing the Codewind IDE plugins will almost certainly be self-hosting from a git clone, they could change the value in the .properties/.json file.  It could be gitignored to prevent it from being checked in.

3. Dang it @mmulholl, now I want to start hacking up the build scripts instead of working on what I'm supposed to be working on.

**Comment by rajivnathan** [comment] 2019-10-25 18:41
I (and others) use `CW_TAG=latest` when we need to test against a PFE image that was built using `run.sh` (so not just images pulled by the IDE). If there are going to be any changes to the behaviour of `CW_TAG` this capability must be maintained.

**Comment by jopit** [comment] 2019-10-25 20:15
All `CW_TAG` does is override the default image version that's hard-coded into the IDEs.  The `run.sh` script tags the images it creates with `latest`.  If the build magic works, IDEs built from master by Jenkins, or self-hosted IDEs would now use `latest` by default. You would no longer have to specify `CW_TAG` to override the tag at all.

**Comment by jopit** [comment] 2019-10-25 20:22
To be completely accurate, any IDE built by Jenkins on a release branch would use the name of the branch as the tag (so `0.6.0` for example).  All other builds would use `latest`.

**Comment by rajivnathan** [comment] 2019-10-28 16:11
That's not what's happening on the latest vscode builds. (Haven't tried eclipse) I have PFE running using `latest` images from run.sh. I installed the latest vscode extension from http://download.eclipse.org/codewind/codewind-vscode/master/latest/codewind.vsix and I see this:

![image](https://user-images.githubusercontent.com/20015929/67695475-86d65d80-f97b-11e9-9509-5f64dd44bc13.png)

![image](https://user-images.githubusercontent.com/20015929/67695506-93f34c80-f97b-11e9-9d59-1d2b3cf0fe65.png)

If I quit VSCode and then `export CW_TAG=latest` and launch VSCode again then it works.

**Comment by jopit** [comment] 2019-10-28 19:12
We haven't changed anything yet, so you still need to use the CW_TAG. The discussion above is about how we could potentially change the behaviour if we decide to do so.

**Comment by mmulholl** [comment] 2019-11-04 21:13
@jopit I like your suggestions, something, anything, would be an improvement :-)

**Comment by eharris369** [comment] 2020-01-09 21:27
@mmulholl In the master branch the default install version is set to `latest` now.  Is that sufficient for what you need?

**Comment by eharris369** [comment] 2020-03-03 21:00
I believe this is resolved by setting the default install version to latest in master branch so closing. If you still have a concern, please re-open.

**Closed by eharris369** 2020-03-03 21:00 UTC
Labels: area/eclipse-ide, kind/bug
