### ISSUE TITLE
Turbine unit tests fail to run

### ISSUE THREAD

**Issue by stalleyj** [eclipse/codewind#355] opened 2019-09-04 10:53 UTC
**Codewind version:**  Failure occurs on master branch.
**OS:** Mac

**Description:**
I wanted to run the Turbine unit tests to verify my code changes but they fail immediately.  

/Users/stalleyj/Development/codewind/src/pfe/file-watcher/server/src/controllers/projectStatusController.ts:70
     *
                                                                                         ^
TypeError: projectUtil.getAllProjectInfo is not a function
    at initAppStateMap (/Users/stalleyj/Development/codewind/src/pfe/file-watcher/server/src/controllers/projectStatusController.ts:70:90)
    at Object.<anonymous> (/Users/stalleyj/Development/codewind/src/pfe/file-watcher/server/src/controllers/projectStatusController.ts:33:2)
    at Module._compile (internal/modules/cjs/loader.js:776:30)
    at Module.replacementCompile (/Users/stalleyj/Development/codewind/src/pfe/file-watcher/server/node_modules/append-transform/index.js:58:13)
    at Module.m._compile (/Users/stalleyj/Development/codewind/src/pfe/file-watcher/server/node_modules/ts-node/src/index.ts:439:23)
    at module.exports (/Users/stalleyj/Development/codewind/src/pfe/file-watcher/server/node_modules/default-require-extensions/js.js:7:9)
    at /Users/stalleyj/Development/codewind/src/pfe/file-watcher/server/node_modules/append-transform/index.js:62:4
    at require.extensions.<computed> (/Users/stalleyj/Development/codewind/src/pfe/file-watcher/server/node_modules/ts-node/src/index.ts:442:12)
    at Object.<anonymous> (/Users/stalleyj/Development/codewind/src/pfe/file-watcher/server/node_modules/append-transform/index.js:62:4)

**Steps to reproduce:**
 codewind/src/pfe/file-watcher/server> npm run unit:test

**Workaround:**

**Comment by ssh24** [comment] 2019-09-04 13:11
I am investigating why this is happening. I am also able to reproduce this using master code.

**Comment by ssh24** [comment] 2019-09-04 13:12
It is also something new because the nightly run also failed for today https://9.37.138.217/index.html

**Comment by ssh24** [comment] 2019-09-04 13:18
Looks like this PR https://github.com/eclipse/codewind/pull/351/files is the culprit. Reverting that commit fixes the test. A recent change was introduced that causes circular dependencies between `projectUtil.ts` and `dockerUtil.ts.

https://github.com/eclipse/codewind/blob/cafae4f274e8b0b804e299f883776db9a7dc6950/src/pfe/file-watcher/server/src/utils/dockerutil.ts#L20

https://github.com/eclipse/codewind/blob/92d1c9aa0ce725082c2c1d0bb0a3fc70009d479c/src/pfe/file-watcher/server/src/projects/projectUtil.ts#L24

**Comment by stalleyj** [comment] 2019-09-04 13:57
Does this mean the 0.3.0 branch is also broken ?

**Comment by ssh24** [comment] 2019-09-04 14:13
I think the change went into 0.3.1 instead 0.3.0? If so, I think we should backport it to 0.3.1 branch just to be safe.

cc @johnmcollier

**Comment by rajivnathan** [comment] 2019-09-04 16:15
Changes are now delivered to master and 0.3.1. @stalleyj can you please verify?

**Comment by stalleyj** [comment] 2019-09-05 13:41
I have verified that the tests do now run on master although I did get 4 test failures (3 timeouts). Is there an issue open for the failures ? 

228 passing (29s)
  4 failing

  1) PFE - unit test
       actions module
         combinational testing of validate function
           combo24 => validate: good appsody project:
     Error: Timeout of 2000ms exceeded. For async tests and hooks, ensure "done()" is called; if returning a Promise, ensure it resolves. (/Users/stalleyj/Development/codewind/src/pfe/file-watcher/server/test/unit-test/unit.test.ts)
      at listOnTimeout (internal/timers.js:531:17)
      at processTimers (internal/timers.js:475:7)

  2) PFE - unit test
       actions module
         combinational testing of validate function
           combo25 => validate: appsody project with missing requiredFiles:
     Error: Timeout of 2000ms exceeded. For async tests and hooks, ensure "done()" is called; if returning a Promise, ensure it resolves. (/Users/stalleyj/Development/codewind/src/pfe/file-watcher/server/test/unit-test/unit.test.ts)
      at listOnTimeout (internal/timers.js:531:17)
      at processTimers (internal/timers.js:475:7)

  3) PFE - unit test
       projectExtensions module
         Combinational testing of getProjectHandler function
           combo6 => getProjectHandler & getProjectCapabilities: projectID dummyappsodyproject:
     Error: Timeout of 2000ms exceeded. For async tests and hooks, ensure "done()" is called; if returning a Promise, ensure it resolves. (/Users/stalleyj/Development/codewind/src/pfe/file-watcher/server/test/unit-test/unit.test.ts)
      at listOnTimeout (internal/timers.js:531:17)
      at processTimers (internal/timers.js:475:7)

  4) PFE - unit test
       projectExtensions module
         testing of removeProjectHandler function
           removeProjectHandler: dummyappsodyproject:

      AssertionError: expected 'docker' to equal 'appsodyExtension'
      + expected - actual

      -docker
      +appsodyExtension
      
      at Context.<anonymous> (test/unit-test/tests/projectExtensions.module.test.ts:431:53)

**Comment by ssh24** [comment] 2019-09-05 14:30
@stalleyj Those tests have been passing on the nightly run builds. If you see them consistently failing, can you please open issue for them? Thanks.

**Comment by stalleyj** [comment] 2019-09-09 11:53
@ssh24 I've run the tests again this morning on latest code so I've raised this issue, they all seem to be appsody related https://github.com/eclipse/codewind/issues/396

**Comment by rajivnathan** [comment] 2019-09-10 15:30
Accidentally reopened. Closing...

**Closed by rajivnathan** 2019-09-10 15:30 UTC
Labels: area/iterative-dev, kind/bug, kind/test
