### ISSUE TITLE
Upgrade to CW 3.0.1 in VSCode failed 

### ISSUE THREAD

**Issue by gruffwizard** [eclipse/codewind#411] opened 2019-09-11 12:35 UTC
While using codewind , VSCode spotted the update from 3.0 to 3.0.1 and offered the upgrade.  Eventually got a this error
![image](https://user-images.githubusercontent.com/9293028/64697389-09c15880-d4a1-11e9-9d21-5b8ae0ea5941.png)

Stop and starting CW in VSCode didn't work.  Had to stop the docker containers and **prune them.** Restarted CW in VSCode and it downloaded latest docker images

**Comment by mattcolegate** [comment] 2019-09-11 12:40
I'll look into it

**Comment by mattcolegate** [comment] 2019-09-11 13:35
Couldn't recreate on first pass - after installing 0.3.0 and restarting VSCode, it informed me my images were out of date then the upgrade was a success. Trying again after clearing out docker.

**Comment by tetchel** [comment] 2019-09-11 13:52
minor, but the broken message ("$tag$") is fixed in master.

It's hard to know what may have caused this. it is not uncommon for docker to get "corrupted" in this way where the images have to be pruned / the engine has to be restarted, before install/start can succeed.

**Comment by tetchel** [comment] 2019-09-11 13:53
For the installer/CLI team, this message is shown only if there is no stderr output from the command that was invoked (`start` here). It may help to look into error scenarios that do not produce output.

**Comment by tobespc** [comment] 2019-09-16 14:38
assiging this to the installer to catch this scenario and moving to enhancement as unable to recreate

**Comment by danielvaughan** [comment] 2019-09-17 11:14
+1 this is an error I am also experiencing. Codewind 0.3.1, VS Code 1.38.1,  Docker 19.03.2 on OSX.

"Error starting Codewind: Unknown error Starting Codewind $tag$"

**Comment by danielvaughan** [comment] 2019-09-17 11:33
Doing a full reset on the Docker Desktop caused the images to be re-pulled and has appeared to clear this error for me.

**Comment by tetchel** [comment] 2019-09-17 14:25
I don't expect us to fix this for 0.4 but I'm adding the hot tag because of the attention this is getting with users hitting it at this week's conference

**Comment by rtaniwa** [comment] 2019-09-23 13:06
I don't believe this issue should be labelled an enhancement. This is a bug. Let's remove the enhancement tag and continue to work with priority given we have seen a number of users hit this.

**Comment by deboer-tim** [comment] 2019-09-23 13:11
Ditto. I couldn't reproduce either, but enough people saw it that I think we need to understand what's going on. If anyone is still seeing this, I think it would help if they could take a snapshot of all the installed images before and after the docker purge/reset. IMHO this sounds like one of our stack images (which we attempt to lock down) wasn't locked down and made a breaking change.

**Comment by jcockbain96** [comment] 2019-09-23 13:18
I'll take it

**Comment by tetchel** [comment] 2019-09-23 13:58
I want to re-iterate that the best fix for this is to find a way to ensure a helpful error is always output (to the error stream) by the installer when it exits with an error code. But I know that may be easier said than done.

**Comment by jcockbain96** [comment] 2019-09-24 14:35
As this comes from a similar place to https://github.com/eclipse/codewind/issues/462 (the `start` command on the CLI). I'm testing where we aren't outputting to stderr there and will add some more checking.

**Comment by malincoln** [comment] 2019-09-26 21:27
@jcockbain96 as this is in progress for next release, pls add 0.5.0 release.  Thanks

**Comment by pdestrais** [comment] 2019-10-29 17:24
<img width="460" alt="image" src="https://user-images.githubusercontent.com/11016696/67792347-4957fa00-fa79-11e9-9927-82b13768b8e3.png">
The proble still exist with v0.5

**Comment by tetchel** [comment] 2020-01-07 14:13
I think this instance of this bug can be closed since the 'unknown error' doesn't occur anymore. Though we still have upgrade troubles some of the time.

**Closed by tetchel** 2020-01-07 14:13 UTC
Labels: area/portal, kind/bug, priority/hot
