### ISSUE TITLE
Project creation broken on Kube due to CLI changes

### ISSUE THREAD

**Issue by johnmcollier** [eclipse/codewind#572] opened 2019-09-26 19:50 UTC
**Codewind version:** latest

**Che version:** 7.1.0
**IDE extension version:** latest
**IDE version:** latest
**Kubernetes cluster:** ROKS 3.11

**Description:**
Project creation is broken on the latest Codewind images, as the extension is trying to call out to the initialize container which doesn't exist on Kube / Che. The follow error is spit out by Theia:
<img width="547" alt="Screen Shot 2019-09-26 at 3 26 32 PM" src="https://user-images.githubusercontent.com/6880023/65718930-99a2fd00-e072-11e9-8349-20f32d5a3f3f.png">

If the `0.4.0` Theia extension is used with the `latest` codewind images, project creation is fine, so seems to be something going on at the extension level.

**Steps to reproduce:**
1. Create a Che workspace with the [latest](https://raw.githubusercontent.com/eclipse/codewind-che-plugin/master/devfiles/latest/devfile.yaml) devfile
2. Try to create a project (Go for example)
3. The Theia extension will spit out the following error:
```
Error creating new project: 2019/09/26 19:38:01 Downloaded file from 'https://codeload.github.com/microclimate-dev2ops/microclimateGoTemplate/legacy.zi
/master' to '/tmp/_2019-09-26T19-38-00Z.zip' 2019/09/26 19:38:01 Extracted file from
'/tmp/_2019-09-26T19-38-00Z.zip' to '/projects/gogotet' 2019/09/26 19:38:01
CONTAINER_LIST_ERROR[107]: Cannot connect to the Docker daemon at unix:///va
/run/docker.sock. Is the docker daemon running?. 
```

**Comment by johnmcollier** [comment] 2019-09-26 20:03
http://download.eclipse.org/codewind/codewind-vscode/master/65/codewind-theia-0.5.0-201909201551.vsix

**Comment by johnmcollier** [comment] 2019-09-26 20:26
May be something at the installer level actually? The error message `CONTAINER_LIST_ERROR` is coming from the Codewind CLI.

Adding the `area/portal` label too, just in case.

**Comment by johnmcollier** [comment] 2019-09-26 20:58
Dug a little further, not a theia extension bug like I thought. Bug is in the CLI:

When validating for a new project, the CLI is calling `apiroutes.GetExtensions()`, which ends up calling out to the Docker Daemon to get the container. However, since the docker daemon isn't accessible on Kube, it fails.

https://github.com/eclipse/codewind-installer/blob/58b800df4fb77190d163ab3b8263307fba2caa97/actions/project.go#L118

and 

https://github.com/eclipse/codewind-installer/blob/58b800df4fb77190d163ab3b8263307fba2caa97/apiroutes/extensions.go#L33

**Comment by makandre** [comment] 2019-09-26 21:02
My bad, caused by https://github.com/eclipse/codewind-installer/pull/119

**Comment by malincoln** [comment] 2019-09-26 21:25
@johnmcollier Should this be fixed for 0.5.0?

**Comment by johnmcollier** [comment] 2019-09-26 21:27
@malincoln Yup, it's a stop ship for 0.5.0

**Comment by malincoln** [comment] 2019-09-26 21:32
@johnmcollier can you update label to "priority/stopship"?

**Comment by tobespc** [comment] 2019-09-30 08:53
will pick this up asap

**Comment by jcockbain96** [comment] 2019-09-30 12:23
I'm picking this up, can I be assigned please?

**Comment by makandre** [comment] 2019-09-30 13:37
I do have a PR fix for this https://github.com/eclipse/codewind-installer/pull/130 It needs to be reviewed

**Closed** 2019-09-30 17:51 UTC
Labels: area/appsody, kind/bug, priority/hot, priority/stopship
