### ISSUE TITLE
Hybrid Local Remote Sync

### ISSUE THREAD

**Issue by maysunfaisal** [eclipse/codewind#826] opened 2019-10-23 20:36 UTC
**Codewind version:**
**OS:**

**Che version:**
**IDE extension version:**
**IDE version:**
**Kubernetes cluster:**

**Question synopsis:**

When I create a remote connection to Codewind from my local IDE; my projects are going to reside in my local machine and will be synced to the remote Codewind, which is all fine.

what happens if my remote Codewind has 

- a project of the same name
- other projects, will these be synced to Local?

**Comment by maysunfaisal** [comment] 2019-10-23 20:36
cc: @tetchel

**Comment by maysunfaisal** [comment] 2019-10-23 20:37
@tobespc a few questions about Hybrid..

**Comment by tetchel** [comment] 2019-10-23 20:38
afaik the syncing is one way only, I think it would be quite separate to "pull" a project from remote to local.

**Comment by ssh24** [comment] 2019-10-23 20:45
I think projects with the same name will still collide since the projects are still stored in `/codewind-workspace` in PFE container.

**Comment by tetchel** [comment] 2019-10-23 20:47
`bind` command blocks it; 
`{"error":"proj_response","error_description":"project name is already in use"}`

**Comment by tobespc** [comment] 2019-10-24 08:13
bind command does block it (went in yesterday) but we do need to figure out how to handle duplicate project names.

Sync is only one way - files get written by the IDE, they get synced into the PFE container and then further synced in to the build/run container

**Comment by yangcao77** [comment] 2019-10-24 19:46
In latest master built from today, I saw portal log the error saying the directory already exist, but it still sync the project to container and send creation request to Turbine. 
```
[24/10/19 19:23:00 /portal/modules/Project.js] [INFO] Project node111 initializing (project type: nodejs, projectID: b13a8aa0-f693-11e9-be0d-314b9f84d5e5)
[24/10/19 19:23:00 /portal/routes/projects/remoteBind.route.js] [INFO] Project node111 (b13a8aa0-f693-11e9-be0d-314b9f84d5e5) opened.
[24/10/19 19:23:00 /portal/routes/projects/remoteBind.route.js] [ERROR] Project creation failed for project node111. Error: { [Error: EEXIST: file already exists, mkdir '/codewind-workspace/cw-temp/']
  errno: -17,
  code: 'EEXIST',
  syscall: 'mkdir',
  path: '/codewind-workspace/cw-temp/' }
[24/10/19 19:23:00 User.js] [INFO] Building project b13a8aa0-f693-11e9-be0d-314b9f84d5e5 (node111)
[24/10/19 19:23:00 FileWatcher.js] [INFO] Calling createProject() for project node111 {"projectID":"b13a8aa0-f693-11e9-be0d-314b9f84d5e5","projectType":"nodejs","startMode":"run","location":"/codewind-workspace/node111","settings":{"contextRoot":"","internalPort":"","healthCheck":"","internalDebugPort":"","isHttps":false,"ignoredPaths":[""]},"language":"nodejs"}
[24/10/19 19:23:00 Turbine] [INFO] Creating project logs directory
[24/10/19 19:23:00 Turbine] [INFO] b13a8aa0-f693-11e9-be0d-314b9f84d5e5: Project Settings: {"contextRoot":"","internalPort":"","healthCheck":"","internalDebugPort":"","isHttps":false,"ignoredPaths":[""]}
[24/10/19 19:23:00 Turbine] [INFO] Log directory created at: /codewind-workspace/.logs/node111-b13a8aa0-f693-11e9-be0d-314b9f84d5e5
[24/10/19 19:23:00 Turbine] [ERROR] [File Name: /file-watcher/server/dist/controllers/projectsController.js | Function Name: getProjectInfoFromFile | Line Number: 773] Failed to find project information related to file /file-watcher/fwdata/projects/b13a8aa0-f693-11e9-be0d-314b9f84d5e5/b13a8aa0-f693-11e9-be0d-314b9f84d5e5.json
[24/10/19 19:23:00 node111] [INFO] Creating project /codewind-workspace/node111
[24/10/19 19:23:00 node111] [INFO] Project data directory: /file-watcher/fwdata/projects/
[24/10/19 19:23:00 node111] [INFO] Initial start mode for project b13a8aa0-f693-11e9-be0d-314b9f84d5e5 is: run
[24/10/19 19:23:00 node111] [INFO] Setting isHttps from the project settings
[24/10/19 19:23:00 node111] [INFO] The ignoredPaths array is empty, File-watcher will ignore the setting
[24/10/19 19:23:00 Turbine] [INFO] b13a8aa0-f693-11e9-be0d-314b9f84d5e5: ignoredPaths after removed any empty strings: 
[24/10/19 19:23:00 node111] [INFO] operationId: 710baa90cf15e4384d25a3714d7d98a9
[24/10/19 19:23:00 node111] [INFO] Pushing project to build queue
[24/10/19 19:23:00 node111] [INFO] Checking for required files
[24/10/19 19:23:00 node111] [INFO] Checking for required file /Dockerfile
[24/10/19 19:23:00 /portal/routes/projects/remoteBind.route.js] [INFO] Successfully created project - name: node111, ID: b13a8aa0-f693-11e9-be0d-314b9f84d5e5
[24/10/19 19:23:00 node111] [INFO] Checking for required file /package.json
[24/10/19 19:23:00 node111] [INFO] Creating container for nodejs project /codewind-workspace/node111
[24/10/19 19:23:00 Turbine] [INFO] typeof projectHandler.getContainerName is undefined
[24/10/19 19:23:00 node111] [INFO] The log name for b13a8aa0-f693-11e9-be0d-314b9f84d5e5 is cw-b13a8aa0-f693-11e9-be0d-314b9f84d5e5-6479418b439788b0b33e7086c4e313ffd65e3f85
[24/10/19 19:23:00 node111] [INFO] Container name: cw-node111-b13a8aa0-f693-11e9-be0d-314b9f84d5e5
[24/10/19 19:23:00 node111] [INFO] Log name: cw-b13a8aa0-f693-11e9-be0d-314b9f84d5e5-6479418b439788b0b33e7086c4e313ffd65e3f85
[24/10/19 19:23:00 node111] [INFO] Beginning build for b13a8aa0-f693-11e9-be0d-314b9f84d5e5
[24/10/19 19:23:00 node111] [INFO] executeBuildScript with args:  {/file-watcher/scripts/nodejs-container.sh /codewind-workspace/node111 /codewind-workspace b13a8aa0-f693-11e9-be0d-314b9f84d5e5 create cw-node111-b13a8aa0-f693-11e9-be0d-314b9f84d5e5 true cw-b13a8aa0-f693-11e9-be0d-314b9f84d5e5-6479418b439788b0b33e7086c4e313ffd65e3f85 run 9229 NONE node111-b13a8aa0-f693-11e9-be0d-314b9f84d5e5 undefined true}, In K8 environment: undefined
[24/10/19 19:23:00 node111] [INFO] Now tracking running process 460 for project b13a8aa0-f693-11e9-be0d-314b9f84d5e5
[24/10/19 19:23:01 node111] [INFO] Build began for b13a8aa0-f693-11e9-be0d-314b9f84d5e5
[24/10/19 19:23:01 node111] [INFO] Build state changed for project: b13a8aa0-f693-11e9-be0d-314b9f84d5e5 from: unknown, to: inProgress, with message: projectStatusController.buildStarted
[24/10/19 19:23:01 node111] [INFO] Emitting event 
 message: projectStatusChanged
 data: {
  "projectID": "b13a8aa0-f693-11e9-be0d-314b9f84d5e5",
  "buildStatus": "inProgress",
  "detailedBuildStatus": "Build started"
}
```

To reproduce:
1. create a project
2. delete the project, and DO NOT delete the project directory. 
3. exec into the container, open workspace, delete the Dockerfile of the project
4. create a project with the same name from ide

What I saw:
exec into the container, open project directory, the Dockerfile got sync
the project build & run successfully

What is expected to see:
it should not sync the project directory into container
the creation should failed and ide should not show the project in the project list

**Comment by tobespc** [comment] 2019-10-25 12:38
I'm going to open separate issues for items in here

**Comment by tobespc** [comment] 2019-10-25 12:43
closing as raised separate issues to address the questions

**Closed by tobespc** 2019-10-25 12:43 UTC
Labels: area/portal, kind/question, remote
