### ISSUE TITLE
Error creating new project: "connect EACCES /var/run/docker.sock"

### ISSUE THREAD

**Issue by juansuerogit** [eclipse/codewind#23] opened 2019-07-17 03:07 UTC
Im running CentOS Linux release 7.6.1810 (Core)
with visual studio code code-1.36.1-1562627663.el7.x86_64.rpm
with docker-ce from the yum repository docker-ce-18.06.3.ce-3.el7
with docker-compose from the yum repository docker-compose version 1.24.1, build 4667896

my setup also added a parameter to docker systemd /usr/lib/systemd/system/docker.service
ExecStart=/usr/bin/dockerd --userns-remap=meta
to enable usernamespaces so i didnt have to run all my containers as root.

but then i went to install codewind from visual studio code and the first weird thing was that it told me docker wasnt installed even though it was.
so i clicked ok and then come to find out my /usr/lib/systemd/system/docker.service was replaced without the userns-remap

and then i put back my userns-remap argument into /usr/lib/systemd/system/docker.service 

and when i try to create a project in codewind i get 
Error creating new project: "connect EACCES /var/run/docker.sock"

BTW my user account is in the docker group.

**Comment by juansuerogit** [comment] 2019-07-17 03:12
fyi  my systemd settings are wiped out and replaced with
/usr/bin/dockerd -H fd:// --containerd=/run/containerd/containerd.sock

is this why?  because docker is listening on the containerd.sock?  instead of the sock codewind is looking for?

**Comment by tetchel** [comment] 2019-07-17 14:13
Hi, we're looking into it. Also linking to #24 since they seem to be caused by the same problem.

**Comment by juansuerogit** [comment] 2019-07-17 16:16
thanks.  i downloaded the source code and didnt find any reference to docker.sock.   and couldnt find the a log file.   its possible you are defaulting to docker.sock but docker is more fragmented now some people even use podman on RHEL 8.  and some people use other engines like containerd or crio.   so maybe the location of centos 7.6 is change cause now the repo uses containerd.sock and thats why you couldnt detect my docker.   giving people choice would be best... installing docker based on configuration or questions or allowing to identify a current installation.

**Comment by tetchel** [comment] 2019-07-17 16:18
The [codewind-installer](https://github.com/eclipse/codewind-installer/) is what is trying to access docker, which uses the Docker SDK for Go, we're trying to figure out what the limitation is.

**Comment by tetchel** [comment] 2019-07-22 16:44
Issue moved to [eclipse/codewind-installer #53](https://github.com/eclipse/codewind-installer/issues/53) via [**ZenHub**](https://www.zenhub.com/)

**Comment by tetchel** [comment] 2019-08-19 21:17
Moving this back here because we have moved the issue tracking back to this respository :)

**Comment by tetchel** [comment] 2019-08-19 21:17
@liamchampton said [here](https://github.com/eclipse/codewind-installer/issues/53#issuecomment-514988207)

After some investigation into this I see 2 separate issues:

    Detection of docker is failing - This seems like a docker/system environment issue rather than a codewind issue. Saying this on the basis that the installer is utilizing a docker API and not interfering with any underlying docker settings. However, it looks like you have solved this one.

    Once installed, a project cannot be created - Because codewind uses docker build we have to mount the docker socket within our container. The docker-compose file the installer uses binds it as a volume. Our volumes section in the docker compose file are: volumes: ["/var/run/docker.sock:/var/run/docker.sock","${WORKSPACE_DIRECTORY}:/codewind-workspace"]. Because your docker socket isn't /var/run/docker.sock this is failing. see: https://github.com/eclipse/codewind-installer/blob/master/utils/docker.go#L42

@juansuerogit Did you install containerd seperately and then configure docker to use it?

**Comment by tobespc** [comment] 2019-10-28 10:13
closing as we no longer use docker in the cli

**Closed by tobespc** 2019-10-28 10:13 UTC
Labels: area/portal, kind/bug
