### ISSUE TITLE
[Che] CLI doesn't sync code changes to PFE

### ISSUE THREAD

**Issue by johnmcollier** [eclipse/codewind#906] opened 2019-10-29 20:34 UTC
**Codewind version:** latest
**Che version:** 7.2.0
**IDE extension version:** latest
**Kubernetes cluster:** OCP 4.2

**Description:**
I created a modified sidecar that deploys PFE without mounting the Che workspace PVC (it creates PFE's own volume), as required for the remote changes. However, while the initial project creation does sync the project's code to PFE, successive code changes are not synced.

Looking in the sidecar logs, I see the following:
```
[2019-10-29 20:07:43.908] [4072.984] Successfully ran installer command: [ project] [ sync] [ -p] [ /projects/pytest] [ -i] [ c4701700-fa87-11e9-ab68-ab496f359c57] [ -t] [ 0] 
[2019-10-29 20:07:43.908] [4072.984] Output:open /home/www-data/.codewind/config/connections/c4701700-fa87-11e9-ab68-ab496f359c57.json: no such file or directory
```

Filewatcherd invokes the CLI to do the sync, but the CLI spits out the above error, and the sync doesn't take place. Looking at the sidecar and PFE containers I see:
- The change reflected in the sidecar & theia containers
- The change not reflected in the PFE container

**Steps to reproduce:**
1. Create a Che workspace from this [devfile](https://raw.githubusercontent.com/johnmcollier/devfiles/master/codewind/codewind.yaml)
2. Create a project, any type should suffice (such as Go)
3. The project will get deployed fine, but successive changes do not get reflected (autobuild is broken so will need to run a manual build)

**Comment by johnmcollier** [comment] 2019-10-29 20:39
**Note:**
To test with my changes, you'll either need to use my [devfile](https://raw.githubusercontent.com/johnmcollier/devfiles/master/codewind/codewind.yaml) or build from the branch in this PR: https://github.com/eclipse/codewind-che-plugin/pull/94, as the PR still needs to be merged

**Comment by tobespc** [comment] 2019-10-30 10:49
sync was broken due to a change going into the cli for bind without realising that the the ide's were still calling bind directly on pfe.   We have put a fix into the cli so get round this but we need all editors to be calling cwctl bind.  That will enable sync to work again (but... the latest cwctl will fix this anyway)

**Comment by tetchel** [comment] 2019-10-30 19:55
```
root INFO [hosted-plugin: 72] [INFO: 19:52:37.385 CLIWrapper.js.on():142]: Successfully ran CLI command cwctl --json --insecure project bind --conid local --name goproj --language go --type docker --path /projects/goproj
[DBUG: 19:52:37.385 CLIWrapper.js.on():148]: CLI object output: {"error":"proj_response","error_description":"project type is invalid"}
```

For some reason the project types do not work in Che. The same command works in local.

**Comment by GeekArthur** [comment] 2019-10-30 20:31
> For some reason the project types do not work in Che. The same command works in local.
This issue (https://github.com/eclipse/codewind/issues/897) also related with project type in Che

**Comment by tetchel** [comment] 2019-10-30 21:16
looking into this, the project-types API appears intact in Che.
```
bash-4.4$ curl -sSkL https://localhost:9090/api/v1/project-types
[
  {
    "projectType": "appsodyExtension",
    "projectSubtypes": {
      "label": "Appsody stack",
      "items": [
        {
          "id": "appsodyhub/java-microprofile",
          "version": "0.2.18",
          "label": "Appsody java-microprofile",
          "description": "Eclipse MicroProfile on Open Liberty & OpenJ9 using Maven"
        }
      ]
    }
  },
  {
    "projectType": "appsodyExtension",
    "projectSubtypes": {
      "label": "Appsody stack",
      "items": [
        {
          "id": "appsodyhub/java-spring-boot2",
          "version": "0.3.15",
          "label": "Appsody java-spring-boot2",
          "description": "Spring Boot using OpenJ9 and Maven"
        }
      ]
    }
  },
  {
    "projectType": "appsodyExtension",
    "projectSubtypes": {
      "label": "Appsody stack",
      "items": [
        {
          "id": "appsodyhub/kitura",
          "version": "0.2.1",
          "label": "Appsody kitura",
          "description": "Runtime for Kitura applications"
        }
      ]
    }
  },
  {
    "projectType": "appsodyExtension",
    "projectSubtypes": {
      "label": "Appsody stack",
      "items": [
        {
          "id": "appsodyhub/nodejs",
          "version": "0.2.5",
          "label": "Appsody nodejs",
          "description": "Runtime for Node.js applications"
        }
      ]
    }
  },
  {
    "projectType": "appsodyExtension",
    "projectSubtypes": {
      "label": "Appsody stack",
      "items": [
        {
          "id": "appsodyhub/nodejs-express",
          "version": "0.2.8",
          "label": "Appsody nodejs-express",
          "description": "Express web framework for Node.js"
        }
      ]
    }
  },
  {
    "projectType": "appsodyExtension",
    "projectSubtypes": {
      "label": "Appsody stack",
      "items": [
        {
          "id": "appsodyhub/nodejs-loopback",
          "version": "0.1.5",
          "label": "Appsody nodejs-loopback",
          "description": "LoopBack 4 API Framework for Node.js"
        }
      ]
    }
  },
  {
    "projectType": "appsodyExtension",
    "projectSubtypes": {
      "label": "Appsody stack",
      "items": [
        {
          "id": "appsodyhub/python-flask",
          "version": "0.1.5",
          "label": "Appsody python-flask",
          "description": "Flask web Framework for Python"
        }
      ]
    }
  },
  {
    "projectType": "appsodyExtension",
    "projectSubtypes": {
      "label": "Appsody stack",
      "items": [
        {
          "id": "appsodyhub/starter",
          "version": "0.1.1",
          "label": "Appsody starter",
          "description": "Runnable starter stack, copy to create a new stack"
        }
      ]
    }
  },
  {
    "projectType": "appsodyExtension",
    "projectSubtypes": {
      "label": "Appsody stack",
      "items": [
        {
          "id": "appsodyhub/swift",
          "version": "0.2.0",
          "label": "Appsody swift",
          "description": "Runtime for Swift applications"
        }
      ]
    }
  },
  {
    "projectType": "docker",
    "projectSubtypes": {
      "items": [
        {
          "id": "go",
          "label": "go"
        },
        {
          "id": "java",
          "label": "java"
        },
        {
          "id": "python",
          "label": "python"
        }
      ]
    }
  },
  {
    "projectType": "nodejs",
    "projectSubtypes": {
      "items": [
        {
          "id": "nodejs",
          "label": "nodejs"
        }
      ]
    }
  },
  {
    "projectType": "spring",
    "projectSubtypes": {
      "items": [
        {
          "id": "java",
          "label": "java"
        }
      ]
    }
  },
  {
    "projectType": "swift",
    "projectSubtypes": {
      "items": [
        {
          "id": "swift",
          "label": "swift"
        }
      ]
    }
  },
  {
    "projectType": "liberty",
    "projectSubtypes": {
      "items": [
        {
          "id": "java",
          "label": "java"
        }
      ]
    }
  }
]bash-4.4$
```

I think the problem is that the cwctl outputs the "invalid type" message for *any* 400 error.
https://github.com/eclipse/codewind-installer/blob/master/utils/project/bind.go#L112

So, likely we're getting 400 for a different reason, but the real error is being masked by this one? I don't see anything in the PFE logs.

**Comment by tetchel** [comment] 2019-10-30 21:22
doing the request by hand worked, so it's not that. something is wrong with the cwctl wrapping of this command.
```
bash-4.4$ curl -X POST -sSkL https://localhost:9090/api/v1/projects/remote-bind/start -H "Content-Type: application/json" -d '{ "name": "goproj", "language": "go", "projectType": "docker", "path": "/projects/goproj" }'
{
  "projectID": "48af3b30-fb5b-11e9-b157-bda9f43e7bcc",
  "name": "goproj",
  "language": "go",
  "locOnDisk": "/projects/goproj",
  "host": "",
  "ports": "",
  "workspace": "/codewind-workspace/",
  "directory": "goproj",
  "infLockFlag": false,
  "loadTestPath": "/codewind-workspace/goproj/load-test",
  "projectType": "docker",
  "buildLogPath": null,
  "state": "closed",
  "autoBuild": true
}bash-4.4$
```

**Comment by tobespc** [comment] 2019-10-31 11:31
closing this issus as the cli changes (providing you have the latest ones in the editor) fixes the sync issue.

**Comment by ssh24** [comment] 2019-10-31 13:10
I am still seeing the error with latest devfile. How often does the theia editor pick up the latest cli?
![Screen Shot 2019-10-31 at 9 09 56 AM](https://user-images.githubusercontent.com/15173354/67949567-4ca8ce00-fbbe-11e9-96b4-0ee4cf72aec3.png)

**Comment by tobespc** [comment] 2019-10-31 13:20
Its the filewatcher demon that needed to be updated as well.  I added a fix into the vscode to make sure it was pulling it as the package-lock was preventing the most recent one being pulled down

**Comment by tobespc** [comment] 2019-10-31 13:21
Will install all the components manually to make sure they all still work on latest

**Comment by maysunfaisal** [comment] 2019-10-31 13:57
The latest SC always pulls the latest FW as well, but that sync call from FW is during update right? 🤔

**Comment by tetchel** [comment] 2019-10-31 14:11
the filewatcher is not the cause of this but i will address pulling the latest filewatcher in my build script

**Comment by markcor11** [comment] 2019-10-31 16:01
Reproduced

**Comment by rajivnathan** [comment] 2019-10-31 16:24
Changing to stopship as we cannot ship until this has been verified fixed.

**Comment by tobespc** [comment] 2019-11-01 13:02
ok, so in my testing I can see that we are updating the files into the codewind-workspace inside the workspace.   Need to see why a build is not triggering

**Comment by johnmcollier** [comment] 2019-11-01 13:36
@tobespc Are you testing with my devfile with the PVC removed or with the master branch? Keep in mind if the Che workspace PVC still exists, syncing could still be broken and we wouldn't notice.

**Comment by tobespc** [comment] 2019-11-01 13:46
so I can see that all the files are updated into the project container, just not having a build kicked off

**Comment by johnmcollier** [comment] 2019-11-01 13:48
@tobespc When I remove the Che workspace volume mount, the files in PFE still don't get synced over.

**Comment by johnmcollier** [comment] 2019-11-01 13:56
Sidecar logs: [sidecar_logs.txt](https://github.com/eclipse/codewind/files/3798189/sidecar_logs.txt)

Specifically:
```
[2019-11-01 13:45:55.012] [281.108] Cwctl call completed, elapsed time of cwctl call: 30
[2019-11-01 13:45:55.012] [281.108] Successfully ran installer command: [ project] [ sync] [ -p] [ /projects/gotest] [ -i] [ 86a96160-fcad-11e9-a478-13c496935eea] [ -t] [ 1572615953729] 
[2019-11-01 13:45:55.013] [281.108] Output:Status: 400 Bad Request
```

**Comment by tobespc** [comment] 2019-11-01 14:50
ok, so I have confirmed that by ensuring the latest cli is installed in sidecar, the sync now works

```
/tmp $ ./cwctl project sync -p /projects/tobesliberty1 -i 35ca1b50-fca2-11e9-877f-33aa35fbf158 -t 15726108
Status: 200 OK
/tmp $ ```

**Comment by johnmcollier** [comment] 2019-11-01 15:23
Verified fixed with the latest CLI in the sidecar

**Comment by johnmcollier** [comment] 2019-11-04 21:40
Reopening as I'm seeing this issue again after merging into master:
```
[2019-11-04 21:36:11.932] [74.239] Successfully ran installer command: [ project] [ sync] [ -p] [ /projects/gotest] [ -i] [ 1e76e810-ff4b-11e9-a40e-e58078679932] [ -t] [ 0] 
[2019-11-04 21:36:11.932] [74.239] Output:Project connection file does not exist, creating default local connection
open /.codewind/config/connections/1e76e810-ff4b-11e9-a40e-e58078679932.json: no such file or directory

```

**Comment by johnmcollier** [comment] 2019-11-04 21:54
So I found the problem with the syncing.

It’s because the IDE calls the CLI to create the project (and thus the json file) It gets created at `/.codewind/config/connections/1e76e810-ff4b-11e9-a40e-e58078679932.json` on the Theia container. 

So when the CLI is triggered by the filewatcherd in the sidecar, it can't find that file, since it's located on the different container. Thus causing the above error.

**Comment by maysunfaisal** [comment] 2019-11-04 21:59
@johnmcollier so the first sync worked but subsequent ones never did?

**Comment by johnmcollier** [comment] 2019-11-04 21:59
@maysunfaisal Yup, projects build fine, but successive code changes aren't synced.

**Comment by maysunfaisal** [comment] 2019-11-04 22:01
@johnmcollier Not sure how one would solve this other than

1. cwctl being invoked from the sidecar always ie project creation and fw calls
2. sidecar and theia are merged

**Comment by johnmcollier** [comment] 2019-11-04 22:03
@maysunfaisal We don't need to merge the sidecar and Theia just yet:

3. Use the typescript filewatcher in Theia, keep the sidecar from nginx proxy and PFE deployment

**Comment by ebuckle** [comment] 2019-11-05 13:20
We have a shared workspace between the sidecar and Theia containers. 

We could save the config file into this shared workspace for sharing between the two. We would need some kind of detection to know which container we're in.

**Comment by markcor11** [comment] 2019-11-05 13:53
`CHE_PROJECTS_ROOT=/projects` should be in common between theia and sidecar

**Comment by jopit** [comment] 2019-11-05 18:57
This is no longer an IDE problem from what I can see, so I'm removing the ide label and adding portal

**Comment by jgwest** [comment] 2019-11-05 20:35
As I see it, here are the options for handling this, ordered by descending feasibility to deliver for 0.6.0:
1) Ideally the `cwctl project sync` command doesn't actually need the information from the file it is looking for when [that error message is thrown](https://github.com/eclipse/codewind/issues/906#issuecomment-549559673), and this step can be bypassed. This is the solution that Elson mentioned on Slack, and is the easiest short term fix.
or
2) IF the `cwctl project sync` command DOES need some of the information from the above file, AND the Go filewatcher happens to already have that information, then we could pass it additional parameters to the `cwctl project sync` command. (But, note that the Go filewatcher has very little additional information that isn't already provided to cwctl, basically only the server URL)
or
3) Move Go filewatcher into the Theia container. (this is probably 95% as much work as option 4, but less elegant of a solution, so option 4 is preferred)
or
4) Consume the TS filewatcher in Theia (I broke down the work on this item: https://github.com/eclipse/codewind/issues/606 )

Option 4 is the most elegant, and is definitely the medium-term goal for this scenario, but it would be tough to contain in 0.6.0 without significant release slippage.

**Comment by tobespc** [comment] 2019-11-06 14:15
done, pr in to the installer to fix

**Closed by tobespc** 2019-11-06 14:15 UTC
Labels: area/portal, kind/bug, priority/stopship, remote

**Comment by malincoln** [comment] 2019-11-06 15:36
@johnmcollier pls verify

**Comment by johnmcollier** [comment] 2019-11-06 20:42
Verified, fixed
