### ISSUE TITLE
Eclipse Manage Template Sources panel: can tab into non-editable areas

### ISSUE THREAD

**Issue by mattcolegate** [eclipse/codewind#780] opened 2019-10-22 10:34 UTC
**Codewind version:** latest hybrid
**OS:** Windows 10

**Che version:** N/A
**IDE extension version:** 0.5.0v201910171920
**IDE version:** 2019-06
**Kubernetes cluster:** N/A

**Description:** Tabbing through the panel tabs into the labels 'Add, remove, enable and disable template sources', 'Enable or disable template sources using the check boxes. Use the buttons...', and all the labels below the source box (only the URI content field should be accessible.

**Steps to reproduce:** Start Codewind. Right click on Local and select Manage Template Sources... . Press the tab key to cycle through the fields in the resulting panel. As well as editable fields and the buttons, the above labels also can be selected.

**Workaround:** N/A

**Comment by eharris369** [comment] 2019-10-22 12:59
This is a duplicate of #776.

**Closed by eharris369** 2019-10-22 12:59 UTC
Labels: duplicate, kind/bug
