### ISSUE TITLE
Auto Build is not working in Codewind for VSCode and Eclipse

### ISSUE THREAD

**Issue by johnmcollier** [eclipse/codewind#54] opened 2019-07-29 17:59 UTC
**Codewind Version:** Latest Development Version
**Eclipse Version:** Eclipse IDE for Enterprise Java Developers 4.11.0
**VS Code Version:** Code 1.35.1

**Operating Systems:**
- Mac Mojave 10.14.5
- VM with Windows 10

In VS Code, if you click on "AutoBuild", stop Codewind and start Codewind again, you will receive some error messages indicating that no logs were found and a 404 error in the file watcher. After that, if you try to enable the “Auto Build” option again, it will not work. In addition, the project never builds again and remains in an “Unknown” state. 
![image](https://media.github.ibm.com/user/210489/files/6f69ef80-9432-11e9-95b8-2e0dba2eec86)

In Eclipse, the same thing happens, but there are no errors on the screen and the projects have a status of “No build information”.
![image](https://media.github.ibm.com/user/210489/files/77299400-9432-11e9-8d87-65e16a00c37c)

**Comment by elsony** [comment] 2019-08-06 17:45
The cause of this problem is due to createProject has never been called by portal to turbine on the project if autobuild has been turned off.  When autobuild is being turned on again after Codwind restart, portal just call build instead of createProject on the first time build. Based on the last design discussion with @tobespc, the conclusion is to handle it on the portal side to make sure the first time build (e.g. via manual build or switching autobuild from disable to enable), portal will call createProject on the first time build instead of just calling build if portal has never call createProject on turbine to register the project before. Therefore, I am removing the iterative-dev area label since this will be handled by portal component.

**Comment by tetchel** [comment] 2019-08-15 21:08
It doesn't even look like the user can recover from this; I tried disable/enable but it still got stuck Unknown, so you have to remove and then re-bind the project.

**Comment by stalleyj** [comment] 2019-08-22 13:45
I am working on a fix for this which is 90% of the way there but still has a few issues.  The logs/capabilities/build action apis are all working with projects that have autoBuild = false.

**Comment by stalleyj** [comment] 2019-08-29 13:59
PR is ready for review https://github.com/eclipse/codewind/pull/330

**Comment by rajivnathan** [comment] 2019-09-03 15:20
Discussed this today with Elson, Toby and Julie. Came to the consensus that when Codewind starts up again, all **enabled** projects will be built once irrespective of whether auto build is on/off. The auto build setting only applies to subsequent builds. Users still have the option of disabling a project if they do not want it to be built and started.

**Comment by tobespc** [comment] 2019-09-09 09:59
this is now delivered

**Closed by tobespc** 2019-09-09 09:59 UTC
Labels: area/portal, kind/bug, priority/hot

**Comment by tetchel** [comment] 2019-09-09 13:28
@jagraj can you verify this in codewind master, when you have a chance
