### ISSUE TITLE
SVT:Default Websphere liberty project failed to build with the latest remote architecture.

### ISSUE THREAD

**Issue by jagraj** [eclipse/codewind#904] opened 2019-10-29 19:18 UTC
**Codewind version:** latest (0.6)
**OS:** WIndows

**Che version:**
**IDE extension version:** latest
**IDE version:**  eclipse 2019-09
**Kubernetes cluster:**

**Description:**
I installed latest eclipse plugin and installed latest codewind on my Windows VM. I tried to create Websphere liberty project and it is failed to build. Please find the attached pfe.txt log for more information.

**Steps to reproduce:**
1. Install latest eclipse plugin
2. Install latest codewind
3. Create Websphere liberty project.
4. Project failed to build.

![image](https://user-images.githubusercontent.com/713849/67801916-98ddfc00-fa60-11e9-82b0-ae4200abf88c.png)

[xaa.txt](https://github.com/eclipse/codewind/files/3785375/xaa.txt)
[xab.txt](https://github.com/eclipse/codewind/files/3785376/xab.txt)
[xac.txt](https://github.com/eclipse/codewind/files/3785377/xac.txt)
[xad.txt](https://github.com/eclipse/codewind/files/3785378/xad.txt)
[xae.txt](https://github.com/eclipse/codewind/files/3785379/xae.txt)
[xaf.txt](https://github.com/eclipse/codewind/files/3785380/xaf.txt)
[xag.txt](https://github.com/eclipse/codewind/files/3785381/xag.txt)
[xah.txt](https://github.com/eclipse/codewind/files/3785382/xah.txt)
[xai.txt](https://github.com/eclipse/codewind/files/3785383/xai.txt)
[xaj.txt](https://github.com/eclipse/codewind/files/3785384/xaj.txt)
[xak.txt](https://github.com/eclipse/codewind/files/3785385/xak.txt)
[xal.txt](https://github.com/eclipse/codewind/files/3785386/xal.txt)
[xam.txt](https://github.com/eclipse/codewind/files/3785387/xam.txt)
[xan.txt](https://github.com/eclipse/codewind/files/3785388/xan.txt)
[xao.txt](https://github.com/eclipse/codewind/files/3785389/xao.txt)
[xap.txt](https://github.com/eclipse/codewind/files/3785390/xap.txt)
[xaq.txt](https://github.com/eclipse/codewind/files/3785391/xaq.txt)
[xar.txt](https://github.com/eclipse/codewind/files/3785392/xar.txt)
[xas.txt](https://github.com/eclipse/codewind/files/3785393/xas.txt)
[xat.txt](https://github.com/eclipse/codewind/files/3785394/xat.txt)
[xau.txt](https://github.com/eclipse/codewind/files/3785395/xau.txt)
[xav.txt](https://github.com/eclipse/codewind/files/3785396/xav.txt)
[xaw.txt](https://github.com/eclipse/codewind/files/3785397/xaw.txt)
[xax.txt](https://github.com/eclipse/codewind/files/3785398/xax.txt)
[xay.txt](https://github.com/eclipse/codewind/files/3785399/xay.txt)

**Workaround:**

**Comment by elsony** [comment] 2019-10-29 20:49
@jagraj What are those txt files?  Are they supposed to be log files? They don't look like our regular log files. It mentioned docker image create failed. Is there any docker log or container log that you can share?

**Comment by mattcolegate** [comment] 2019-10-30 09:28
I've also recreated this on my Windows laptop. I don't seem to have a .logs directory created in my workspace, so I'm attaching the log from the pfe container.

**Comment by mattcolegate** [comment] 2019-10-30 09:40
[logs.txt](https://github.com/eclipse/codewind/files/3788031/logs.txt)

**Comment by tobespc** [comment] 2019-10-30 10:47
looks like when we copy files we are not using the correct directory structure on windows.  Files are copied across with a flat file structure

**Comment by tobespc** [comment] 2019-10-30 11:04
this is a dupe of #864 closing

**Closed by tobespc** 2019-10-30 11:04 UTC
Labels: area/portal, kind/bug, priority/stopship, remote
