### ISSUE TITLE
SVT: [Che] Build failures in some default applications, even if they are running

### ISSUE THREAD

**Issue by sujeilyfonseca** [eclipse/codewind#1099] opened 2019-11-12 21:56 UTC
**Codewind version:** 0.6.0
**OS:** Red Hat Enterprise Linux 7 (64 bit)

**Che version:** 7.2.0
**Kubernetes cluster:** OKD/Openshift

**Description:** Java Lagom and Swift projects are displayed as `[Running]` but with the status `[Build Failed - Creating image for build failed]`.

![Screen Shot 2019-11-12 at 4 41 49 PM](https://user-images.githubusercontent.com/49531960/68713223-5d1c5980-056b-11ea-8fa8-25ebe8d50640.png)

Both applications are running:

![Screen Shot 2019-11-12 at 4 41 30 PM](https://user-images.githubusercontent.com/49531960/68713250-6b6a7580-056b-11ea-9440-54b7a3ebe807.png)

![Screen Shot 2019-11-12 at 4 41 40 PM](https://user-images.githubusercontent.com/49531960/68713255-6dcccf80-056b-11ea-80f1-63775884869a.png)

Sometimes an error can be obtained when trying to access the logs:

![Screen Shot 2019-11-12 at 4 27 26 PM](https://user-images.githubusercontent.com/49531960/68713291-7d4c1880-056b-11ea-8e0c-cc341c5d8448.png)

**Pods:**
```
[root@sfonseca-okd-codewind ~]# oc get pods
NAME                                                              READY     STATUS    RESTARTS   AGE
che-59bb5f7dbb-vsmqj                                              1/1       Running   0          6h
che-operator-6f59664648-hdl5p                                     1/1       Running   0          6h
codewind-performance-workspace9j0h3pshywifitmv-6899b7bf9d-ssxvc   1/1       Running   0          1h
codewind-workspace9j0h3pshywifitmv-66dbf9c896-6s8z5               1/1       Running   0          1h
cw-cwstandardgo-e251b4e0-058b-11ea-99a3-f7599996b-w8f5s           1/1       Running   0          1h
cw-cwstandardlagom-e8849ee0-058b-11ea-99a3-5f787956d4-whd5t       1/1       Running   0          56m
cw-cwstandardlagom1-fe78c010-058f-11ea-99a3-6468cff888-7xld4      1/1       Running   0          28m
cw-cwstandardliberty-f4dba5d0-058b-11ea-99a3-6666d6b54-s8bkb      1/1       Running   0          57m
cw-cwstandardmicroprofile-0f9fe980-058c-11ea-99a3-55d7c48dqlj6j   1/1       Running   0          55m
cw-cwstandardnode-eeff4040-058b-11ea-99a3-c9f68678d-m67w2         1/1       Running   0          1h
cw-cwstandardpython-ff90bc90-058b-11ea-99a3-6bd7ccb97c-ckxqm      1/1       Running   0          1h
cw-cwstandardspringboot-072ad7b0-058c-11ea-99a3-59fb8b57cfztdxw   1/1       Running   0          58m
cw-cwstandardswift-0b9d0210-0590-11ea-99a3-5d847c877d-mnzbm       1/1       Running   0          28m
devfile-registry-5c774759b5-qwp98                                 1/1       Running   0          6h
keycloak-54d559d456-8zxt7                                         1/1       Running   0          6h
plugin-registry-69765c8c79-2jnf5                                  1/1       Running   0          6h
postgres-759896d9cd-vj7wl                                         1/1       Running   0          6h
tiller-deploy-57bcbcbbc8-swst6                                    1/1       Running   0          5h
workspace9j0h3pshywifitmv.che-jwtproxy-774cb888bc-8rx6z           1/1       Running   0          1h
workspace9j0h3pshywifitmv.che-workspace-pod-8c4468458-n6pxv       3/3       Running   0          1h
```

**Logs:**
[logs.zip](https://github.com/eclipse/codewind/files/3838368/logs.zip)

**Note:** This error may be intermittent.

@jagraj

**Comment by rajivnathan** [comment] 2019-11-13 21:17
I've seen this as well

**Comment by johnmcollier** [comment] 2019-11-15 21:36
Were the apps already running before the build failures occurred? I.e. was this after a project update and not during creation/import? If the build fails during an update before the app is redeployed (so the old app is still up) then Codewind would think it's still running.

The logs for the failed builds are interesting
```
runtime/cgo: pthread_create failed: Resource temporarily unavailable
SIGABRT: abort
PC=0x7f1ed21a7207 m=3 sigcode=18446744073709551610
goroutine 0 [idle]:
runtime: unknown pc 0x7f1ed21a7207
stack: frame={sp:0x7f1ecf850858, fp:0x0} stack=[0x7f1ecf0511b0,0x7f1ecf850db0)
00007f1ecf850758:  0000000000000000  0000000000000000 
00007f1ecf850768:  0000000000000000  0000000000000000 
00007f1ecf850778:  0000000000000000  0000000000000000 
00007f1ecf850788:  0000000000000000  0000000000000000 
00007f1ecf850798:  0000000000000000  0000000000000000 
00007f1ecf8507a8:  0000000000000000  0000000000000000 
00007f1ecf8507b8:  0000000000000000  0000000000000000 
00007f1ecf8507c8:  0000000000000000  0000000000000000 
00007f1ecf8507d8:  0000000000000000  0000000000000000 
00007f1ecf8507e8:  0000000000000000  0000000000000000 
00007f1ecf8507f8:  0000000000000000  0000000000000000 
00007f1ecf850808:  0000000000000000  0000000000000000 
00007f1ecf850818:  0000000000000000  0000000000000000 
00007f1ecf850828:  00007f1ed2538868  00005572e5e9f5bd 
00007f1ecf850838:  00007f1ec80008c0  00000000000000f1 
00007f1ecf850848:  0000000000000011  0000000000000000 
00007f1ecf850858: <00007f1ed21a88f8  0000000000000020 
00007f1ecf850868:  0000000000000000  0000000000000000 
00007f1ecf850878:  0000000000000000  0000000000000000 
00007f1ecf850888:  0000000000000000  0000000000000000 
00007f1ecf850898:  0000000000000000  0000000000000000 
00007f1ecf8508a8:  0000000000000000  0000000000000000 
00007f1ecf8508b8:  0000000000000000  0000000000000000 
00007f1ecf8508c8:  0000000000000000  0000000000000000 
00007f1ecf8508d8:  0000000000000000  000000000000000d 
00007f1ecf8508e8:  00007f1ed225fff9  0000000000000000 
00007f1ecf8508f8:  00007f1ed21eb0b3  000000000000000d 
00007f1ecf850908:  00007f1ed25381c0  0000000000000001 
00007f1ecf850918:  00007f1ed2538243  00007f1ed25343a0 
00007f1ecf850928:  00007f1ed21ec8ce  00007f1ed25381c0 
00007f1ecf850938:  000000000000000a  00007f1ec80008c0 
00007f1ecf850948:  00000000000000f1  0000000000000011 
runtime: unknown pc 0x7f1ed21a7207
stack: frame={sp:0x7f1ecf850858, fp:0x0} stack=[0x7f1ecf0511b0,0x7f1ecf850db0)
00007f1ecf850758:  0000000000000000  0000000000000000 
00007f1ecf850768:  0000000000000000  0000000000000000 
00007f1ecf850778:  0000000000000000  0000000000000000 
00007f1ecf850788:  0000000000000000  0000000000000000 
00007f1ecf850798:  0000000000000000  0000000000000000 
00007f1ecf8507a8:  0000000000000000  0000000000000000 
00007f1ecf8507b8:  0000000000000000  0000000000000000 
00007f1ecf8507c8:  0000000000000000  0000000000000000 
00007f1ecf8507d8:  0000000000000000  0000000000000000 
00007f1ecf8507e8:  0000000000000000  0000000000000000 
00007f1ecf8507f8:  0000000000000000  0000000000000000 
00007f1ecf850808:  0000000000000000  0000000000000000 
00007f1ecf850818:  0000000000000000  0000000000000000 
00007f1ecf850828:  00007f1ed2538868  00005572e5e9f5bd 
00007f1ecf850838:  00007f1ec80008c0  00000000000000f1 
00007f1ecf850848:  0000000000000011  0000000000000000 
00007f1ecf850858: <00007f1ed21a88f8  0000000000000020 
00007f1ecf850868:  0000000000000000  0000000000000000 
00007f1ecf850878:  0000000000000000  0000000000000000 
00007f1ecf850888:  0000000000000000  0000000000000000 
00007f1ecf850898:  0000000000000000  0000000000000000 
00007f1ecf8508a8:  0000000000000000  0000000000000000 
00007f1ecf8508b8:  0000000000000000  0000000000000000 
00007f1ecf8508c8:  0000000000000000  0000000000000000 
00007f1ecf8508d8:  0000000000000000  000000000000000d 
00007f1ecf8508e8:  00007f1ed225fff9  0000000000000000 
00007f1ecf8508f8:  00007f1ed21eb0b3  000000000000000d 
00007f1ecf850908:  00007f1ed25381c0  0000000000000001 
00007f1ecf850918:  00007f1ed2538243  00007f1ed25343a0 
00007f1ecf850928:  00007f1ed21ec8ce  00007f1ed25381c0 
00007f1ecf850938:  000000000000000a  00007f1ec80008c0 
00007f1ecf850948:  00000000000000f1  0000000000000011 
```

That's coming straight from Docker (same error as https://github.com/docker/for-linux/issues/343), indicating something's using up all of the processes.

**Comment by johnmcollier** [comment] 2019-11-15 21:42
@sujeilyfonseca Something has exhausted all of the processes on the node that's running Codewind, causing the build failures. I would try restarting the Codewind workspace and seeing if they still persist, and if so, try restarting the node that's running Codewind (can find the node with kubectl describe pod <codewind>`)

**Comment by sujeilyfonseca** [comment] 2019-11-19 01:09
After following your suggestions, this problem was resolved in my cluster.

Thanks for addressing this problem, @johnmcollier! Thanks for the recommendation, @jgwest!

**Comment by johnmcollier** [comment] 2019-11-19 17:13
Closing out as our error status was functioning as intended here - Opened https://github.com/eclipse/codewind/issues/1164 for long-term stress testing of Codewind

**Closed by johnmcollier** 2019-11-19 17:13 UTC
Labels: area/iterative-dev, kind/bug, priority/hot
