### ISSUE TITLE
SVT:ODO projects failed to build from codewind che workspace

### ISSUE THREAD

**Issue by jagraj** [eclipse/codewind#675] opened 2019-10-14 19:52 UTC
**Codewind version:** 0.5.0
**OS:** RHEL

**Che version:** 7.2.0
**IDE extension version:** 0.5.0
**IDE version:**7.2.0
**Kubernetes cluster:**
OKD Cluster

**Description:**
I have Codewind 0.5.0 version installed from Eclipse che. I created ODO projects and they failed to show the status for the projects. Here are I am attaching logs and screenshot from the failure. 
I did apply role bindings needed for ODO projects. When I look at the pod status and they all up and running.

```
kubectl get pods
NAME                                                              READY     STATUS    RESTARTS   AGE
che-7fbd6b89b4-5m9vn                                              1/1       Running   0          4h
che-operator-6f59664648-j5qlp                                     1/1       Running   0          4h
codewind-performance-workspacerpe2jbd9t1tadrg4-79b8748fcf-gm6fg   1/1       Running   0          3h
codewind-workspacerpe2jbd9t1tadrg4-747fd5f98-nhz6h                1/1       Running   0          3h
cw-dotnetokdcw05svt-app-1-hjpnr                                   1/1       Running   0          2h
cw-gookdcw05svt-f725fe20-ee99-11e9-88de-5cb795476-6bmbs           1/1       Running   0          3h
cw-httpdokdcw05svt-app-1-bmbks                                    1/1       Running   0          2h
cw-javampokdcw05svt-1223b670-ee9c-11e9-88de-74dc49c448-c9kpm      1/1       Running   0          3h
cw-lagomokdcw05svt-049579f0-ee9a-11e9-88de-d57b7854b-wsk76        1/1       Running   0          3h
cw-nodejsokdcw05svt-0f1724a0-ee9a-11e9-88de-764d677fc5-pm4qb      1/1       Running   0          3h
cw-olokdcw05svt-dc54d740-ee9b-11e9-88de-6f7885fbdd-2ndmn          1/1       Running   3          3h
cw-pythonodookdcw05svt-app-1-dx4jf                                1/1       Running   0          1h
cw-pythonokdcw05svt-e6469e00-ee9b-11e9-88de-76c89b58d-brj4v       1/1       Running   0          3h
cw-springokdcw05svt-f0d7b200-ee9b-11e9-88de-6db9b8b78-7446r       1/1       Running   0          3h
cw-swiftokdcw05svt-fd8e3e10-ee9b-11e9-88de-5ff595877d-fqqk2       1/1       Running   0          3h
devfile-registry-5c774759b5-q8zpt                                 1/1       Running   0          4h
keycloak-66c74b7599-snk7v                                         1/1       Running   0          4h
plugin-registry-69765c8c79-j6d95                                  1/1       Running   0          4h
postgres-864b695569-nhs8q                                         1/1       Running   0          4h
tiller-deploy-57bcbcbbc8-m7hjw                                    1/1       Running   0          4h
workspacerpe2jbd9t1tadrg4.che-jwtproxy-57584dbb4b-lgbb8           1/1       Running   0          3h
workspacerpe2jbd9t1tadrg4.che-workspace-pod-6c9f9c7db7-v4pc7      3/3       Running   0          3h
```

ODO Projects created ..

1. dotnetokdcw05svt (.Net)
2. httpdokdcw05svt (HTTPD)
3. pythonodookdcw05svt (Python)

Logs..
[codewind-workspace.txt](https://github.com/eclipse/codewind/files/3726190/codewind-workspace.txt)

![image](https://user-images.githubusercontent.com/713849/66777707-a196d580-ee97-11e9-8114-025a70c61b4a.png)

**Steps to reproduce:**
1. Install codewind from Eclipse che workspaces.
2. Create ODO projects and they failed to build.
3. You can see ODO projects are in failed state in the workspace.

**Workaround:**

**Comment by GeekArthur** [comment] 2019-10-15 13:36
I will investigate this.

**Comment by GeekArthur** [comment] 2019-10-15 16:23
I can reproduce the issue for `httpd` and `dotnet` projects.

This issue is due to `s2i` base image doesn't install `rsync`, I will open an issue against odo but I don't think they can fix this before our `0.5.0` release, so in the meantime I will disable `httpd` and `dotnet`.

**Comment by ssh24** [comment] 2019-10-15 16:28
I also cannot build a dotnet project
```
[15/10/19 16:26:31 mydotnet] [TRACE] OK
[15/10/19 16:26:31 mydotnet] [TRACE] 
Step 2 of 4:

[15/10/19 16:26:31 mydotnet] [TRACE] - Building and deploying odo component: cw-mydotnet

[15/10/19 16:26:31 mydotnet] [TRACE]  ✗  projectrequests.project.openshift.io is forbidden: User "system:serviceaccount:che:che-workspace" cannot create projectrequests.project.openshift.io at the cluster scope: no RBAC policy matched

[15/10/19 16:26:31 mydotnet] [TRACE] - Failed to build and deploy odo component: cw-mydotnet

[15/10/19 16:26:31 mydotnet] [TRACE] updateBuildState 8b26bdc0-ef68-11e9-a3b1-9f6a612d47bc failed buildscripts.odoBuildPushFailMsg  

[15/10/19 16:26:31 mydotnet] [TRACE] Sending update build state post for project 8b26bdc0-ef68-11e9-a3b1-9f6a612d47bc and state failed
curl -sS -k -X POST -H Content-Type: application/json -d {"projectID": "8b26bdc0-ef68-11e9-a3b1-9f6a612d47bc", "buildStatus": "failed", "detailedBuildStatus": "buildscripts.odoBuildPushFailMsg", "type": "buildState"} https://localhost:9191/internal/api/v1/projects/updateStatus

[15/10/19 16:26:31 server.js] [TRACE] Checking origin host  matches expected host localhost:9191
[15/10/19 16:26:31 server.js] [TRACE] POST /internal/api/v1/projects/updateStatus called with 
 req.body { projectID: '8b26bdc0-ef68-11e9-a3b1-9f6a612d47bc',
  buildStatus: 'failed',
  detailedBuildStatus: 'buildscripts.odoBuildPushFailMsg',
  type: 'buildState' }
[15/10/19 16:26:31 /portal/routes/projects/internal.route.js] [DEBUG] Internal API: updateStatus
[15/10/19 16:26:31 User.js] [INFO] Updating status for project 8b26bdc0-ef68-11e9-a3b1-9f6a612d47bc.
[15/10/19 16:26:31 Turbine] [TRACE] Key translated. Returning message: Failed to build or deploy odo application
[15/10/19 16:26:31 FileWatcher.js] [DEBUG] Portal's event listener: projectStatusChanged
[15/10/19 16:26:31 FileWatcher.js] [DEBUG] Portal's event listener: {"projectID":"8b26bdc0-ef68-11e9-a3b1-9f6a612d47bc","buildStatus":"failed","detailedBuildStatus":"Failed to build or deploy odo application","lastbuild":1571156791434}
[15/10/19 16:26:31 FileWatcher.js] [ERROR] projectStatusChanged: failed (project: {
  "projectID": "8b26bdc0-ef68-11e9-a3b1-9f6a612d47bc",
  "buildStatus": "failed",
  "detailedBuildStatus": "Failed to build or deploy odo application",
  "lastbuild": 1571156791434
})
```

**Comment by GeekArthur** [comment] 2019-10-15 16:30
@ssh24 See my comments above.

**Comment by GeekArthur** [comment] 2019-10-15 17:55
Open issue against ODO: https://github.com/openshift/odo/issues/2289

**Comment by jagraj** [comment] 2019-10-16 14:35
@GeekArthur 
I still see httpd and dotnet templates in my latest workspace.

![Screen Shot 2019-10-16 at 10 16 55 AM](https://user-images.githubusercontent.com/713849/66929191-97dcb180-f000-11e9-8505-e89bf1b29431.png)

**Comment by GeekArthur** [comment] 2019-10-16 14:55
@jagraj That's is because the latest 0.5.0 image is not pushed to Dockerhub, from the screenshot below, the 0.5.0 image is 7 days ago but fix PR is merged yesterday, so it doesn't have my fix. You can check with @josephca to let him update the 0.5.0 image on Dockerhub.
![Screen Shot 2019-10-16 at 10 52 42 AM](https://user-images.githubusercontent.com/15131537/66930839-323df480-f003-11e9-8e19-ed3886106ccc.png)

**Comment by malincoln** [comment] 2019-10-17 19:03
@jagraj just gave update that he successfully verified the fix.  @GeekArthur and @ssh24 can you pls close.  Thanks

**Comment by elsony** [comment] 2019-10-17 19:10
Closing as requested on preview comment

**Closed by elsony** 2019-10-17 19:10 UTC
Labels: area/iterative-dev, kind/bug, priority/stopship
