### ISSUE TITLE
Error `/favicon.ico' not found

### ISSUE THREAD

**Issue by micgibso** [eclipse/codewind#2301] opened 2020-02-25 09:18 UTC
**Codewind version:** Latest
**OS:** Windows

**Description:**
Running Codewind locally on Windows produces the following error:
`[2020-02-25 03:12:02] ERROR `/favicon.ico' not found.`

**Steps to reproduce:**
1. Run Codewind on localhost:
   $ docker login
   $ docker run --rm -it --volume="$PWD/docs:/srv/jekyll" --volume="$PWD/vendor/bundle:/usr/local/bundle" -p 4321:4321 jekyll/jekyll:3.8.5 jekyll serve --port 4321 --host 0.0.0.0
2. Click Docs in the header bar
3. Click News. The error occurs every time you click News.

![image](https://user-images.githubusercontent.com/7224752/75232827-cc7f2780-57af-11ea-8d03-7e0d72d9612f.png)

**Workaround:** 
None that I found.

**Comment by micgibso** [comment] 2020-02-25 09:19
@sghung Fyi, thanks

**Comment by sishida** [comment] 2020-02-25 15:55
Didn't we used to have a "like" button on the news pages? It looks like that is no longer being pulled in. I don't see it on the news pages anymore.

**Comment by sishida** [comment] 2020-02-25 16:05
I did some investigating...
1️⃣There's this image called "favicon.ico": https://github.com/eclipse/codewind-docs/blob/master/docs/favicon.ico
2️⃣ The `head.html` also mentions favicon: https://github.com/eclipse/codewind-docs/edit/master/docs/_includes/head.html

**Comment by sghung** [comment] 2020-02-25 18:41
@micgibso and @sishida This error looks to be a jekyll problem: https://talk.jekyllrb.com/t/favicon-ico-not-found/2571/3

It is the same behaviour we're seeing, when it is a non-home page, you see this error.

However, if I am using the google inspector with the console enabled on the live site, I don't see that problem. You can also confirm that on the news page, you do see the icon.

The favicon.ico exists. You can verify it in the _sites directory when it is generated. It is in the home directory.

I would argue that this is a jeyll issue and we can't do anything about it. I can look into it a bit more, but I don't think we should be spending hours fixing this bug.

**Comment by sishida** [comment] 2020-02-25 19:22
@sghung Thanks for letting us know! I'll update our Box doc with a note mentioning this false positive.

Since it looks like it's a Jekyll issue and not harming anything on our side, I am OK with closing this issue. :)

**Comment by sghung** [comment] 2020-02-25 19:31
I also was trying to play around with this and had a hard time reproducing this issue consistently. Sometimes Jekyll complains and sometimes it doesn't. As a result. based on the last comment and some additional investigation on my side, I think this is a false warning and we can confirm in our website (both locally and live) that the icons aren't missing.

**Closed** 2020-02-26 07:58 UTC
Labels: area/docs, area/website, kind/bug
