### ISSUE TITLE
Generated client won't build

### ISSUE THREAD

**Issue by NottyCode** [eclipse/codewind#550] opened 2019-09-24 16:38 UTC
After generating the client into my project I run mvn verify and get the following errors:

```
[INFO] -------------------------------------------------------------
[ERROR] COMPILATION ERROR :
[INFO] -------------------------------------------------------------
[ERROR] /Users/nottinga/Documents/github/guides/guide-microprofile-openapi/finish/src/test/java/org/openapitools/api/DefaultApiTest.java:[28,30] package org.openapitools.model does not exist
[ERROR] /Users/nottinga/Documents/github/guides/guide-microprofile-openapi/finish/src/test/java/org/openapitools/api/DefaultApiTest.java:[39,40] package com.fasterxml.jackson.jaxrs.json does not exist
[ERROR] /Users/nottinga/Documents/github/guides/guide-microprofile-openapi/finish/src/test/java/org/openapitools/api/DefaultApiTest.java:[59,13] cannot find symbol
  symbol:   class DefaultApi
  location: class org.openapitools.api.DefaultApiTest
[ERROR] /Users/nottinga/Documents/github/guides/guide-microprofile-openapi/finish/src/test/java/org/openapitools/api/DefaultApiTest.java:[63,9] cannot find symbol
  symbol:   class JacksonJsonProvider
  location: class org.openapitools.api.DefaultApiTest
[ERROR] /Users/nottinga/Documents/github/guides/guide-microprofile-openapi/finish/src/test/java/org/openapitools/api/DefaultApiTest.java:[63,44] cannot find symbol
  symbol:   class JacksonJsonProvider
  location: class org.openapitools.api.DefaultApiTest
[ERROR] /Users/nottinga/Documents/github/guides/guide-microprofile-openapi/finish/src/test/java/org/openapitools/api/DefaultApiTest.java:[67,66] cannot find symbol
  symbol:   class DefaultApi
  location: class org.openapitools.api.DefaultApiTest
[INFO] 6 errors
[INFO] -------------------------------------------------------------
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time:  13.288 s
[INFO] Finished at: 2019-09-24T11:37:01-05:00
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal org.apache.maven.plugins:maven-compiler-plugin:3.1:testCompile (default-testCompile) on project mp-openapi: Compilation failure: Compilation failure:
[ERROR] /Users/nottinga/Documents/github/guides/guide-microprofile-openapi/finish/src/test/java/org/openapitools/api/DefaultApiTest.java:[28,30] package org.openapitools.model does not exist
[ERROR] /Users/nottinga/Documents/github/guides/guide-microprofile-openapi/finish/src/test/java/org/openapitools/api/DefaultApiTest.java:[39,40] package com.fasterxml.jackson.jaxrs.json does not exist
[ERROR] /Users/nottinga/Documents/github/guides/guide-microprofile-openapi/finish/src/test/java/org/openapitools/api/DefaultApiTest.java:[59,13] cannot find symbol
[ERROR]   symbol:   class DefaultApi
[ERROR]   location: class org.openapitools.api.DefaultApiTest
[ERROR] /Users/nottinga/Documents/github/guides/guide-microprofile-openapi/finish/src/test/java/org/openapitools/api/DefaultApiTest.java:[63,9] cannot find symbol
[ERROR]   symbol:   class JacksonJsonProvider
[ERROR]   location: class org.openapitools.api.DefaultApiTest
[ERROR] /Users/nottinga/Documents/github/guides/guide-microprofile-openapi/finish/src/test/java/org/openapitools/api/DefaultApiTest.java:[63,44] cannot find symbol
[ERROR]   symbol:   class JacksonJsonProvider
[ERROR]   location: class org.openapitools.api.DefaultApiTest
[ERROR] /Users/nottinga/Documents/github/guides/guide-microprofile-openapi/finish/src/test/java/org/openapitools/api/DefaultApiTest.java:[67,66] cannot find symbol
[ERROR]   symbol:   class DefaultApi
[ERROR]   location: class org.openapitools.api.DefaultApiTest
[ERROR] -> [Help 1]
[ERROR]
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR]
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/MojoFailureException
```

I'm pretty sure this is because the generated client was written into a `src/gen/java` folder rather than `src/main/java` and no update to my maven pom was made to cause that to be built.

**Comment by keithchong** [comment] 2019-09-25 18:10
@sghung , please resolve this as a dup of https://github.com/eclipse/codewind/issues/79

Maven project customizations/setup.

**Comment by sghung** [comment] 2019-09-25 19:27
Closing based on Keith's comment regarding this being a dupe of #79

**Closed by sghung** 2019-09-25 19:27 UTC
Labels: area/openapi

**Comment by MultiStorm** [comment] 2020-12-17 09:13
What was the solution to this problem?
I have exactly the same difficulties!
