### ISSUE TITLE
SVT:Appsody projects are stuck in "Starting" state even though container log says application up and running

### ISSUE THREAD

**Issue by jagraj** [eclipse/codewind#715] opened 2019-10-17 13:43 UTC
**Codewind version:** 0.5.0
**OS:** WIndows

**Che version:**
**IDE extension version:** 0.5.0
**IDE version:**  Eclipse 2019-09
**Kubernetes cluster:**

**Description:**
I created bunch of Appsody and Default template projects from my eclipse workspace with Codewind 0.5.0 version. After all projects up and running, I stopped codewind and uninstall codewind images to get the latest from the docker hub with the fixes. After building and deploying all projects I see default template projects all up and running but not all appsody projects.

**Steps to reproduce:**

1. Install Codewind 0.5.0 from Eclipse plugin.
2. Create default and appsody projects for each templates.
3. Wait until all projects built and running.
4. Stop codewind and uninstall codewind.
5. Install codewind and it will build all projects.
6. I see all default template projects up and running but appsody projects status stuck in "Starting" or "Stopped" state. 

Log:
[pfe.txt](https://github.com/eclipse/codewind/files/3739571/pfe.txt)

![image](https://user-images.githubusercontent.com/713849/67013686-7ee80500-f0c1-11e9-8360-16e730f336bc.png)

Here is app log says it is up and running but the status not reflected.

```
[Container] [INFO] [AUDIT   ] CWWKT0016I: Web application available (default_host): http://1e1c33b0fb6e:9080/javametrics/
[Container] [INFO] [AUDIT   ] CWWKZ0001I: Application javametrics-rest started in 4.061 seconds.
[Container] [INFO] [AUDIT   ] CWWKT0016I: Web application available (default_host): http://1e1c33b0fb6e:9080/
[Container] [INFO] [AUDIT   ] CWWKZ0001I: Application starter-app started in 9.547 seconds.
[Container] [INFO] [AUDIT   ] CWWKF0012I: The server installed the following features: [appSecurity-2.0, cdi-2.0, concurrent-1.0, distributedMap-1.0, jaxrs-2.1, jaxrsClient-2.1, jndi-1.0, json-1.0, jsonb-1.0, jsonp-1.1, jwt-1.0, managedBeans-1.0, microProfile-3.0, mpConfig-1.3, mpFaultTolerance-2.0, mpHealth-2.0, mpJwt-1.1, mpMetrics-2.0, mpOpenAPI-1.1, mpOpenTracing-1.3, mpRestClient-1.3, opentracing-1.3, servlet-4.0, ssl-1.0, websocket-1.1].
[Container] [INFO] [AUDIT   ] CWWKF0011I: The defaultServer server is ready to run a smarter planet. The defaultServer server started in 48.789 seconds.
```

```
docker ps -a
CONTAINER ID        IMAGE                                                   COMMAND                  CREATED             STATUS              PORTS                                                                                                 NAMES
8c6aaff44fac        cw-olcw05svt-e53233b0-ee8e-11e9-baab-99b3b1176a2a       "/opt/ol/helpers/run…"   About an hour ago   Up About an hour    0.0.0.0:32808->9080/tcp, 0.0.0.0:32807->9443/tcp                                                      cw-olcw05svt-e53233b0-ee8e-11e9-baab-99b3b1176a2a
facafd256f44        appsody/nodejs-loopback:0.1                             "/appsody/appsody-co…"   About an hour ago   Up About an hour    0.0.0.0:32806->3000/tcp, 0.0.0.0:32805->9229/tcp                                                      cw-appsodynodejslbcw05svt-409d2270-ee8d-11e9-baab-99b3b1176a2a
7821be46a09e        appsody/swift:0.1                                       "/appsody/appsody-co…"   About an hour ago   Up About an hour    0.0.0.0:32804->8080/tcp                                                                               cw-appsodyswiftcw05svt-9149cb50-ee8e-11e9-baab-99b3b1176a2a
80b176d2a748        appsody/python-flask:0.1                                "/appsody/appsody-co…"   About an hour ago   Up About an hour    0.0.0.0:32803->5678/tcp, 0.0.0.0:32802->8080/tcp                                                      cw-appsodypythoncw05svt-38913d40-ee8e-11e9-baab-99b3b1176a2a
62ac0067bb13        appsody/nodejs-express:0.2                              "/appsody/appsody-co…"   About an hour ago   Up About an hour    0.0.0.0:32801->3000/tcp, 0.0.0.0:32800->9229/tcp                                                      cw-appsodynodejsskacw05svt-3cd6a490-ee8d-11e9-baab-99b3b1176a2a
bb55744dbf6c        appsody/nodejs:0.2                                      "/appsody/appsody-co…"   About an hour ago   Up About an hour    0.0.0.0:32797->3000/tcp, 0.0.0.0:32796->9229/tcp                                                      cw-appsodynodejsdefcw05svt-7e9da1d0-ee8d-11e9-baab-99b3b1176a2a
1e1c33b0fb6e        appsody/java-microprofile:0.2                           "/appsody/appsody-co…"   About an hour ago   Up About an hour    0.0.0.0:32795->7777/tcp, 0.0.0.0:32794->9080/tcp, 0.0.0.0:32793->9443/tcp                             cw-appsodyempcw04svt-c226ea80-ee77-11e9-b6ee-c7aea732692d
88fd2cd137b7        appsody/java-microprofile:0.2                           "/appsody/appsody-co…"   About an hour ago   Up About an hour    0.0.0.0:32792->7777/tcp, 0.0.0.0:32791->9080/tcp, 0.0.0.0:32790->9443/tcp                             cw-swiftcw05svt-010755b0-ee90-11e9-baab-99b3b1176a2a
f750f1b54199        appsody/java-spring-boot2:0.3                           "/appsody/appsody-co…"   About an hour ago   Up About an hour    0.0.0.0:32789->5005/tcp, 0.0.0.0:32788->8080/tcp, 0.0.0.0:32786->8443/tcp, 0.0.0.0:32784->35729/tcp   cw-appsodyspringkotcw05svt-44c61630-ee8e-11e9-baab-99b3b1176a2a
b48f006e8826        appsody/java-spring-boot2:0.3                           "/appsody/appsody-co…"   About an hour ago   Up About an hour    0.0.0.0:32787->5005/tcp, 0.0.0.0:32785->8080/tcp, 0.0.0.0:32783->8443/tcp, 0.0.0.0:32782->35729/tcp   cw-appsodyspringdefcw05svt-3de6e6a0-ee8e-11e9-baab-99b3b1176a2a
b1134a494ca8        cw-pythoncw05svt-f60573f0-ee8e-11e9-baab-99b3b1176a2a   "python app.py"          About an hour ago   Up About an hour    0.0.0.0:32781->5000/tcp                                                                               cw-pythoncw05svt-f60573f0-ee8e-11e9-baab-99b3b1176a2a
5206000d351c        cw-javampcw05svt-975e6270-ee8f-11e9-baab-99b3b1176a2a   "/home/default/artif…"   About an hour ago   Up About an hour    127.0.0.1:32772->7777/tcp, 0.0.0.0:32780->9080/tcp, 0.0.0.0:32779->9443/tcp                           cw-javampcw05svt-975e6270-ee8f-11e9-baab-99b3b1176a2a
68f4a8cafc9c        cw-springcw04svt-dc3cc5c0-ee77-11e9-b6ee-c7aea732692d   "/scripts/new_entryp…"   About an hour ago   Up About an hour    127.0.0.1:32771->7777/tcp, 0.0.0.0:32778->8080/tcp                                                    cw-springcw04svt-dc3cc5c0-ee77-11e9-b6ee-c7aea732692d
2ff3c92f2a6d        cw-lagomcw05svt-b50d5f70-ee8e-11e9-baab-99b3b1176a2a    "java -cp /deploymen…"   About an hour ago   Up About an hour    0.0.0.0:32777->8778/tcp, 0.0.0.0:32776->9000/tcp, 0.0.0.0:32775->9779/tcp                             cw-lagomcw05svt-b50d5f70-ee8e-11e9-baab-99b3b1176a2a
df20985cd49b        cw-gocw05svt-a71c7ea0-ee8e-11e9-baab-99b3b1176a2a       "/app/main"              About an hour ago   Up About an hour    0.0.0.0:32774->8000/tcp                                                                               cw-gocw05svt-a71c7ea0-ee8e-11e9-baab-99b3b1176a2a
eb7285a07ef1        cw-nodejscw05svt-c4804c60-ee8e-11e9-baab-99b3b1176a2a   "docker-entrypoint.s…"   About an hour ago   Up About an hour    0.0.0.0:32773->3000/tcp, 127.0.0.1:32770->9229/tcp                                                    cw-nodejscw05svt-c4804c60-ee8e-11e9-baab-99b3b1176a2a
02f4e01c041c        codewind-pfe-amd64:0.5.0                                "sh -c ' /file-watch…"   About an hour ago   Up About an hour    127.0.0.1:10000->9090/tcp                                                                             codewind-pfe
776c652b503b        codewind-performance-amd64:0.5.0                        "docker-entrypoint.s…"   About an hour ago   Up About an hour    127.0.0.1:9095->9095/tcp                                                                              codewind-performance
```

**Workaround:**

**Comment by sghung** [comment] 2019-10-17 14:23
@makandre can you take a look?

**Comment by laven26** [comment] 2019-10-17 14:40
@sghung I can take a look

**Comment by makandre** [comment] 2019-10-19 01:04
@sghung said one of the symptoms seen was a projectCreation event getting emitted after the container starts. That’s suspiciously like the symptoms we saw in #720. It’s possible that, if projectCreation is the last event received for a project, maybe the app status in that event (starting?) gets shown by eclipse plugin. 

cc @eharris369

**Comment by eharris369** [comment] 2019-10-21 13:13
On a projectCreation event, Codewind Eclipse does a full refresh of the project - it calls api/v1/projects and uses the result of that to update the project so it does not rely on what is in the projectCreation event for the status.

**Comment by jagraj** [comment] 2019-10-21 16:18
Here are the logs with the latest release images and eclipse 0.5.0 plugin. After codewind restart (Appsody microprofile, Appsody NodeJS Default, AppsodyPython) are in "Starting" state and Appsody Nodejs Simple project in "Stopped" state.

![image](https://user-images.githubusercontent.com/713849/67223016-7dd61100-f3fc-11e9-9fe0-96a5e760951e.png)

[pfe-10212019.txt](https://github.com/eclipse/codewind/files/3751864/pfe-10212019.txt)
[appsody.log](https://github.com/eclipse/codewind/files/3751868/appsody.log)
[appsody.log](https://github.com/eclipse/codewind/files/3751870/appsody.log)
[appsody.log](https://github.com/eclipse/codewind/files/3751874/appsody.log)
[appsody.log](https://github.com/eclipse/codewind/files/3751879/appsody.log)

**Comment by makandre** [comment] 2019-10-21 16:28
"Appsody Nodejs Simple project in "Stopped" state." <- If this is the `nodejs` stack and not the `nodejs-express` stack, then it is expected to be `Stopped`

**Comment by makandre** [comment] 2019-10-21 16:32
Your `nodejs-express` app hit this intermittent problem which has been reported on slack chat.

```
K[?25h[37;40mnpm[0m [0m[31;40mERR![0m [0m[35mcode[0m ENOAUDIT
[Container] [0m[37;40mnpm[0m [0m[31;40mERR![0m [0m[35maudit[0m Your configured registry (https://registry.npmjs.org/) does not support audit requests, or the audit endpoint is temporarily unavailable.
[Container] [0m
[Container] [37;40mnpm[0m [0m[31;40mERR![0m[35m[0m A complete log of this run can be found in:
[Container] [0m[37;40mnpm[0m [0m[31;40mERR![0m[35m[0m     /root/.npm/_logs/2019-10-21T14_22_34_830Z-debug.log
[Container] [0m[Error] FATAL error APPSODY_PREP command received an error.  The controller is exiting: exit status 1
```
A request to build the app again should fix this one.

**Comment by eharris369** [comment] 2019-10-21 16:42
I reproduced this on my machine and it looks like the timeout problem:
```
^[[32m[21/10/19 16:29:26 appsodyNode2] [INFO]^[[39m Emitting event
 message: projectStatusChanged
 data: {
  "projectID": "23265b30-f0f9-11e9-92ab-717b0ba0ac64",
  "appStatus": "stopped",
  "appErrorStatus": "Failed to ping application due to timeout."
}
```
```
^[[32m[21/10/19 16:29:12 appsodySwift1] [INFO]^[[39m Emitting event
 message: projectStatusChanged
 data: {
  "projectID": "b1d24060-f0f9-11e9-92ab-717b0ba0ac64",
  "appStatus": "stopped",
  "appErrorStatus": "Failed to ping application due to timeout."
}
```

**Comment by eharris369** [comment] 2019-10-21 16:54
I guess it is not exactly the same since these are in stopped state but what was the resolution for the timeout issue?  Is there a setting for adjusting the timeout for a project that the IDEs can expose to the user?

**Comment by makandre** [comment] 2019-10-21 17:06
I think stopped apps will eventually get re-pinged by https://github.com/eclipse/codewind/blob/master/src/pfe/file-watcher/server/src/controllers/projectStatusController.ts#L375 which specifically looks at apps in `stopped` or `started`

I think I finally reproduced this once, from what I could tell, the last status change for the project was `started` (i.e. not a timeout), yet it was still showing as `stopped` in Eclipse.

**Comment by makandre** [comment] 2019-10-22 04:10
Got a couple of PRs that will hopefully address this issue.  It was still only intermittently reproducible but I tracked it down to 2 causes:

1. For apps that are stuck in stopped state, it appears Codewind was pinging the wrong port.  This happens because Codewind relies on the `stdout` from the appsody extension's `entrypoint.sh` script to map a stack to ports, but this mechanism seems to be intermittently unreliable (sometimes there are missing lines).

2. Codewind was triggering builds of appsody projects when files changed, but this is unnecessary because Appsody itself watches for file changes and it does not need external re-builds.  I believe this caused some interference with the app status and mainly affected apps stuck in starting state.

**Comment by jagraj** [comment] 2019-10-22 19:32
@makandre 

Thanks for the fix, I moved to latest drivers and started codewind with all the projects from the workspace. The fix did improve the issue but I still see some projects in the bad state. Here are the logs and screenshot from the failure. I reproduced on one of windows machine from the pool.
I see some of the containers using same images for different projects. Is that valid.?

I will go ahead and share machine details via slack.

[pfe.txt](https://github.com/eclipse/codewind/files/3757969/pfe.txt)
[appsody.log](https://github.com/eclipse/codewind/files/3758029/appsody.log)
[appsody.log](https://github.com/eclipse/codewind/files/3758033/appsody.log)
[appsody.log](https://github.com/eclipse/codewind/files/3758036/appsody.log)



![image](https://user-images.githubusercontent.com/713849/67322254-c0701a00-f4de-11e9-99bf-2251cf99d6b5.png)

```
CONTAINER ID        IMAGE                                                       COMMAND                  CREATED             STATUS              PORTS                                                                                                 NAMES
aa478a356b66        cw-javawlcw05svt-dfcf20f0-f42d-11e9-83a2-f72517aa6715       "/home/default/artif…"   About an hour ago   Up About an hour    127.0.0.1:32773->7777/tcp, 0.0.0.0:32827->9080/tcp, 0.0.0.0:32826->9443/tcp                           cw-javawlcw05svt-dfcf20f0-f42d-11e9-83a2-f72517aa6715
cdb709aa1b1b        cw-swiftcw05svt-48203c30-f4b9-11e9-83a2-f72517aa6715        "sh -c 'cd /swift-pr…"   About an hour ago   Up About an hour    0.0.0.0:32825->8080/tcp                                                                               cw-swiftcw05svt-48203c30-f4b9-11e9-83a2-f72517aa6715
54249fcde1dc        appsody/swift:0.1                                           "/appsody/appsody-co…"   About an hour ago   Up About an hour    0.0.0.0:32824->8080/tcp                                                                               cw-appsodyswiftcw05svt-60f586c0-f42d-11e9-83a2-f72517aa6715
f0769b5a1ec2        appsody/nodejs-loopback:0.1                                 "/appsody/appsody-co…"   About an hour ago   Up About an hour    0.0.0.0:32823->3000/tcp, 0.0.0.0:32822->9229/tcp                                                      cw-appsodynodejslbcw05svt-adfb4f10-f42b-11e9-83a2-f72517aa6715
b209a9a60800        appsody/python-flask:0.1                                    "/appsody/appsody-co…"   About an hour ago   Up About an hour    0.0.0.0:32821->5678/tcp, 0.0.0.0:32820->8080/tcp                                                      cw-appsodypythoncw05svt-a937de20-f42c-11e9-83a2-f72517aa6715
14b7cfba05b2        appsody/nodejs-express:0.2                                  "/appsody/appsody-co…"   About an hour ago   Up About an hour    0.0.0.0:32819->3000/tcp, 0.0.0.0:32818->9229/tcp                                                      cw-appsodynodejsscacw05svt-1b15e970-f42c-11e9-83a2-f72517aa6715
f2c70ec58776        appsody/nodejs-express:0.2                                  "/appsody/appsody-co…"   About an hour ago   Up About an hour    0.0.0.0:32817->3000/tcp, 0.0.0.0:32816->9229/tcp                                                      cw-appsodynodejssimpcw05svt-313b9ec0-f42c-11e9-83a2-f72517aa6715
f8ace395882c        appsody/nodejs:0.2                                          "/appsody/appsody-co…"   About an hour ago   Up About an hour    0.0.0.0:32815->3000/tcp, 0.0.0.0:32814->9229/tcp                                                      cw-appsodynodejsdefcw05svt-7180b6f0-f42c-11e9-83a2-f72517aa6715
ae69e1c5024c        appsody/java-microprofile:0.2                               "/appsody/appsody-co…"   About an hour ago   Up About an hour    0.0.0.0:32813->7777/tcp, 0.0.0.0:32812->9080/tcp, 0.0.0.0:32811->9443/tcp                             cw-appsodyempcw05svt-81bf9be0-f42b-11e9-83a2-f72517aa6715
f3c4363b9781        appsody/java-spring-boot2:0.3                               "/appsody/appsody-co…"   About an hour ago   Up About an hour    0.0.0.0:32810->5005/tcp, 0.0.0.0:32809->8080/tcp, 0.0.0.0:32807->8443/tcp, 0.0.0.0:32805->35729/tcp   cw-appsodyspringdefcw05svt-ec7e2860-f42c-11e9-83a2-f72517aa6715
6678d1964ab6        appsody/java-spring-boot2:0.3                               "/appsody/appsody-co…"   About an hour ago   Up About an hour    0.0.0.0:32808->5005/tcp, 0.0.0.0:32806->8080/tcp, 0.0.0.0:32804->8443/tcp, 0.0.0.0:32803->35729/tcp   cw-appsodyspringkotlincw05svt-0ff28b10-f42d-11e9-83a2-f72517aa6715
3f9f74a1ae73        cw-olcw05svt-a9ed07e0-f42d-11e9-83a2-f72517aa6715           "/opt/ol/helpers/run…"   2 hours ago         Up 2 hours          0.0.0.0:32802->9080/tcp, 0.0.0.0:32801->9443/tcp                                                      cw-olcw05svt-a9ed07e0-f42d-11e9-83a2-f72517aa6715
0693a90211b0        cw-springbootcw05svt-c88780e0-f42d-11e9-83a2-f72517aa6715   "/scripts/new_entryp…"   2 hours ago         Up 2 hours          127.0.0.1:32772->7777/tcp, 0.0.0.0:32800->8080/tcp                                                    cw-springbootcw05svt-c88780e0-f42d-11e9-83a2-f72517aa6715
3b4d26f94652        cw-nodejscw05svt-9ac331e0-f42d-11e9-83a2-f72517aa6715       "docker-entrypoint.s…"   2 hours ago         Up 2 hours          0.0.0.0:32799->3000/tcp, 127.0.0.1:32771->9229/tcp                                                    cw-nodejscw05svt-9ac331e0-f42d-11e9-83a2-f72517aa6715
3e3e97799c43        cw-gocw05svt-7b907080-f42d-11e9-83a2-f72517aa6715           "/app/main"              2 hours ago         Up 2 hours          0.0.0.0:32798->8000/tcp                                                                               cw-gocw05svt-7b907080-f42d-11e9-83a2-f72517aa6715
88fd2c985a93        codewind-pfe-amd64:0.5.0                                    "sh -c ' /file-watch…"   2 hours ago         Up 2 hours          127.0.0.1:10000->9090/tcp                                                                             codewind-pfe
f509ecebabcc        codewind-performance-amd64:0.5.0                            "docker-entrypoint.s…"   2 hours ago         Up 2 hours          127.0.0.1:9095->9095/tcp                                                                              codewind-performance
```

**Comment by sujeilyfonseca** [comment] 2019-10-22 19:49
**Codewind version:** codewind-0.5.0-201910161808.vsix
**OS:** VM with Windows 10

**IDE extension version:** 0.5.0
**IDE version:** 1.39.2

I see a similar behavior on my machine. My Appsody Spring Boot Default template is stuck on "Stopped" state, and before the Appsody Spring Boot Kotlin was stuck in "Starting" state:

<img width="1463" alt="Screen Shot 2019-10-22 at 3 47 29 PM" src="https://user-images.githubusercontent.com/49531960/67325510-4b531380-f4e3-11e9-868d-d20adc650541.png">

```
[ERRO: 14:46:58.879 Project.js.update():107]: No ports were provided for an app that is supposed to be started
```

```
 C:\Users\Administrator> docker ps
CONTAINER ID        IMAGE                                                            COMMAND                  CREATED              STATUS              PORTS                                                                                                 NAMES
3d8c4779bb1b        appsody/java-spring-boot2:0.3                                    "/appsody/appsody-co…"   About a minute ago   Up About a minute   0.0.0.0:32802->5005/tcp, 0.0.0.0:32801->8080/tcp, 0.0.0.0:32800->8443/tcp, 0.0.0.0:32799->35729/tcp   cw-cwappsodyspringbootkotlin-82cf0c90-d0eb-11e9-8997-0364b70249df
e7c59d6ce4a2        cw-cwstandardmicroprofile-e9382b80-f1c3-11e9-8c08-7dc7eba32b73   "/home/default/artif…"   52 minutes ago       Up 52 minutes       127.0.0.1:32770->7777/tcp, 0.0.0.0:32798->9080/tcp, 0.0.0.0:32797->9443/tcp                           cw-cwstandardmicroprofile-e9382b80-f1c3-11e9-8c08-7dc7eba32b73
fa5d2fd8ee11        cw-cwstandardswift-c6f94a40-da17-11e9-8abf-413d753d4987          "sh -c 'cd /swift-pr…"   55 minutes ago       Up 55 minutes       0.0.0.0:32796->8080/tcp                                                                               cw-cwstandardswift-c6f94a40-da17-11e9-8abf-413d753d4987
45e35dc385f9        appsody/nodejs-loopback:0.1                                      "/appsody/appsody-co…"   56 minutes ago       Up 56 minutes       0.0.0.0:32795->3000/tcp, 0.0.0.0:32794->9229/tcp                                                      cw-cwappsodyloopback4-c8172760-db09-11e9-9c4b-697704cf907a
d38b4cd44799        appsody/nodejs-express:0.2                                       "/appsody/appsody-co…"   56 minutes ago       Up 56 minutes       0.0.0.0:32793->3000/tcp, 0.0.0.0:32792->9229/tcp                                                      cw-cwappsodynodeexpresssimple-a44abcd0-db0d-11e9-9c4b-697704cf907a
527651d6dbb1        appsody/nodejs-express:0.2                                       "/appsody/appsody-co…"   56 minutes ago       Up 56 minutes       0.0.0.0:32791->3000/tcp, 0.0.0.0:32790->9229/tcp                                                      cw-cwappsodynodeexpressskaffold-9bbaf3e0-db09-11e9-9c4b-697704cf907a
8556769cd920        appsody/python-flask:0.1                                         "/appsody/appsody-co…"   56 minutes ago       Up 56 minutes       0.0.0.0:32789->5678/tcp, 0.0.0.0:32788->8080/tcp                                                      cw-cwappsodypythonflask-302b6780-f11c-11e9-ab8f-51bc8b82921b
c9ccd3874e3f        appsody/java-spring-boot2:0.3                                    "/appsody/appsody-co…"   57 minutes ago       Up 57 minutes       0.0.0.0:32785->5005/tcp, 0.0.0.0:32783->8080/tcp, 0.0.0.0:32781->8443/tcp, 0.0.0.0:32780->35729/tcp   cw-cwappsodyspringbootdefault-184cbc00-d0b9-11e9-b07c-6b68e46b9433
df2510956828        appsody/java-microprofile:0.2                                    "/appsody/appsody-co…"   57 minutes ago       Up 57 minutes       0.0.0.0:32779->7777/tcp, 0.0.0.0:32778->9080/tcp, 0.0.0.0:32777->9443/tcp                             cw-cwappsodyeclipsemicroprofile-4b1fd6f0-dba7-11e9-9c4b-697704cf907a
496a73d05c7f        cw-cwstandardgo-e52ba810-da16-11e9-9417-ed109350210e             "/app/main"              59 minutes ago       Up 59 minutes       0.0.0.0:32776->8000/tcp                                                                               cw-cwstandardgo-e52ba810-da16-11e9-9417-ed109350210e
340c1595f8e8        cw-cwstandardnodeexpress-c63ec950-da16-11e9-9417-ed109350210e    "docker-entrypoint.s…"   About an hour ago    Up About an hour    0.0.0.0:32775->3000/tcp, 127.0.0.1:32769->9229/tcp                                                    cw-cwstandardnodeexpress-c63ec950-da16-11e9-9417-ed109350210e
7df0165ebd99        cw-cwstandardlagom-09ad3500-da17-11e9-9417-ed109350210e          "java -cp /deploymen…"   About an hour ago    Up About an hour    0.0.0.0:32774->8778/tcp, 0.0.0.0:32773->9000/tcp, 0.0.0.0:32772->9779/tcp                             cw-cwstandardlagom-09ad3500-da17-11e9-9417-ed109350210e
eb81d1d67f26        cw-cwstandardpython-58d75200-da17-11e9-9417-ed109350210e         "python app.py"          About an hour ago    Up About an hour    0.0.0.0:32771->5000/tcp                                                                               cw-cwstandardpython-58d75200-da17-11e9-9417-ed109350210e
6e3be8953fb8        cw-cwstandardopenliberty-23636410-da17-11e9-9417-ed109350210e    "/opt/ol/helpers/run…"   About an hour ago    Up About an hour    0.0.0.0:32770->9080/tcp, 0.0.0.0:32769->9443/tcp                                                      cw-cwstandardopenliberty-23636410-da17-11e9-9417-ed109350210e
db0ec681e432        cw-cwstandardspringboot-28743e50-dbae-11e9-91ae-bbc543524280     "/scripts/new_entryp…"   About an hour ago    Up About an hour    127.0.0.1:32768->7777/tcp, 0.0.0.0:32768->8080/tcp                                                    cw-cwstandardspringboot-28743e50-dbae-11e9-91ae-bbc543524280
03ba78368f15        codewind-pfe-amd64:0.5.0                                         "sh -c ' /file-watch…"   About an hour ago    Up About an hour    127.0.0.1:10000->9090/tcp                                                                             codewind-pfe
05f4a3adb394        codewind-performance-amd64:0.5.0                                 "docker-entrypoint.s…"   About an hour ago    Up About an hour    127.0.0.1:9095->9095/tcp                                                                              codewind-performance
```

[codewind.log](https://github.com/eclipse/codewind/files/3758106/codewind.log)
[codewind-pfe.txt](https://github.com/eclipse/codewind/files/3758108/codewind-pfe.txt)
[appsody.log](https://github.com/eclipse/codewind/files/3758111/appsody.log)
[filewatcherd-1.log](https://github.com/eclipse/codewind/files/3758109/filewatcherd-1.log)

**Comment by makandre** [comment] 2019-10-22 20:11
@jagraj @sujeilyfonseca Looking at your appsody logs, it appears you both hit a problem where the `appsody run` command for the spring project error out:

```
[Container] [FATAL] Non-resolvable parent POM dev.appsody:spring-boot2-stack:[0.3, 0.4) for dev.appsody:application:0.0.1-SNAPSHOT: No versions matched the requested parent version range '[0.3, 0.4)' and 'parent.relativePath' points at no local POM @ line 6, column 11
[Container]  @ 
[Container] [[1;31mERROR[m] The build could not read 1 project -> [1m[Help 1][m
[Container] [[1;31mERROR[m]   
[Container] [[1;31mERROR[m]   The project dev.appsody:application:0.0.1-SNAPSHOT (/project/user-app/pom.xml) has 1 error
[Container] [[1;31mERROR[m]     Non-resolvable parent POM dev.appsody:spring-boot2-stack:[0.3, 0.4) for dev.appsody:application:0.0.1-SNAPSHOT: No versions matched the requested parent version range '[0.3, 0.4)' and 'parent.relativePath' points at no local POM @ line 6, column 11 -> [1m[Help 2][m
[Container] [[1;31mERROR[m] 
[Container] [[1;31mERROR[m] To see the full stack trace of the errors, re-run Maven with the [1m-e[m switch.
[Container] [[1;31mERROR[m] Re-run Maven using the [1m-X[m switch to enable full debug logging.
[Container] [[1;31mERROR[m] 
[Container] [[1;31mERROR[m] For more information about the errors and possible solutions, please read the following articles:
[Container] [[1;31mERROR[m] [1m[Help 1][m http://cwiki.apache.org/confluence/display/MAVEN/ProjectBuildingException
[Container] [[1;31mERROR[m] [1m[Help 2][m http://cwiki.apache.org/confluence/display/MAVEN/UnresolvableModelException
[Container] Wait received error on APPSODY_RUN/DEBUG/TEST exit status 1
```

So this is an appsody stack issue.  Appsody team did introduced some range tolerance to their framework but I'm told there are some some edge changes where a version change happens that would require some user intervention.  I suspect this is one of those cases.

**Comment by naveenkaratekid** [comment] 2019-10-22 20:59
**Codewind version**: 0.5.0
**OS**: VM with Windows 10

**IDE extension version**: 0.5.0
**IDE version**: 1.39.2 

I am also noticing issues with Appsody Springboot default and Kotlin templates, in addition to the micro profile templates. Attached are the logs files for Codewind PFE, and the logs for the templates mentioned and a screenshot of VSCode

[appsody-SP-kotlin.log](https://github.com/eclipse/codewind/files/3758540/appsody-SP-kotlin.log)
[appsody-SP-def.log](https://github.com/eclipse/codewind/files/3758541/appsody-SP-def.log)
[appsody-MP.log](https://github.com/eclipse/codewind/files/3758542/appsody-MP.log)
[codewind PFE logs.txt](https://github.com/eclipse/codewind/files/3758543/codewind.PFE.logs.txt)
![Screen Shot 2019-10-22 at 4 51 30 PM](https://user-images.githubusercontent.com/19738071/67332465-0af89300-f4ed-11e9-8edc-3ba1ccb57001.png)

**Comment by malincoln** [comment] 2019-10-22 21:22
Adding info from Andrew on workaround:
ANDREW MAK:deathstar:  41 minutes ago
It’s easily recoverable by manually building the project tho, and typically there’s no problem when things are not as busy as during a startup when 10+ projects are getting brought up at the same time

**Comment by makandre** [comment] 2019-10-23 01:37
@naveenkaratekid Did you delete the old `<codewind-workspace>/.extension/codewind-appsody-extension`, so that a new version will be installed by PFE when it restarts?

**Comment by naveenkaratekid** [comment] 2019-10-23 12:10
@makandre Yes, I deleted the folder after uninstalling Codewind. Maybe I missed a step. I'll try again, and let you know.

**Comment by micgibso** [comment] 2019-10-23 13:01
Documented on https://github.com/eclipse/codewind-docs/pull/188/files

**Comment by hanczaryk** [comment] 2019-10-28 13:35
FYI, Jag asked that I add a comment with my experience where my spring-boot2 application get stuck reporting 'Stopped' Application Status when I attempted to 'Enable Project'.  In actuality, my app is functional and can be accessed at http://127.0.0.1:32831/sbgolf

![image](https://user-images.githubusercontent.com/30906029/67682635-3274b300-f966-11e9-9ee9-0a226d03b78b.png)

**Comment by islamm-ibm** [comment] 2019-11-04 16:27
I am facing similar issue, the application status in Codewind explorer is "stopped", though I can access application, the associated services seems to be up/running.
Attached Appsody.log & Turbine.log (zipped).

[Turbine.log.zip](https://github.com/eclipse/codewind/files/3804957/Turbine.log.zip)
[appsody.log.zip](https://github.com/eclipse/codewind/files/3804960/appsody.log.zip)

**Comment by jagraj** [comment] 2019-12-02 16:17
I restarted my codewind and couple of projects are stuck at "Starting" state and status not turned into "Running" state.  To me, Eclipse microprofile, nodejs default app should be running and other apps does not have web server running and they should be in "Stopped" state as we do not support status for these apps.

Logs
[.log](https://github.com/eclipse/codewind/files/3912123/default.log)
[filewatcherd-1.log](https://github.com/eclipse/codewind/files/3912124/filewatcherd-1.log)
[pfe-12022019.txt](https://github.com/eclipse/codewind/files/3912129/pfe-12022019.txt)
[appsodynodejsdevcw06svt.txt](https://github.com/eclipse/codewind/files/3912145/appsodynodejsdevcw06svt.txt)


![image](https://user-images.githubusercontent.com/713849/69974574-89385400-14f3-11ea-9137-0d006f21e781.png)

Here are the logs for these apps.

**Comment by makandre** [comment] 2019-12-02 16:25
The https://github.com/eclipse/codewind/files/3912145/appsodynodejsdevcw06svt.txt linked above is from the `nodejs` stack (not express) which does not have a running server.  So remaining in `starting` state is correct (note: the change to `stopped` state after a timeout was reverted, hence it remains in `starting` state)

**Comment by jagraj** [comment] 2019-12-02 16:36
Here is the appsody log for Microprofile log. 
[appsodyempcw06svt.txt](https://github.com/eclipse/codewind/files/3912235/appsodyempcw06svt.txt)

**Comment by makandre** [comment] 2019-12-02 16:54
In PFE log, these messages can be seen for appsodyempcw06svt towards the end of the log:

```
[32m[02/12/19 15:43:50 appsodyempcw06svt] [INFO][39m pingInTransitApplications: Application state error message: could not retrieve the port for the project
...
[32m[02/12/19 15:44:45 appsodyempcw06svt] [INFO][39m Found container information: {"containerId":"","ip":"","serviceName":"","exposedPort":"","internalPort":"","exposedDebugPort":"","internalDebugPort":"","containerPorts":[],"hostPorts":[]}
```

Codewind wasn't able to get any information on the container, which leads me to suspect the container was still not up when Codewind was checking.  This at least explains why it is still in `starting` state.

As mentioned before, normally Codewind should continue to periodically ping the app until it is up.  If this is not happening, we do have #812 to look into why.

Finally, after things have settled down and most projects are more or less in running state, does requesting a manual build of this project get it to running state eventually?

**Comment by jagraj** [comment] 2019-12-02 18:24
Yes, After manual rebuild project status turned into "Running" state. Yes, I agree we need polling to query the status of the project and set appropriate status for the applications.

**Comment by micgibso** [comment] 2019-12-16 09:29
Documented here in the Troubleshooting: https://www.eclipse.org/codewind/troubleshooting.html#projects-stuck-in-starting-or-stopped-state

**Comment by sghung** [comment] 2019-12-16 15:56
@jagraj @micgibso I believe Jag was working with project types that have a proper server, so it wouldn't fall into the troubleshooting doc's restrictions on serverless appsody apps.

**Comment by sishida** [comment] 2020-01-07 16:56
@sghung Hi, Steven, Do you happen to know if this issue good to close? Thanks!

**Comment by sghung** [comment] 2020-01-09 18:46
Closing as this will be covered in two issues:
- https://github.com/eclipse/codewind/issues/812
- https://github.com/eclipse/codewind/issues/1269

**Closed by sghung** 2020-01-09 18:46 UTC
Labels: area/appsody, area/docs, kind/bug, priority/hot
