### ISSUE TITLE
Add an ignoredPaths API to PFE and remove hard coded list from CLI

### ISSUE THREAD

**Issue by james-wallis** [eclipse/codewind#835] opened 2019-10-24 09:36 UTC
**Codewind version:** Master

**Description of the enhancement:**

Issue https://github.com/eclipse/codewind/issues/750 and PR https://github.com/eclipse/codewind-installer/pull/162 added functionality to ignore large unneeded folders such as `node_modules` to improve the time it took to add the users files into PFE.

The solution includes a hardcoded list and work should be completed to make it dynamic and on a per project type basis. 

**Proposed solution:** 

A potential solution is to create an ignoredPaths API in PFE which returns a different list given a different project type.

**Comment by elsony** [comment] 2019-10-29 18:11
Add hot to this item since using a hardcoded list of ignorePaths in the installer causes regression in function that we are ignoring the settings in the .cw-settings file.

**Comment by yangcao77** [comment] 2019-10-29 18:19
Turbine has ignoredPaths for each project, it can be get from`projectInfo.ignoredPaths`.
Perhaps an additional Turbine GET API need to be created to return the `projectInfo.ignoredPaths` to portal.

**Comment by james-wallis** [comment] 2019-10-30 14:19
If we go down the route of having an ignoredPaths API in Turbine I think it'll create extra overhead each time a users project is changed as the CLI will need to make an API request to see which files it should ignore. Potentially `CLI -> Portal -> Turbine -> Portal -> CLI`. 

I don't have a better solution however, but agree it should be dynamic and Turbine and Portal should be using the same `ignoredPaths` + a users defined ones in `.cw-settings`

**Comment by yangcao77** [comment] 2019-10-30 15:17
However, since Turbine is now monitoring & read the change of `.cw-settings` file. Turbine has already kept the record of the `ignoredPaths`. 
Not sure if we want portal to also read the file, or if both portal & Turbine are going to read the file.

**Comment by jcockbain96** [comment] 2019-10-31 10:02
@tobespc, picking this up. Can I be assigned?

**Comment by jcockbain96** [comment] 2019-10-31 16:53
@yangcao77 how does turbine determine its list of `ignoredPaths`? Is it a set of defaults for each `projectType` + anything user defined in `.cw-settings`? If we stay with the `ignoredPaths` list being stored there I'd think we would need a Turbine API to call. 

Otherwise we'd have two copies of the same list being stored (the current Turbine one, plus another in PFE for this new API to expose).

The alternative in my opinion, is to have the `ignoredPaths` be driven entirely by `.cw-settings`. So, all of the `ignoredPaths` are copied into `.cw-settings` on binding a project (if a `.cw-settings` doesn't exist already). Then this is the list the CLI reads when sync is called, and also what Turbine works off of. So totally user configurable, like a `.gitignore`. This would then mean that the `ignorePaths` list is only in one location.

**Comment by yangcao77** [comment] 2019-10-31 17:34
@jcockbain96 `ignoredPaths` is the user defined value in `.cw-settings`. if it's not defined in `.cw-settings`, Turbine would use the default one for that specific projectType. 
I agree that from user's perspective, exposing the default/current `ignoredPath` or other settings in `.cw-settings` is better than our current design. (i.e. `.cw-settings` file with empty values.) so user would have an idea on the current setting, and make change to it if they want to.  However, I remember we used to do that in Microclimate, but at some point, pfe is designed to only have read right, but no write right to the `.cw-settings` file.

**Comment by jcockbain96** [comment] 2019-10-31 17:53
Thanks @yangcao77, as I understand it using the CLI we can now write to a users `cw-settings`.  I remember that being the problem too. I can confirm tomorrow.

So does that mean it would work from a Turbine perspective if we use the CLI to add the default `ignoredPaths` for that type on a bind? It would then be up to the user to manage that list. The Portal API could return the default list for each type.

**Comment by yangcao77** [comment] 2019-10-31 18:34
@jcockbain96 Yes. Upon creation, Turbine reads the `.cw-setings` file to look for the value. If it's empty, Turbine is going to use the default on set in each project type's handler. 
So I would say set the default `ignoredPaths` in `.cw-settings` before portal sends creation request to Turbine. Otherwise, it would be considered as a "settingsChanged" event, and would rely on filewatcher & cwctl to report the change, it would have sync issue then. 

And for the default `ignoredPaths`, CLI/portal should use the same value Turbine is using: 
Liberty: https://github.com/eclipse/codewind/blob/5b64bbecffb096ff82ba3216802504bc652628ff/src/pfe/file-watcher/server/src/projects/libertyProject.ts#L88
Spring: https://github.com/eclipse/codewind/blob/5b64bbecffb096ff82ba3216802504bc652628ff/src/pfe/file-watcher/server/src/projects/springProject.ts#L69
Node: https://github.com/eclipse/codewind/blob/5b64bbecffb096ff82ba3216802504bc652628ff/src/pfe/file-watcher/server/src/projects/nodejsProject.ts#L61
Swift: https://github.com/eclipse/codewind/blob/5b64bbecffb096ff82ba3216802504bc652628ff/src/pfe/file-watcher/server/src/projects/swiftProject.ts#L59
Docker: https://github.com/eclipse/codewind/blob/5b64bbecffb096ff82ba3216802504bc652628ff/src/pfe/file-watcher/server/src/projects/DockerProject.ts#L76
Appsody: https://github.com/eclipse/codewind/blob/5b64bbecffb096ff82ba3216802504bc652628ff/src/pfe/file-watcher/server/src/projects/ShellExtensionProject.ts#L88

**Comment by elsony** [comment] 2019-11-11 21:59
@yangcao77 Toby mentioned on one of the call this morning that this problem has been fixed.  Can you verify this?

**Comment by jcockbain96** [comment] 2019-11-12 08:53
The change isn't into `cwctl` to set `.cw-settings` yet, https://github.com/eclipse/codewind-installer/pull/191. 

Once that is merged that will be ready to verify.

**Closed** 2019-11-13 09:49 UTC
Labels: area/portal, kind/bug, kind/enhancement, priority/hot, remote
