### ISSUE TITLE
SVT:Exceptions when starting open liberty sample

### ISSUE THREAD

**Issue by jagraj** [eclipse/codewind#342] opened 2019-08-30 12:58 UTC
**Codewind version:** 0.3
**OS:**  Windows

**Che version:**
**IDE extension version:**  eclipse-plugin 0.3
**IDE version:** Eclipse 2019-06
**Kubernetes cluster:**

**Description:**
With the latest open liberty docker image, we are getting exceptions during application start.
I had cached liberty image with previous version, I deleted old image and with the latest open liberty image that I am getting this exception.

```
[AUDIT   ] CWWKT0016I: Web application available (default_host): http://882b84d7d800:9080/health/
[AUDIT   ] CWWKT0016I: Web application available (default_host): http://882b84d7d800:9080/openapi/
[ERROR   ] SRVE0777E: Exception thrown by application class 'com.ibm.ws.container.service.metadata.internal.MetaDataServiceImpl.getMetaData:268'
java.lang.IllegalStateException: WEB#io.openliberty.sample.getting.started#io.openliberty.sample.getting.started.war
	at com.ibm.ws.container.service.metadata.internal.MetaDataServiceImpl.getMetaData(MetaDataServiceImpl.java:268)
	at [internal classes]

[ERROR   ] SRVE0315E: An exception occurred: java.lang.Throwable: java.lang.IllegalStateException: WEB#io.openliberty.sample.getting.started#io.openliberty.sample.getting.started.war
	at com.ibm.ws.webcontainer.webapp.WebApp.handleRequest(WebApp.java:5051)
	at [internal classes]
Caused by: java.lang.IllegalStateException: WEB#io.openliberty.sample.getting.started#io.openliberty.sample.getting.started.war
	at com.ibm.ws.container.service.metadata.internal.MetaDataServiceImpl.getMetaData(MetaDataServiceImpl.java:268)
	... 1 more

[ERROR   ] SRVE0777E: Exception thrown by application class 'com.ibm.ws.container.service.metadata.internal.MetaDataServiceImpl.getMetaData:268'
java.lang.IllegalStateException: WEB#io.openliberty.sample.getting.started#io.openliberty.sample.getting.started.war
	at com.ibm.ws.container.service.metadata.internal.MetaDataServiceImpl.getMetaData(MetaDataServiceImpl.java:268)
	at [internal classes]
```

**Steps to reproduce:**

1. Install codewind 0.3 from eclipse plugin.
2. Create open liberty project from the template.
3. During app start in latest open liberty image, I get exception posted above.

**Workaround:**

**Comment by sujeilyfonseca** [comment] 2019-10-17 16:54
**Codewind version:** [codewind-0.5.0-201910161808.vsix](https://download.eclipse.org/codewind/codewind-vscode/0.5.0/latest/)
**OS:** VM with Windows 10 

**IDE extension version:** 0.5.0
**IDE version:** 1.39.0

I still see this problem with Codewind 0.5.0, but only on Windows 10. I can't reproduce this in MacOS Mojave.

```
ROR   ] SRVE0777E: Exception thrown by application class 'com.ibm.ws.container.service.metadata.internal.MetaDataServiceImpl.getMetaData:268'
java.lang.IllegalStateException: WEB#io.openliberty.sample.getting.started#io.openliberty.sample.getting.started.war
	at com.ibm.ws.container.service.metadata.internal.MetaDataServiceImpl.getMetaData(MetaDataServiceImpl.java:268)
	at [internal classes]

[ERROR   ] SRVE0777E: Exception thrown by application class 'com.ibm.ws.container.service.metadata.internal.MetaDataServiceImpl.getMetaData:268'
java.lang.IllegalStateException: WEB#io.openliberty.sample.getting.started#io.openliberty.sample.getting.started.war
	at com.ibm.ws.container.service.metadata.internal.MetaDataServiceImpl.getMetaData(MetaDataServiceImpl.java:268)
	at [internal classes]

[ERROR   ] SRVE0777E: Exception thrown by application class 'com.ibm.ws.container.service.metadata.internal.MetaDataServiceImpl.getMetaData:268'
java.lang.IllegalStateException: WEB#io.openliberty.sample.getting.started#io.openliberty.sample.getting.started.war
	at com.ibm.ws.container.service.metadata.internal.MetaDataServiceImpl.getMetaData(MetaDataServiceImpl.java:268)
	at [internal classes]
```

**Comment by elsony** [comment] 2019-11-13 22:04
The error looks like to be coming from the application itself instead of a problem on Turbine build.  Transferring to portal since portal owns the templates.

**Comment by rwalle61** [comment] 2020-01-07 11:01
I have been able to start open liberty samples recently (on MacOS, Codewind 0.7.0+), and I believe @mattcolegate has been able to start them on Windows (10?). So maybe we can close this?

**Comment by hhellyer** [comment] 2020-01-07 11:09
This was an error in the logs when the health endpoint was accessed.
There is a closed Open Liberty bug from August (around when this issue was originally raised) here: https://github.com/OpenLiberty/open-liberty/issues/8573 which references the exact error string and a fix here: https://github.com/OpenLiberty/open-liberty/pull/8631

I have started an Open Liberty app locally and access /health - I do not see this error now. I believe we can close this now.

**Closed** 2020-01-07 11:10 UTC
Labels: area/portal, kind/bug
