### ISSUE TITLE
deleting project in codewind

### ISSUE THREAD

**Issue by AndyRWatson** [eclipse/codewind#1282] opened 2019-11-26 21:03 UTC
**Codewind version:** 0.6.0
**OS:**. 10.15

**Che version:**
**IDE extension version:**. 0.6
**IDE version:** VSCodew
**Kubernetes cluster:**

**Description of the enhancement:**
When deleting a project in codewind I am asked a few questions to complete the process,  one of which is "Would you like to also delete the project directory at /Users/watsona/codewind-workspace/mye ?" and offered the options "Cancel/Remove directory".   From a usability perspective I would have expected "Yes/No" as a better option,  especially as if I hit "Cancel" I'd have assumed that meant cancel the whole delete process,  rather than completing the process but leaving the files.    Maybe a better answer to the question would be leave files/delete files.

Either way I feel the flow here and use of cancel may not be the optimum wording from a usability perspective.

**Proposed solution:** 

Change wording to yes/no/cancel or leave/delete/cancel

**Comment by rajivnathan** [comment] 2019-11-26 21:37
Dupe of https://github.com/eclipse/codewind/issues/778. @tetchel is this still a limitation?

**Comment by tetchel** [comment] 2019-11-26 21:38
Yes it's not going to change anytime soon

**Closed** 2019-12-03 14:09 UTC
Labels: area/vscode-ide, kind/enhancement
