### ISSUE TITLE
Plugin asks user where to generate files to

### ISSUE THREAD

**Issue by NottyCode** [eclipse/codewind#547] opened 2019-09-24 15:54 UTC
I have a maven project in vs code and the tool asks me where to write the generated Java source files. Given this is a maven project the tool should know to write the generated code into the `src/main/java` folder. Perhaps `src/test/java` might be a contender, but even then the question should be should this go into main or test, not which folder under src should it go into.

**Comment by keithchong** [comment] 2019-09-25 18:22
@sghung , please resolve this as a dup of #79

Maven project customizations/setup.

**Comment by sghung** [comment] 2019-09-25 19:28
Closing based on Keith's comment regarding this being a dupe of #79

**Closed by sghung** 2019-09-25 19:28 UTC
Labels: area/openapi
