### ISSUE TITLE
(metrics) SVT:Add support for Performance tests on Appsody Liberty stacks

### ISSUE THREAD

**Issue by jagraj** [eclipse/codewind#1079] opened 2019-11-11 14:37 UTC
**Codewind version:** 0.6
**OS:** WIndows

**Che version:**
**IDE extension version:** 0.6 
**IDE version:** Eclipse 2019-09
**Kubernetes cluster:**

**Description:**
Performance tests results are no longer available in the history after test is completed running. 

PFE log.

[pfe.txt](https://github.com/eclipse/codewind/files/3831771/pfe.txt)

Performance log.
[performance.txt](https://github.com/eclipse/codewind/files/3831775/performance.txt)

![image](https://user-images.githubusercontent.com/713849/68594797-522bd100-0466-11ea-9ac7-61e8e6570304.png)

**Steps to reproduce:**
1. Create Appsody eclipse microprofile project. 
2. After successfully running, start couple of performance tests and I do not see tests in the history any more. 

**Workaround:**

**Comment by tetchel** [comment] 2019-11-11 17:52
did the performance monitor ever work with appsody? https://github.com/eclipse/codewind/issues/533

**Comment by jagraj** [comment] 2019-11-11 18:13
Yes, this feature is enabled only for supported projects. I cerated Appsody eclipse Microprofile project and the options are available for this project. This is enabled for Java and Nodejs projects.

![Screen Shot 2019-11-11 at 1 11 50 PM](https://user-images.githubusercontent.com/713849/68610047-d8efa680-0484-11ea-8e6b-51deebe58106.png)

**Comment by jagraj** [comment] 2019-11-11 20:21
I also verified against Codewind 0.5 release, load tests from "Performance Dashboard" does not work for appsody microprofile project and we should disable or display this message to the user.

![image](https://user-images.githubusercontent.com/713849/68618206-d8600b80-0496-11ea-8b10-c6d282f418a8.png)

**Comment by tobespc** [comment] 2019-11-12 08:59
Will take a look but as this is not a regression I question whether its stop ship

**Comment by jagraj** [comment] 2019-11-13 13:28
@tobespc 
We can move this to hot, Java is popular stack and Kabanero teams use this stack widely and it will be nice if we can make this to work or disable options and display the message as commented here. (https://github.com/eclipse/codewind/issues/1079#issuecomment-552599256).

**Comment by jopit** [comment] 2019-11-13 14:35
Based on a conversation with @tobespc, the IDEs need to disable the menu items for the performance dashboard as well when the flag to disable app metrics is set.

**Comment by tetchel** [comment] 2019-11-13 14:51
We already do that

**Comment by eharris369** [comment] 2019-11-13 14:53
I checked the Eclipse code as well and it is only showing the perf monitor action if metrics are available.

**Comment by tetchel** [comment] 2019-11-13 15:00
background: https://github.com/eclipse/codewind/issues/258

My understanding is that portal always reports Appsody projects support appmetrics, because they can't inspect the package/pom/etc to determine if it actually does. So the IDEs ping the app monitor endpoint to see if it responds, and if it does, it opens it. If it doesn't, you see the message in https://github.com/eclipse/codewind/issues/1079#issuecomment-552553177

Investigating why jag's microprofile project didn't work now...

**Comment by tetchel** [comment] 2019-11-13 15:35
Nothing is wrong from the IDE side

- metrics/status reports metrics are installed, which is true
- <app url>/javametrics-dash can be opened, and so can the performance dashboard
but indeed, when I run load tests in the perf dashboard, I don't see any results

**Comment by jopit** [comment] 2019-11-13 15:37
Based on @tetchel  investigation, I'm transferring this bug back to portal

**Comment by tobespc** [comment] 2019-11-13 15:41
@jopit thanks for the update, will work on it again from portal perspective

**Comment by tobespc** [comment] 2019-11-14 10:12
I'm seeing performance metrics for
Appsody Node.js Express simple
Appsody Node.js skaffold

Appsody Spring - menus are disabled as metrics not supported
Appsody Kotlin - menus are disabled as metrics not supported

**Comment by tobespc** [comment] 2019-11-14 10:54
I currently can't get appsody liberty to build - have raised issue #1121

**Comment by tobespc** [comment] 2019-11-14 14:54
appsody incubator liberty is showing the problem

**Comment by markcor11** [comment] 2019-11-15 12:22
Do any metrics show up if you change the load run settings in the performance dashboard to show only results for /health rather than the project urls ?  

* Edit load run settings -> path = /health

**Comment by markcor11** [comment] 2019-11-15 12:45
Reproduced...   answer to my question above is yes.

**Comment by markcor11** [comment] 2019-11-15 15:56
Looking at a sample Appsody project it uses Open Liberty & OpenJ9.  We don't enable metrics on a Codewind Open Liberty project. There is some commentary in https://github.com/RuntimeTools/javametrics#open-liberty that talks about enabling metrics for open-liberty but I since this is appsody I believe that needs to be applied in the stack itself. @makandre can you comment ?

**Comment by makandre** [comment] 2019-11-15 16:25
Based on the java-microprofile stack's README, it does say javametrics is already built-in:
https://github.com/appsody/stacks/blob/c9694470e082492c54dfd6574622d1e92332a498/incubator/java-microprofile/README.md

But I don't know the specifics of whether the javametrics is enabled by default or not, @neeraj-laad is one of the maintainers of this stack and maybe able to provide some insights.

**Comment by jopit** [comment] 2019-11-18 18:41
@markcor11 @tobespc Is there some way the IDEs can tell that we are in this scenario so that we can display a better message to the user?

**Comment by malincoln** [comment] 2020-01-14 16:08
@tobespc I'm removing 0.7.0 release.  Pls update once you know the target release.  Thanks

**Comment by tobespc** [comment] 2020-04-28 10:25
The problem we have is that inject metrics does not work for appsody projects.  Without this, unless the underlying appsody stack is already using appmetrics or javametrics, its not possible to get performance information.   The work to enable inject metrics for appsody is being tracked here #1361 .  Closing this issue as tracking under 1361

**Closed by tobespc** 2020-04-28 10:25 UTC
Labels: area/portal, kind/bug, kind/enhancement
