### ISSUE TITLE
Provide file:// support in Codewind handling of extensions' templates repo URLs

### ISSUE THREAD

**Issue by lentheivendra** [eclipse/codewind#595] opened 2019-10-01 14:51 UTC
**Description of the enhancement:**
For Codewind extensions that implement the getRepositories() function in templatesProvider.js, it would be useful to return templates repository file:// URLs pointing to local json files in the codewind server that the extensions themselves create/manage. 

**Proposed solution:** 
I have a proposed patch for https://github.com/eclipse/codewind/blob/master/src/pfe/portal/modules/Templates.js (in particular the getTemplatesFromRepo() function) that adds this support. Please review the referenced PR below.

**Comment by tetchel** [comment] 2019-10-01 16:35
Looks like users want this too: https://github.com/eclipse/codewind/issues/540#issuecomment-535425378

**Comment by tetchel** [comment] 2019-10-02 17:42
Let me know when this is finished; currently the VS Code "add template source" wizard will only allow http(s) URLs.

**Comment by lentheivendra** [comment] 2019-10-03 15:04
@tobespc Please review PR #598

**Comment by elsony** [comment] 2019-10-03 21:24
@tetchel PR #598 has been merged.

**Comment by tetchel** [comment] 2019-10-04 01:57
I allowed file:// URLs but I get this error when I POST it to templates/repositories:

`StatusCodeError: 500 - "connect ECONNREFUSED 127.0.0.1:80"`
pfe logs:
```
[04/10/19 01:54:31 /portal/routes/templates.route.js] [ERROR] { Error: connect ECONNREFUSED 127.0.0.1:80
    at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1106:14)
  errno: 'ECONNREFUSED',
  code: 'ECONNREFUSED',
  syscall: 'connect',
  address: '127.0.0.1',
  port: 80 }
[04/10/19 01:54:31 /portal/middleware/errorHandler.js] [ERROR] { error:
   { name: 'Error', message: 'connect ECONNREFUSED 127.0.0.1:80' } }
```

**Comment by lentheivendra** [comment] 2019-10-04 13:24
@tetchel maybe there are code paths in portal that need updating for supporting file://, with my patch the /api/v1/templates API was able to process index.json files provided as file:// URLs.  I'll take a look around.. @tobespc any ideas of where else besides https://github.com/eclipse/codewind/blob/master/src/pfe/portal/modules/Templates.js#L352 updates are needed for this?

**Comment by tetchel** [comment] 2019-10-04 14:10
it's [this call](https://github.com/eclipse/codewind/blob/master/src/pfe/portal/modules/Templates.js#L249) to [this function](https://github.com/eclipse/codewind/blob/master/src/pfe/portal/modules/Templates.js#L454) which still assumes http(s).

**Comment by lentheivendra** [comment] 2019-10-04 18:47
Ok will try similar changes to that function

**Comment by malincoln** [comment] 2020-01-07 15:31
@lentheivendra I see this is in Verify.  If it's ready, pls verify and close.  Thanks

**Comment by tetchel** [comment] 2020-01-07 19:32
Closing as a duplicate of https://github.com/eclipse/codewind/issues/668#issuecomment-571636500

**Closed by tetchel** 2020-01-07 19:32 UTC
Labels: area/portal, kind/enhancement
