### ISSUE TITLE
load test is failing with error (see below)

### ISSUE THREAD

**Issue by tobespc** [eclipse/codewind#2184] opened 2020-02-13 13:47 UTC
```message: projectLogsListChanged
 data: {
  "projectID": "5b41e610-4e5a-11ea-a33d-71f549a0a68a",
  "type": "build",
  "build": [
    {
      "origin": "workspace",
      "files": [
        "/codewind-workspace/.logs/tobeslib-5b41e610-4e5a-11ea-a33d-71f549a0a68a/docker.build.log"
      ]
    },
    {
      "origin": "container",
      "files": [
        "/home/default/logs/maven.build.log"
      ],
      "podName": "cw-tobeslib-5b41e610-4e5a-11ea-a33d-7bf4bcbfdc-gm7f2"
    }
  ]
}
[13/02/20 13:44:48 User.js] [INFO] Running load for project: 5b41e610-4e5a-11ea-a33d-71f549a0a68a config: {"method":"GET","path":"/","requestsPerSecond":"1","concurrency":"1","maxSeconds":"20","url":"http://172.30.94.46:9080/"}
[13/02/20 13:44:49 dockerFunctions.js] [WARN] Unable to exec: project does not exist, has no container or is closed
[13/02/20 13:44:49 /portal/modules/LoadRunner.js] [INFO] beginJavaProfiling: Stopping liberty server
[13/02/20 13:44:49 dockerFunctions.js] [WARN] Unable to exec: project does not exist, has no container or is closed
(node:149) UnhandledPromiseRejectionWarning: Unable to exec: project does not exist, has no container or is closed
(node:149) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 2)
(node:149) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
[13/02/20 13:44:54 /portal/modules/LoadRunner.js] [INFO] httpCheckHealth 200
[13/02/20 13:44:59 /portal/modules/LoadRunner.js] [INFO] httpCheckHealth 200
[13/02/20 13:45:04 /portal/modules/LoadRunner.js] [INFO] httpCheckHealth 200
[13/02/20 13:45:09 /portal/modules/LoadRunner.js] [INFO] httpCheckHealth 200
[13/02/20 13:45:14 /portal/modules/LoadRunner.js] [INFO] httpCheckHealth 200
[13/02/20 13:45:19 /portal/modules/LoadRunner.js] [INFO] httpCheckHealth 200
[13/02/20 13:45:24 /portal/modules/LoadRunner.js] [INFO] httpCheckHealth 200
[13/02/20 13:45:29 /portal/modules/LoadRunner.js] [INFO] httpCheckHealth 200
[13/02/20 13:45:34 /portal/modules/LoadRunner.js] [INFO] httpCheckHealth 200
[13/02/20 13:45:39 /portal/modules/LoadRunner.js] [INFO] httpCheckHealth 200
[13/02/20 13:45:44 /portal/modules/LoadRunner.js] [INFO] httpCheckHealth 200
[13/02/20 13:45:48 /portal/routes/projects/loadtest.route.js] [ERROR] { LoadRunError: Load run already in progress.
For project 5b41e610-4e5a-11ea-a33d-71f549a0a68a
    at User.runLoad (/portal/modules/User.js:159:13)
    at /portal/routes/projects/loadtest.route.js:49:36
    at newFn (/portal/node_modules/express-async-errors/index.js:16:20)
    at Layer.handle [as handle_request] (/portal/node_modules/express/lib/router/layer.js:95:5)
    at next (/portal/node_modules/express/lib/router/route.js:137:13)
    at validationFunction (/portal/middleware/reqValidator.js:28:5)
    at validate (/portal/node_modules/express-openapi-validate/dist/OpenApiValidator.js:100:17)
    at validateReq (/portal/middleware/reqValidator.js:24:3)
    at newFn (/portal/node_modules/express-async-errors/index.js:16:20)
    at Layer.handle [as handle_request] (/portal/node_modules/express/lib/router/layer.js:95:5)
  name: 'LoadRunError',
  code: 'RUN_IN_PROGRESS',
  info:
   { name: 'LoadRunError',
     code: 'RUN_IN_PROGRESS',
     message:
      'Load run already in progress. For project 5b41e610-4e5a-11ea-a33d-71f549a0a68a' } }
[13/02/20 13:45:49 /portal/modules/LoadRunner.js] [INFO] httpCheckHealth 200
[13/02/20 13:45:49 /portal/modules/LoadRunner.js] [INFO] beginJavaProfiling: Starting liberty server
[13/02/20 13:45:49 dockerFunctions.js] [WARN] Unable to exec: project does not exist, has no container or is closed
[13/02/20 13:45:54 /portal/modules/LoadRunner.js] [INFO] httpCheckHealth 200
[13/02/20 13:45:54 /portal/modules/LoadRunner.js] [INFO] LibertyServer has responded to /health
[13/02/20 13:45:54 dockerFunctions.js] [WARN] Unable to exec: project does not exist, has no container or is closed
[13/02/20 13:45:54 /portal/modules/LoadRunner.js] [INFO] createCollection: 5b41e610-4e5a-11ea-a33d-71f549a0a68a, 172.30.94.46, 9080, javametrics
[13/02/20 13:45:54 /portal/modules/LoadRunner.js] [INFO] Load run on project 5b41e610-4e5a-11ea-a33d-71f549a0a68a started
(node:149) UnhandledPromiseRejectionWarning: Error: connect ECONNREFUSED 127.0.0.1:9090
    at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1106:14)
(node:149) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 4)
[13/02/20 13:46:14 /portal/modules/LoadRunner.js] [INFO] Load run on project 5b41e610-4e5a-11ea-a33d-71f549a0a68a completed
[13/02/20 13:46:14 /portal/modules/LoadRunner.js] [INFO] recordCollection: Metrics collection deleted
```

**Comment by tobespc** [comment] 2020-02-13 13:49
load test then completes, on a rerun complains load test is still running and gives 
```[13/02/20 13:48:56 /portal/routes/projects/loadtest.route.js] [ERROR] { LoadRunError: Load run already in progress.
For project 5b41e610-4e5a-11ea-a33d-71f549a0a68a
    at User.runLoad (/portal/modules/User.js:159:13)
    at /portal/routes/projects/loadtest.route.js:49:36
    at newFn (/portal/node_modules/express-async-errors/index.js:16:20)
    at Layer.handle [as handle_request] (/portal/node_modules/express/lib/router/layer.js:95:5)
    at next (/portal/node_modules/express/lib/router/route.js:137:13)
    at validationFunction (/portal/middleware/reqValidator.js:28:5)
    at validate (/portal/node_modules/express-openapi-validate/dist/OpenApiValidator.js:100:17)
    at validateReq (/portal/middleware/reqValidator.js:24:3)
    at newFn (/portal/node_modules/express-async-errors/index.js:16:20)
    at Layer.handle [as handle_request] (/portal/node_modules/express/lib/router/layer.js:95:5)
  name: 'LoadRunError',
  code: 'RUN_IN_PROGRESS',
  info:
   { name: 'LoadRunError',
     code: 'RUN_IN_PROGRESS',
     message:
      'Load run already in progress. For project 5b41e610-4e5a-11ea-a33d-71f549a0a68a' } }
[13/02/20 13:48:56 /portal/modules/LoadRunner.js] [INFO] httpCheckHealth 200
[13/02/20 13:48:56 /portal/modules/LoadRunner.js] [INFO] beginJavaProfiling: Starting liberty server
[13/02/20 13:48:56 dockerFunctions.js] [WARN] Unable to exec: project does not exist, has no container or is closed
[13/02/20 13:49:01 /portal/modules/LoadRunner.js] [INFO] httpCheckHealth 200
[13/02/20 13:49:01 /portal/modules/LoadRunner.js] [INFO] LibertyServer has responded to /health
[13/02/20 13:49:01 dockerFunctions.js] [WARN] Unable to exec: project does not exist, has no container or is closed
[13/02/20 13:49:01 /portal/modules/LoadRunner.js] [INFO] createCollection: 5b41e610-4e5a-11ea-a33d-71f549a0a68a, 172.30.94.46, 9080, javametrics
[13/02/20 13:49:01 /portal/modules/LoadRunner.js] [INFO] Load run on project 5b41e610-4e5a-11ea-a33d-71f549a0a68a started
(node:149) UnhandledPromiseRejectionWarning: Error: connect ECONNREFUSED 127.0.0.1:9090
    at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1106:14)
(node:149) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 8)
[13/02/20 13:49:21 /portal/modules/LoadRunner.js] [INFO] Load run on project 5b41e610-4e5a-11ea-a33d-71f549a0a68a completed
[13/02/20 13:49:22 /portal/modules/LoadRunner.js] [INFO] recordCollection: Metrics collection deleted
```

**Comment by stalleyj** [comment] 2020-02-19 09:18
This is a duplicate of https://github.com/eclipse/codewind/issues/2252

**Closed by stalleyj** 2020-02-19 09:18 UTC
Labels: area/portal, kind/bug
