### ISSUE TITLE
[odo] SVT: EACCES: permission denied, unlink configuration file

### ISSUE THREAD

**Issue by sujeilyfonseca** [eclipse/codewind#825] opened 2019-10-23 20:32 UTC
**Codewind version:** [0.5.0 ](https://raw.githubusercontent.com/eclipse/codewind-che-plugin/master/devfiles/0.5.0/devfile.yaml)
**OS:** Red Hat Enterprise Linux 7 (64 bit)

**Che version:** 7.2.0
**Kubernetes cluster:** OKD/Openshift 

**Description:** EACCES: permission denied, unlink configuration file with ODO Python and ODO Perl. This is an intermittent error, so it could not be reproduced all the time.

<img width="541" alt="Screen Shot 2019-10-23 at 12 21 37 PM" src="https://user-images.githubusercontent.com/49531960/67431512-6f315a80-f5b2-11e9-82dd-df4b8081b319.png">

![Screen Shot 2019-10-23 at 1 48 01 PM](https://user-images.githubusercontent.com/49531960/67431513-6f315a80-f5b2-11e9-815c-f96e5aa477ff.png)

**Steps to reproduce:**
1. Prepare an OKD Cluster 
2. Install Che 
3. Deploy a Codewind workspace
4. Create some ODO projects
5. Try to delete a project

@jagraj

**Comment by GeekArthur** [comment] 2019-10-24 19:30
The issue is `odo delete` is failed for some reason during the resources (eg. service, route, pvc) deletion process, then dangling `config.yaml` won't be deleted by non-root theia editor since `config.yaml` is generated by PFE which uses root as user.

**Comment by GeekArthur** [comment] 2019-12-05 23:07
`odo delete` can handle `config.yaml` deletion, can't reproduce this, close the issue.

**Closed by GeekArthur** 2019-12-05 23:07 UTC
Labels: area/iterative-dev, kind/bug
