### ISSUE TITLE
Appsody projects disabled by default on create - Eclipse IDE

### ISSUE THREAD

**Issue by ssh24** [eclipse/codewind#2095] opened 2020-02-07 15:59 UTC
**Description:**
Not sure if this is an intended behavior but I noticed that appsody projects are all disabled if you create a brand new project using Eclipse IDE. Did not notice this happening on VSCode.

/area appsody
/area eclipse-ide

**Comment by makandre** [comment] 2020-02-07 16:02
What version of Codewind?  0.8.1 by any chance?

**Comment by ssh24** [comment] 2020-02-07 16:11
Downloaded the master zip of eclipse ide

**Comment by makandre** [comment] 2020-02-07 16:14
Any error in logs?

Also could you `ls -la` contents of these folders in PFE:
- `/codewind-workspace/.extensions`
- `/extensions` (should be an appsody extension zip here, if so, are you able to list the contents?)

**Comment by ssh24** [comment] 2020-02-07 16:24
So if I have an existing project and restart PFE it comes up fine. Just happens on new projects. Which logs do you?

Here are the command outputs:
```
PS C:\Users\Administrator> docker exec -it codewind-pfe bash
[root@589f4fc9c0d7 /]# ls -al /codewind-workspace/.extensions
total 16
drwxrwxr-x  4 root root 4096 Feb  7 16:15 .
drwxrwxrwx 21 root root 4096 Feb  7 16:03 ..
drwxr-xr-x  4 root root 4096 Feb  5 16:59 codewind-appsody-extension
drwxr-xr-x  4 root root 4096 Feb  5 16:59 codewind-appsody-extension__old
[root@589f4fc9c0d7 /]# ls -al /extensions/
total 25132
drwxr-xr-x 2 root root     4096 Feb  7 15:46 .
drwxr-xr-x 1 root root     4096 Feb  7 16:15 ..
-rw-r--r-- 1 root root 11763906 Feb  7 15:45 codewind-appsody-extension-9.9.9999.zip
-rw-r--r-- 1 root root 13957394 Feb  7 15:45 codewind-odo-extension-9.9.9999.zip
```
This is also on Windows - didn't try on Mac yet

**Comment by makandre** [comment] 2020-02-07 16:32
PFE's log and project's `appsody.log` if available.

Just gave this a try on Mac, not reproducible there.

**Comment by ssh24** [comment] 2020-02-07 18:29
I was going to try it out again so that I can get the logs and now it started working for me :@

**Comment by eharris369** [comment] 2020-02-13 16:07
I tried creating several appsody projects and could not reproduce this.  Can you see if you can still reproduce?

**Comment by ssh24** [comment] 2020-02-13 17:35
@eharris369 I couldn't reproduce this today when I tried it out earlier. We can keep this issue open for the backlogs and if we see it in the future use it as a reference

**Comment by eharris369** [comment] 2020-03-03 20:58
Closing since it is not reproducible. Please re-open if you find that you can reproduce the problem.

**Closed by eharris369** 2020-03-03 20:58 UTC
Labels: area/appsody, area/eclipse-ide, kind/bug
