### ISSUE TITLE
SVT: Getting capabilities failed and Filewatcher status code 404 errors with Appsody Templates

### ISSUE THREAD

**Issue by sujeilyfonseca** [eclipse/codewind#1353] opened 2019-12-03 20:40 UTC
**Codewind version:** 0.6.1 & latest
**OS:** Windows 10, Mac OS, and Red Hat Enterprise Linux 7 (64 bit)

**Che version:** 7.3.1
**IDE extension version:** 0.6.1
**IDE version:** VS Code 1.40.2
**Kubernetes cluster:** OKD/Openshift

**Description:** Getting capabilities failed and Filewatcher status code 404 errors with Appsody Templates

![Screen Shot 2019-12-03 at 2 26 08 PM](https://user-images.githubusercontent.com/49531960/70087367-31c4e180-15e2-11ea-9faa-8471a68ad1be.png)

![Screen Shot 2019-12-03 at 2 58 55 PM](https://user-images.githubusercontent.com/49531960/70087302-0e9a3200-15e2-11ea-9513-b90c2cfe9e45.png)

<img width="1475" alt="Screen Shot 2019-12-03 at 3 15 52 PM" src="https://user-images.githubusercontent.com/49531960/70087326-1c4fb780-15e2-11ea-8d8c-b302f65b7cf1.png">

**Steps to reproduce the problem:**
1. Install and start Codewind
2. Create an Appsody project
3. Errors will appear on the screen
4. After the errors, the logs can be accessed and the project works fine

**Comment by johnmcollier** [comment] 2019-12-03 20:42
Errors seem to be identical to the ones seen in https://github.com/eclipse/codewind/issues/936

@stalleyj @makandre Thoughts?

**Comment by makandre** [comment] 2019-12-03 20:45
Yeah, I think this is a dup of https://github.com/eclipse/codewind/issues/1073 actually; but you're right is the same symptom and 1073 is the one that's still open.

**Comment by johnmcollier** [comment] 2019-12-03 20:46
Ah, I missed 1073

**Comment by johnmcollier** [comment] 2019-12-03 20:47
Closing as a dupe of #1073 then

**Closed by johnmcollier** 2019-12-03 20:47 UTC
Labels: kind/bug
