### ISSUE TITLE
Move the OpenShift Registry topic and signpost back to Getting Started user workflows

### ISSUE THREAD

**Issue by MelHopper** [eclipse/codewind#3188] opened 2020-06-25 17:11 UTC
**Problem:**

Both the **Using Codewind on eclipse che user workflow** and the **Using Codewind remotely user workflow** reference the topic `openshiftregistry.html`. However, the` openshiftregistry.html `topic exists within the Eclipse Che block only. 

In addition, it represents an optional setup so should not be part of the Getting Started journey for Eclipse Che or Remote. Instead, the topic  needs to be in the Product Reference section of **'Developing Projects**' and referenced from within the user workflows.

<img width="335" alt="Screenshot 2020-06-25 at 18 07 14" src="https://user-images.githubusercontent.com/13365734/85766297-d2115d80-b70e-11ea-98c4-48e7be0e85ad.png">

**Solution**
1. Move the `openshiftregistry.html` topic out of the Eclipse Che block and into the Developing Projects block of the ToC. 

2. Add a 'Next Steps' section to the `openshiftregistry.html` topic to signpost the user to the next topic in their Getting Started workflow for Eclipse Che ((i.e che-createcodewindworkspace.html) or for Remote (i.e che-remotedeploy-projects-vscode.html or remotedeploy-projects-eclipse.html )

**Comment by micgibso** [comment] 2020-06-29 08:27
Not a bug, more of an enhancement.

**Comment by micgibso** [comment] 2020-07-01 08:18
Closing as complete.

**Closed by micgibso** 2020-07-01 08:18 UTC
Labels: area/docs, kind/enhancement
