### ISSUE TITLE
vscode not sending authenticate token after resetting connection

### ISSUE THREAD

**Issue by tobespc** [eclipse/codewind#1457] opened 2019-12-10 16:14 UTC
UI socket is not sending the access token when reconnecting to a remote codewind.

pfe logs show 
```
[10/12/19 16:08:19 /portal/routes/projects/fileChanges.route.js] [INFO] Watch status for projectID 3277e3c0-1b46-11ea-8f3b-115db09824da: success
[10/12/19 16:08:19 socketAuth.js] [INFO] UISocket : [pre-authenticate]
[10/12/19 16:08:19 socketAuth.js] [ERROR] UISocket : [verifySocketUser] - secret or public key must be provideds
[10/12/19 16:08:19 socketAuth.js] [INFO] UISocket : [authenticate] - /default#MnhnWe-mNNjNDNYVAAAH unauthorized: TOKEN_REJECTED
[10/12/19 16:08:19 socketAuth.js] [INFO] UISocket : [disconnect] - /default#MnhnWe-mNNjNDNYVAAAH disconnected.
```

I can recreate by removing a connection in vscode, then adding a new one to the same gatekeeper, this then occurs.  To fix I need to remove all connections and stop and start codewind

**Comment by tetchel** [comment] 2019-12-10 18:41
i too have noticed funky "reconnect" behaviour with the socket. Do you see this message in vscode?

`Socket at ${this.uri} did not respond to authentication request within ${timeoutS} seconds. Try refreshing the connection.`

I definitely am sending the authentication event again, and from the logs you have above, it looks like it is indeed receiving that event, it's just rejecting it (`TOKEN_REJECTED`) ?

**Comment by tetchel** [comment] 2019-12-10 22:06
I definitely saw an issue at least similar to this this morning, but I can't reproduce it now that I'm testing against Codewind 0.7.0. It may also have been resolved by https://github.com/eclipse/codewind-vscode/commit/bc1b1324737d628e419e7f89ee5f82b983700651

Can you try it again in the morning?

**Closed** 2019-12-17 15:14 UTC
Labels: area/vscode-ide, kind/bug, priority/hot

**Comment by tobespc** [comment] 2019-12-17 15:29
verified, all ok
