### ISSUE TITLE
Registry content in Eclipse Che is confusing and does not match identical information in remote section

### ISSUE THREAD

**Issue by MelHopper** [eclipse/codewind#3189] opened 2020-06-25 17:21 UTC
**Problem**

The registry topics of the Eclipse Che Getting Started content is confusing and does not match what should be an identical topic in the Remote Getting Started section.

It is also not clear in which use cases you would need to add an image registry.
 
**Solution**

The content of `che-setupregistries.html` and `remote-setupregistries.html` should match. 

In addition, it appears that the use cases in the  **prerequisites section** of `che-setupregistries.html` and also the **Determining if you need an image registry section** of `remote-setupregistries.html` are not exhaustive and may be incorrect

**Details**
The content for the **prerequisites section** of `remote-setupregistries.html` looks like it needs to be replaced with the **Determining if you need an image registry section** of `che-setupregistries.html` (this is clearer) so that both topics match. **But**, the accuracy of the **Determining if you need an image registry section** of `che-setupregistries.html` also needs to be checked with a developer to ensure it encompasses all scenarios. Image registries need to be added for several reasons, and these reasons need to be made clearer.

**Comment by micgibso** [comment] 2020-06-29 08:26
Not a bug, more of an enhancement.

**Comment by micgibso** [comment] 2020-07-02 10:28
PR approved and merged.

**Closed by micgibso** 2020-07-02 10:28 UTC
Labels: area/docs, kind/bug
