### ISSUE TITLE
SVT: VSCode: Creating a remote connection can fail with certain network conditions.

### ISSUE THREAD

**Issue by DavidG1011** [eclipse/codewind#2285] opened 2020-02-20 23:25 UTC
**Codewind version:** 0.9.0
**OS:** MacOS

**Kubernetes cluster:**  OKD 4.2

**Description:** This is definitely an edge case, but... I noticed If I'm working remotely but connected to the IBM network via VPN, it can cause a "no such host error" upon attempting to connect to a remote cluster:

![image](https://user-images.githubusercontent.com/30476587/74988619-4019e100-540c-11ea-832d-88b07d8a8c93.png)

This can also occur when running `cwctl install remote ...`:

![image](https://user-images.githubusercontent.com/30476587/74989102-83288400-540d-11ea-8c83-284b9993ac26.png)

**Steps to reproduce:**
1. Connect to a network other than the IBM intranet.
2. Connect to IBM network using VPN.
3. Create a new remote connection with an existing gatekeeper.

@jagraj

**Comment by tetchel** [comment] 2020-02-20 23:26
can you open that url in the browser?

**Comment by naveenkaratekid** [comment] 2020-02-20 23:30
I too have seen a similar issue when I tried to configure remote at home when I used my master node:

```
INFO[0000] Checking namespace codewind exists           
INFO[0000] Creating codewind namespace                  
ERRO[0000] Unable to create codewind namespace: Post https://nk-openshift-master.rtp.raleigh.ibm.com:8443/api/v1/namespaces: dial tcp: lookup nk-openshift-master.rtp.raleigh.ibm.com on 209.18.47.61:53: no such host 
ERRO[0000] Error: rem_create_namespace - Post https://nk-openshift-master.rtp.raleigh.ibm.com:8443/api/v1/namespaces: dial tcp: lookup nk-openshift-master.rtp.raleigh.ibm.com on 209.18.47.61:53: no such host 
Naveens-MacBook-Pro:0.8.0 naveenk@ibm.com$ ssh root@nk-openshift-master.rtp.raleigh.ibm.com```
```

**Comment by tetchel** [comment] 2020-02-20 23:32
if your computer can't find the hostname, it can't do anything against that node.

This is the correct behaviour

**Comment by DavidG1011** [comment] 2020-02-20 23:37
It's reachable from the browser:

![image](https://user-images.githubusercontent.com/30476587/74989887-b0763180-540f-11ea-9134-0c0dd0255ad7.png)


![image](https://user-images.githubusercontent.com/30476587/74989983-f632fa00-540f-11ea-95fc-f0bcf28f8508.png)

**Comment by tetchel** [comment] 2020-02-20 23:39
@markcor11 is there any reason the installer code may have different DNS behaviour than the browser? 😕

**Comment by sujeilyfonseca** [comment] 2020-02-21 01:06
I’ve seen this problem every time I use the VPN, if I try to deploy a new remote connection: 

```
ERRO[0000] Unable to create cw namespace: Post https://sfonseca-okd-codewind.rtp.raleigh.ibm.com:8443/api/v1/namespaces: dial tcp: lookup sfonseca-okd-codewind.rtp.raleigh.ibm.com on 192.168.1.1:53: no such host 
ERRO[0000] Error: rem_create_namespace - Post https://sfonseca-okd-codewind.rtp.raleigh.ibm.com:8443/api/v1/namespaces: dial tcp: lookup sfonseca-okd-codewind.rtp.raleigh.ibm.com on 192.168.1.1:53: no such host 
```

Note: The console can be accessed over the browser, and I can successfully access the host in the cluster. 

My workaround is to deploy the remote connection directly in the OKD/Openshift cluster, using the `cwctl-linux`, and use the gatekeeper URL in the IDE. That way, I can deploy and establish a new remote connection using the VPN..

**Comment by sujeilyfonseca** [comment] 2020-02-21 01:07
I’ve seen this problem every time I use the VPN, if I try to deploy a new remote connection: 

```
ERRO[0000] Unable to create cw namespace: Post https://sfonseca-okd-codewind.rtp.raleigh.ibm.com:8443/api/v1/namespaces: dial tcp: lookup sfonseca-okd-codewind.rtp.raleigh.ibm.com on 192.168.1.1:53: no such host 
ERRO[0000] Error: rem_create_namespace - Post https://sfonseca-okd-codewind.rtp.raleigh.ibm.com:8443/api/v1/namespaces: dial tcp: lookup sfonseca-okd-codewind.rtp.raleigh.ibm.com on 192.168.1.1:53: no such host 
```

Note: The console can be accessed over the browser, and I can successfully access the host in the cluster. 

My workaround is to deploy the remote connection directly in the OKD/Openshift cluster, using the `cwctl-linux`, and use the gatekeeper URL in the IDE. That way, I can deploy and establish a new remote connection using the VPN.

**Comment by markcor11** [comment] 2020-02-21 07:38
This looks like a networking / vpn issue because I've seen something similar recently.  I haven't dug in much but both `oc` or `kubectl` started showing this problem too when using vpn from home in the evenings. 

oc login --token=xzu-7sIfXWDPE....  --server=https://mycluster.api......com:6443. returned :   

error: dial tcp: lookup mycluster.api......com on <myLanDNSServer> *no such host - verify you have provided the correct host and port and that the server is currently running.*

what's interesting is even `nslookup mycluster.api.....com` fails however ping worked. 

From your trace  ```ERRO[0000] Error: rem_create_namespace - Post https://sfonseca-okd-codewind.rtp.raleigh.ibm.com:8443/api/v1/namespaces: dial tcp: lookup sfonseca-okd-codewind.rtp.raleigh.ibm.com on 192.168.1.1:53: no such host ```

port 53 is used by DNS so 192.168.1.1:53 looks like your local lan DNS server which matches what I saw too. 

Until we better understand what has changed in MacOS / VPN / DNS Forwarder,  Could you try : 

1.   ping sfonseca-okd-codewind.rtp.raleigh.ibm.com
2.  check that you get back the correct tcpip address
3.  add that to your /etc/hosts. 
4.  test cwctl again

**Comment by tobespc** [comment] 2020-02-21 11:16
I can't access any of my fyre machines when connecting from home

**Comment by sujeilyfonseca** [comment] 2020-02-21 12:38
@markcor11, your workaround works.

1. Pinged my host and verified the returned address:
```
(base) Sujeilys-MBP:~ sfonseca$ ping sfonseca-okd-codewind.rtp.raleigh.ibm.com
PING sfonseca-okd-codewind.rtp.raleigh.ibm.com (9.37.222.128): 56 data bytes
64 bytes from 9.37.222.128: icmp_seq=0 ttl=54 time=33.415 ms
64 bytes from 9.37.222.128: icmp_seq=1 ttl=54 time=60.482 ms
64 bytes from 9.37.222.128: icmp_seq=2 ttl=54 time=40.087 ms
64 bytes from 9.37.222.128: icmp_seq=3 ttl=54 time=38.171 ms
64 bytes from 9.37.222.128: icmp_seq=4 ttl=54 time=38.823 ms
```

2. Opened my Mac's Hosts File: `sudo nano /etc/hosts`
3. Added the new TCP/IP: `9.37.222.128    sfonseca-okd-codewind.rtp.raleigh.ibm.com`
4. Saved the file: `Ctrl + O`
5. Exited the file: `Ctrl + X`
6. Cleared my Mac's DNS cache: `sudo killall -HUP mDNSResponder`

After that, I successfully deployed a new remote connection using the VPN:
```
...
NFO[0047] Preparing Codewind Gatekeeper resources      
INFO[0047] Creating codewind-gatekeeper-k6w5j584.9.37.222.128.nip.io server Key 
INFO[0047] Creating codewind-gatekeeper-k6w5j584.9.37.222.128.nip.io server certificate 
INFO[0047] Deploying Codewind Gatekeeper Secrets        
INFO[0047] Deploying Codewind Gatekeeper Session Secrets 
INFO[0047] Deploying Codewind Gatekeeper TLS Secrets    
INFO[0047] Deploying Codewind Gatekeeper Deployment     
INFO[0047] Deploying Codewind Gatekeeper Service        
INFO[0047] Deploying Codewind Gatekeeper Route          
INFO[0047] Waiting for pod: codewind-gatekeeper-k6w5j584 
INFO[0047] codewind-gatekeeper-k6w5j584, phase: Pending   
INFO[0047] codewind-gatekeeper-k6w5j584, phase: Pending ContainersNotReady  
INFO[0050] codewind-gatekeeper-k6w5j584, phase: Running   
INFO[0050] Waiting for Codewind Gatekeeper to start on https://codewind-gatekeeper-k6w5j584.9.37.222.128.nip.io 
.....
INFO[0055] Waiting for Codewind PFE to start            
.
INFO[0056] Codewind is available at: https://codewind-gatekeeper-k6w5j584.9.37.222.128.nip.io
```

**Comment by naveenkaratekid** [comment] 2020-02-21 12:45
Are the steps similar if using OKD from the public cloud?

**Comment by sujeilyfonseca** [comment] 2020-02-21 12:58
Yes, @naveenkaratekid

**Comment by tetchel** [comment] 2020-02-21 15:25
Should we doc the workaround?

**Comment by markcor11** [comment] 2020-04-21 12:28
I think we can close this, problem is caused by the wrong DNS server listed in the workstations network settings. Changing to the correct DNS server which knows about "private zone" addresses resolves the problem.

/close

**Closed** 2020-04-21 12:28 UTC
Labels: area/portal, kind/bug
