### ISSUE TITLE
Codewind install on windows need disk share as prereq for both VSCode and Eclipse.

### ISSUE THREAD

**Issue by jagraj** [eclipse/codewind#466] opened 2019-09-17 14:42 UTC
**Codewind version:** 0.4
**OS:** Windows

**Che version:** 
**IDE extension version:** 0.4
**IDE version:** Eclipse and VSCode
**Kubernetes cluster:**

**Description:**
We need to add disk share as prereq for windows users. Here is more information that we documented in Microclimate.dev docs. 

https://microclimate.dev/installlocally#installing-on-windows

```
Enable your local disk drive for sharing in Docker. Open the Docker Settings window, click the Shared Drives tab, and select the drive on which you are installing Microclimate.
For help resolving issues when using OS authentication setups such as AzureAD, see the Troubleshooting page.
```

**Steps to reproduce:**

**Workaround:** 

@sishida

**Comment by tobespc** [comment] 2019-09-18 08:45
this issue will go away when we have the new architecture for codewind (the hybrid stuff)

**Comment by sishida** [comment] 2019-09-18 17:25
@jagraj and @tobespc If we plan to eventually resolve this issue, ID will not update the Troubleshooting page in the docs. Instead, let's just leave all the info in this issue for reference.

**Comment by jagraj** [comment] 2019-09-19 17:26
I came to know we have close to 70 to 80% os the users coming to conferences using Windows for the labs. It will be nice to doc this as prerequisite section for Codewind install in the docs. This will definitely help avoid install failures.

**Comment by sishida** [comment] 2019-09-20 14:08
@jagraj Because @tobes mentions that this issue will go away when we have the new Codewind architecture, I'd prefer to leave this info in an issue and not update the doc. If I updated the doc, we'd just have to remember to remove the info later.

**Comment by sishida** [comment] 2019-09-26 15:03
After talking with @jagraj, we are currently unsure if this issue will go away, so we will wait until testing of the 0.5.0 hybrid scenario until we take further action.

**Comment by sishida** [comment] 2019-10-29 19:38
Update: The hybrid/remote scenario didn't go in the 0.5.0 release but is scheduled to go in with 0.6.0, the docs team will follow up about this issue after the testing of the 0.6.0 hybrid/remote scenario.

**Comment by sishida** [comment] 2020-01-07 16:54
@jagraj Hi, Jag, Now that Codewind remote is in tech preview, can we confirm that this issue is resolved? Or does it still need to be worked on? Thank you!

**Comment by jagraj** [comment] 2020-01-09 19:36
@tobespc 
Not sure how new architecture address this prerequisite. As a prerequisite user must share their drive on Windows with their user account.

**Comment by tobespc** [comment] 2020-01-10 10:25
this is no longer a pre req for windows.  The changes that went in to 0.7.0 removed the need for anything to be shared locally.   Its not the remote change as such, more the general architecture change

**Comment by sishida** [comment] 2020-01-10 14:19
@jagraj and @tobespc If the prereq is no longer needed, would it be OK to close this issue? Please let us know. Thank you! 😸

**Comment by jagraj** [comment] 2020-01-10 15:20
@tobespc 
We don't have to share even for appsody projects.? I got into this issue (https://github.com/eclipse/codewind/issues/1690) with the 0.8.0 release.

**Comment by tobespc** [comment] 2020-02-03 11:22
appsody projects are the only ones that need sharing still

**Comment by micgibso** [comment] 2020-03-13 11:00
ID complete.

**Comment by micgibso** [comment] 2020-04-20 13:23
Reopening to change the description from Appsody to all projects. Discussion:

Andy Watson:
Noticed a tweet around codewind and docker drive sharing.  Do we require the share for all windows users or just when using appsody (as per the docs ?) https://www.eclipse.org/codewind/vsc-getting-started.html

Andrew Mak
I think the issue is step 3 “If you are planning to work with Appsody projects…”  You need to share drive regardless

Jagadeeswar Gangaru
Yes, as we should not determine if user going to use appsody or not at that point. I think we need to make that mandatory for codewind install.

**Closed** 2020-05-13 07:09 UTC
Labels: area/docs, kind/bug
