### ISSUE TITLE
SVT:Codewind did not start in the expected time.Process did not complete and had to be terminated

### ISSUE THREAD

**Issue by jagraj** [eclipse/codewind#256] opened 2019-08-22 12:22 UTC
**Codewind version:** Latest
**OS:** Windows

**Che version:**
**IDE extension version:**   
Codewind tech preview	0.3.0.v201908161735	org.eclipse.codewind.feature.group	IBM

**IDE version:**
Eclipse IDE for Enterprise Java Developers.

Version: 2019-06 (4.12.0)
Build id: 20190614-1200

**Description:**
I am getting following message after starting codewind from eclipse plugin tools. Even though it is started and running. Looks like some timing issue here if I have multiple projects in my workspace.

Codewind did not start in the expected time.Process did not complete and had to be terminated.

**Steps to reproduce:**
1. Install latest codewind.
2. Create all samples from the available templates.
3. Wait until all the projects up and running.
4. Restart docker daemon for any changes to take effect.
5. After docker daemon up and running then try to start codewind again.
6. I got into this error message in the dialog. (Codewind did not start in the expected time.Process did not complete and had to be terminated.)

 

![image](https://user-images.githubusercontent.com/713849/63513887-5a9eec00-c4b5-11e9-85ba-c95078553fc9.png)

Workspace log.
[.log](https://github.com/eclipse/codewind/files/3530085/default.log)

**Workaround:**

**Comment by tetchel** [comment] 2019-08-22 13:29
I wonder if it is because you have so many projects

**Comment by jagraj** [comment] 2019-08-22 14:37
Could be, may be we need to provide settings to the user so that they can configure based on their workspace size.?

**Comment by jagraj** [comment] 2019-08-22 14:38
May be you can set these timeouts based on user projects list size.?

**Comment by tobespc** [comment] 2019-09-09 09:58
we now a ready api that should now be called to determine that portal is ready before any builds are attempted.  @eharris369 Can you check what it is the eclipse plugin is waiting for please?

**Comment by eharris369** [comment] 2019-09-09 13:27
It waits for the installer to return from the start request which it looks like is timing out.  If it is actually up and running you should be able to right click on Codewind in the view and select Refresh.  I have a PR for checking that Codewind is ready before creating a connection: https://github.com/eclipse/codewind-eclipse/pull/263 but I don't think that is the problem as it will not even get that far if it does not think Codewind is in started state.  I also have an issue open for allowing the user to set the start/stop and install/uninstall timeouts: https://github.com/eclipse/codewind-eclipse/issues/47.  I would not have thought having a lot of projects would affect Codewind start.  I will try to reproduce and investigate.

**Comment by eharris369** [comment] 2019-09-09 18:14
I checked with Elson and the number of projects should not affect Codewind start.  It would affect Codewind stop since it needs to stop all of the project containers but not start.

**Comment by tobespc** [comment] 2020-01-06 16:23
I don't believe this is valid anymore, moving to verify

**Comment by malincoln** [comment] 2020-01-07 18:52
@jagraj pls verify and close if resolved. Thanks

**Comment by stalleyj** [comment] 2020-02-19 10:14
This is complete.

**Closed by stalleyj** 2020-02-19 10:14 UTC
Labels: area/eclipse-ide, area/portal, kind/bug
