### ISSUE TITLE
Eclipse Add Template Source panel: can tab into non-editable area

### ISSUE THREAD

**Issue by mattcolegate** [eclipse/codewind#782] opened 2019-10-22 10:46 UTC
**Codewind version:** latest hybrid
**OS:** Windows 10

**Che version:** N/A
**IDE extension version:** 0.5.0v201910171920
**IDE version:** 2019-06
**Kubernetes cluster:** N/A

**Description:** Tabbing through the panel tabs into the label 'Supply a URL, name and description for the new template source'.

**Steps to reproduce:** Start Codewind and right click Local in the Codewind Explorer view. Select Manage Template Sources... and press Add in the resulting panel. Press the tab key to cycle through the fields in the new resulting panel. As well as editable fields and the buttons, the above label also can be selected.

**Workaround:** N/A

**Comment by eharris369** [comment] 2019-10-22 12:55
This is a duplicate of #776.  Please don't open separate issues for the same thing.  Just rename the original issue as "Can tab to labels in Eclipse dialogs and wizards" and then list the dialogs and wizards affected in the details.

**Closed by eharris369** 2019-10-22 12:55 UTC
Labels: kind/bug
