### ISSUE TITLE
Each open liberty project build leaves behind 3 (now 2) ~400 MB dangling docker image

### ISSUE THREAD

**Issue by makandre** [eclipse/codewind#2391] opened 2020-03-03 22:02 UTC
**Codewind version:**
**OS:**

**Che version:**
**IDE extension version:**
**IDE version:**
**Kubernetes cluster:**

**Description:**

Every time a Codewind open liberty project is built, it leaves behind 3 roughly 400 MB dangling docker image (1 image per stage of the multi-stage docker build):

```
andrewmak@andrews-mbp ~ % docker images | grep none        
<none>                                                        <none>                              c2cd220732e5        29 seconds ago      442MB
<none>                                                        <none>                              4b0e9df2616b        31 seconds ago      481MB
<none>                                                        <none>                              076dcfd4dcc5        8 minutes ago       413MB
<none>                                                        <none>                              4ab4f56e23f4        8 minutes ago       442MB
<none>                                                        <none>                              9330eac0f7f4        8 minutes ago       481MB
<none>                                                        <none>                              32f6d5bfc030        25 hours ago        413MB
```

**Steps to reproduce:**

**Workaround:**

**Comment by makandre** [comment] 2020-03-04 20:35
Turns out open liberty projects are Docker type projects in Codewind, and this problem of leaving dangling images behind exists for all Docker type projects.

PR https://github.com/eclipse/codewind/pull/2402 ensures we remove the dangling final image but it doesn't fully solve the problem for projects using multi-stage docker build (`lagom`, `open liberty`).  For these project the intermediate image from the multi-stage build is still left behind.

**Comment by hhellyer** [comment] 2020-07-01 14:42
Is this a problem? I googled quickly to see if anyone else was seeing this issue and someone has raised a bug against docker asking about dangling images in multi-stage builds - https://github.com/moby/moby/issues/34151

The consensus seems to be that the `<none>` images are important as they act as caching layers for subsequent rebuilds. Removing them after each build would slow the builds down.

If a user was running multi-stage docker builds outside of codewind they would see the same issue and also lose the benefit of the cached intermediate images if they pruned them.

I'm inclined to say we should close this as working as designed. (Even though I find the `<none>` images a bit annoying too.)

@makandre - Do you think we really should delete these images, bearing in mind it will slow down docker builds or can this issue be closed?

**Comment by makandre** [comment] 2020-07-01 20:24
Agree we shouldn't "fix" this at the expense of losing build caching, and this should be fixed similar to https://github.com/eclipse/codewind/issues/2389#issuecomment-594183605. But with multistage build maybe it's not possible since we don't know what the old intermediate layers are.

If it's not trivial without some fix in docker itself, I'm ok to close this as a limitation.

**Comment by hhellyer** [comment] 2020-07-07 10:54
Closing as this is a limitation caused by docker working as designed.

**Closed by hhellyer** 2020-07-07 10:54 UTC
Labels: area/iterative-dev, kind/bug
