### ISSUE TITLE
SVT: Eclipse IDE : Mac : AppsodyEclipseMicropofile project stuck in starting 

### ISSUE THREAD

**Issue by mmulholl** [eclipse/codewind#1703] opened 2020-01-10 15:48 UTC
**Codewind version:**   Codewind tech preview	0.8.0.v202001082125	
**OS:** Mac

**Che version:**
**IDE extension version:** 
**IDE version:**Eclipse IDE for Enterprise Java Developers. Version: 2019-09 R (4.13.0). Build id: 20190917-1200
**Kubernetes cluster:**

**Description:**
After creating an AppsodyEclipseMicropropfile the project gets stuck in starting state.

This in the app logs:

Running development environment...
Pulling docker image docker.io/appsody/java-microprofile:0.2
Running command: docker pull docker.io/appsody/java-microprofile:0.2
0.2: Pulling from appsody/java-microprofile
Digest: sha256:44deecb2d0b2567e964444e9ba9d50417b355a0c3956237e0de74f1e248aa0db
Status: Image is up to date for appsody/java-microprofile:0.2
[Warning] Could not stat mount path: /root/.m2/repository
[Warning] Could not mount /root/.m2/repository:/mvn/repository because the local file was not found.
Running command: docker run --rm -P --name cw-appsodyeclipsemicro007-bdc7d310-33b8-11ea-9f49-d1f2144d13b2 --network codewind_network -v /Users/mmulholl@us.ibm.com/codewind-data/AppsodyEclipseMicro007/src:/project/user-app/src -v /Users/mmulholl@us.ibm.com/codewind-data/AppsodyEclipseMicro007/pom.xml:/project/user-app/pom.xml -v appsody-controller-0.3.3:/.appsody -t --entrypoint /.appsody/appsody-controller docker.io/appsody/java-microprofile:0.2 --mode=run
[Container] Running APPSODY_PREP command: ../validate.sh && mvn -B -Dmaven.repo.local=/mvn/repository install -DskipTests && /project/install-dev-deps.sh
[Container] Installing parent dev.appsody:java-microprofile:0.2.21
[Container] [[1;34mINFO[m] Scanning for projects...
[Container] [[1;34mINFO[m] 
[Container] [[1;34mINFO[m] [1m-------------------< [0;36mdev.appsody:java-microprofile[0;1m >--------------------[m
[Container] [[1;34mINFO[m] [1mBuilding java-microprofile 0.2.21[m
[Container] [[1;34mINFO[m] [1m--------------------------------[ pom ]---------------------------------[m
[Container] [[1;34mINFO[m] 
[Container] [[1;34mINFO[m] [1m--- [0;32mmaven-enforcer-plugin:3.0.0-M2:enforce[m [1m(enforce-versions)[m @ [36mjava-microprofile[0;1m ---[m
[Container] [[1;34mINFO[m] Skipping Rule Enforcement.
[Container] [[1;34mINFO[m] 
[Container] [[1;34mINFO[m] [1m--- [0;32mmaven-install-plugin:2.4:install[m [1m(default-install)[m @ [36mjava-microprofile[0;1m ---[m
[Container] [[1;34mINFO[m] Installing /project/user-app/../pom.xml to /mvn/repository/dev/appsody/java-microprofile/0.2.21/java-microprofile-0.2.21.pom
[Container] [[1;34mINFO[m] [1m------------------------------------------------------------------------[m
[Container] [[1;34mINFO[m] [1;32mBUILD SUCCESS[m
[Container] [[1;34mINFO[m] [1m------------------------------------------------------------------------[m
[Container] [[1;34mINFO[m] Total time:  2.363 s
[Container] [[1;34mINFO[m] Finished at: 2020-01-10T14:52:17Z
[Container] [[1;34mINFO[m] [1m------------------------------------------------------------------------[m
[Container] failed to load external entity "pom.xml"
[Container] failed to load external entity "pom.xml"
[Container] failed to load external entity "pom.xml"
[Container] Project pom.xml is missing the required parent:
[Container] 
[Container]   <parent>
[Container]     <groupId>dev.appsody</groupId>
[Container]     <artifactId>java-microprofile</artifactId>
[Container]     <version></version>
[Container]     <relativePath/>
[Container]   </parent>
[Container]   
[Container] [Error] FATAL error APPSODY_PREP command received an error.  The controller is exiting: exit status 1
[Error] Error in 'appsody run': exit status 1

**Steps to reproduce:**

**Workaround:**

**Comment by malincoln** [comment] 2020-01-10 17:17
@sghung pls review

**Comment by makandre** [comment] 2020-01-10 17:20
I was not able to reproduce and asking others on the team to try.  It is likely an environment or stack issue since not much was changed in appsody extension for 0.8.0

**Comment by sghung** [comment] 2020-01-10 17:43
I run into this issue: https://github.com/eclipse/codewind/issues/1690

Not sure why fhat isn't blocking this scenario from happening. Although in both cases, it is complaining about a missing pom.xml

**Comment by keithchong** [comment] 2020-01-10 18:05
I reproduced this only once.  I tried to rebuild (it downloaded dependencies again) and it built successfully.

[Container] failed to load external entity "pom.xml"
[Container] failed to load external entity "pom.xml"
[Container] failed to load external entity "pom.xml"
[Container] Project pom.xml is missing the required parent:
[Container] 
[Container]   <parent>
[Container]     <groupId>dev.appsody</groupId>
[Container]     <artifactId>java-microprofile</artifactId>
[Container]     <version></version>
[Container]     <relativePath/>
[Container]   </parent>
[Container]   
[Container] [Error] FATAL error APPSODY_PREP command received an error.  The controller is exiting: exit status 1
[Error] Error in 'appsody run': exit status 1

**Comment by mmulholl** [comment] 2020-01-10 21:35
Seeing it with Appsody Spring Kotlin project too, if it is an environment problem what can I do?

**Comment by mmulholl** [comment] 2020-01-10 21:50
I do see a lot of old appsody docker images, maybe they need cleaning up

**Comment by mmulholl** [comment] 2020-01-13 15:24
actually Kotlin does not have an issue, just AppsodyEclipseMicroprofile.

**Comment by sghung** [comment] 2020-01-13 15:57
Assigning to myself since I believe it is closely related to #1690, which I am investigating right now

**Comment by sghung** [comment] 2020-01-16 19:53
Closing as dupe of #1690

**Closed by sghung** 2020-01-16 19:53 UTC
Labels: area/appsody, kind/bug, priority/stopship
