### ISSUE TITLE
SVT : Eclipse : Mac : Spring apps failing maven build

### ISSUE THREAD

**Issue by mmulholl** [eclipse/codewind#1510] opened 2019-12-12 17:23 UTC
**Codewind version:**  Codewind tech preview	0.7.0.v201912112008	
**OS:** Mac

**Che version:**
**IDE extension version:** 2019-0019
**IDE version:** 2019-009 Eclipse jee
**Kubernetes cluster:**

**Description:**
Spring app fail maven build. See this is the workspace log:

!ENTRY org.eclipse.codewind.core 4 0 2019-12-12 12:19:49.295
!MESSAGE [ERROR JSONObjectResult.getString:41] The project template object did not have the expected key: projectStyle

**Steps to reproduce:**

**Workaround:**

**Comment by mmulholl** [comment] 2019-12-12 17:27
This from the pfe log:
[12/12/19 17:19:59 /portal/routes/projects/remoteBind.route.js] [INFO] Project Springer007a syncing with build container, projectRoot is /root/app
[12/12/19 17:19:59 /portal/routes/projects/remoteBind.route.js] [ERROR] { Error: Command failed: docker cp /codewind-workspace/Springer007a/. undefined:/root/app
Error: No such container:path: undefined:/root

    at ChildProcess.exithandler (child_process.js:294:12)
    at ChildProcess.emit (events.js:198:13)
    at maybeClose (internal/child_process.js:982:16)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:259:5)
  killed: false,
  code: 1,
  signal: null,
  cmd:
   'docker cp /codewind-workspace/Springer007a/. undefined:/root/app',
  stdout: '',
  stderr: 'Error: No such container:path: undefined:/root\n' }
[12/12/19 17:19:59 /portal/middleware/errorHandler.js] [ERROR] { error:
   { name: 'Error [ERR_HTTP_HEADERS_SENT]',
     message: 'Cannot set headers after they are sent to the client' } }
Error [ERR_HTTP_HEADERS_SENT]: Cannot set headers after they are sent to the client
    at ServerResponse.setHeader (_http_outgoing.js:470:11)
    at ServerResponse.header (/portal/node_modules/express/lib/response.js:771:10)
    at ServerResponse.send (/portal/node_modules/express/lib/response.js:170:12)
    at handleErrors (/portal/middleware/errorHandler.js:8:26)
    at newFn (/portal/node_modules/express-async-errors/index.js:16:20)
    at Layer.handle_error (/portal/node_modules/express/lib/router/layer.js:71:5)
    at trim_prefix (/portal/node_modules/express/lib/router/index.js:315:13)
    at /portal/node_modules/express/lib/router/index.js:284:7
    at Function.process_params (/portal/node_modules/express/lib/router/index.js:335:12)
    at next (/portal/node_modules/express/lib/router/index.js:275:10)
[12/12/19 17:20:03 /portal/routes/projects/remoteBind.route.js] [ERROR] { Error: Command failed: docker exec undefined rm -rf /root/app/Dockerfile-build
Error: No such container: undefined

    at ChildProcess.exithandler (child_process.js:294:12)
    at ChildProcess.emit (events.js:198:13)
    at maybeClose (internal/child_process.js:982:16)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:259:5)
  killed: false,
  code: 1,
  signal: null,
  cmd: 'docker exec undefined rm -rf /root/app/Dockerfile-build',
  stdout: '',
  stderr: 'Error: No such container: undefined\n' }
[12/12/19 17:20:03 /portal/middleware/errorHandler.js] [ERROR] { error:
   { name: 'Error [ERR_HTTP_HEADERS_SENT]',
     message: 'Cannot set headers after they are sent to the client' } }
Error [ERR_HTTP_HEADERS_SENT]: Cannot set headers after they are sent to the client
    at ServerResponse.setHeader (_http_outgoing.js:470:11)
    at ServerResponse.header (/portal/node_modules/express/lib/response.js:771:10)
    at ServerResponse.send (/portal/node_modules/express/lib/response.js:170:12)
    at handleErrors (/portal/middleware/errorHandler.js:8:26)
    at newFn (/portal/node_modules/express-async-errors/index.js:16:20)
    at Layer.handle_error (/portal/node_modules/express/lib/router/layer.js:71:5)
    at trim_prefix (/portal/node_modules/express/lib/router/index.js:315:13)
    at /portal/node_modules/express/lib/router/index.js:284:7
    at Function.process_params (/portal/node_modules/express/lib/router/index.js:335:12)
    at next (/portal/node_modules/express/lib/router/index.js:275:10)
[12/12/19 17:20:08 Springer007] [INFO] pingApplications: Application state error message: Failed to get application status: connect ECONNREFUSED 192.168.208.4:8080
martins-mbp-2:automation-codewind-svt mmulholl@us.ibm.com$

**Comment by jagraj** [comment] 2019-12-12 20:05
I just hit same issue after moving to latest 0.7.0 images. My codewind default spring project failing to build.

**Comment by tobespc** [comment] 2019-12-13 09:17
isn't this the same issue as https://github.com/eclipse/codewind/issues/1414 ?
You need to make sure you have created a new spring project that has the docker-build file

**Comment by malincoln** [comment] 2019-12-13 19:30
@mmulholl pls confirm 1414 resolves this issue.  Thanks

**Comment by mmulholl** [comment] 2019-12-13 20:10
Issue not solved

**Comment by malincoln** [comment] 2019-12-13 20:52
@elsony ^^^

**Comment by malincoln** [comment] 2019-12-13 21:36
duplicate of #1414

**Closed** 2019-12-13 21:37 UTC
Labels: area/eclipse-ide, area/iterative-dev, duplicate, kind/bug, priority/stopship
