### ISSUE TITLE
[Che] Autobuild broken on master

### ISSUE THREAD

**Issue by johnmcollier** [eclipse/codewind#901] opened 2019-10-29 17:35 UTC
**Codewind version:** latest

**Che version:** 7.2.0
**IDE extension version:** latest
**Kubernetes cluster:** OCP 4.2

**Description:**
Autobuild is broken on master after the changes in https://github.com/eclipse/codewind-che-plugin/pull/93 were merged to use the codewind cli (cwctl) in the Che sidecar.

**Workaround:** 
Build manually?

**Comment by tobespc** [comment] 2019-10-30 08:45
We have put a fix in already to the cli to fix this (so make sure you have the latest).  But, you need to make sure that theia is calling the cwctl bind (rather than api/v1/bind) as that is the reason the build is not autobuilding.   When we bind a project, we set up a default connection.  There was a bug in the cli where it would break autobuild if this file was not found.  We have fixed that but still need theia to call cwctl bind

**Comment by tobespc** [comment] 2019-10-30 10:50
this is the same as #906

**Comment by tetchel** [comment] 2019-10-30 19:54
im going to close this as a dupe of 906

**Closed by tetchel** 2019-10-30 19:54 UTC
Labels: area/vscode-ide, kind/bug, priority/stopship, remote
