### ISSUE TITLE
Hybrid: no version in the result from the environment API

### ISSUE THREAD

**Issue by eharris369** [eclipse/codewind#1096] opened 2019-11-12 19:56 UTC
The IDE code checks the version of Codewind to make sure it is compatible but the output of api/v1/environment does not contain the version for the hybrid case:

{
  "running_in_k8s": true,
  "user_string": null,
  "socket_namespace": "/default",
  "workspace_location": "/projects",
  "os_platform": "Linux",
  "tekton_dashboard": {
    "status": false,
    "message": "not-installed",
    "url": ""
  }

**Comment by jopit** [comment] 2019-11-12 20:02
Not currently blocking, but still required for 0.7.0

**Comment by tobespc** [comment] 2019-11-13 09:41
Closing as a dupe of #578

**Closed by tobespc** 2019-11-13 09:41 UTC
Labels: area/portal, kind/bug
