### ISSUE TITLE
No meaningful error message if missing `oc adm policy` or `kube rolebinding` (permissions)

### ISSUE THREAD

**Issue by beccabau** [eclipse/codewind#115] opened 2019-08-06 19:29 UTC
**Codewind version:** latest (dev)
https://raw.githubusercontent.com/eclipse/codewind-che-plugin/master/devfiles/latest/devfile.yaml
**OS:** OKD

**Che version:** 4ef1d89
**IDE extension version:** 
**IDE version:** Eclipse Che
**Kubernetes cluster:** OKD

![image](https://user-images.githubusercontent.com/13971834/62570096-55a72f00-b85d-11e9-959a-ad342e943038.png)

**Description of the enhancement:** If the user misses a policy or user permission configuration, the CLI does not provide a clear explanation that it is missing (and the user might not realize), from this part of the process:
```
git clone https://github.com/eclipse/codewind-che-plugin.git
kubectl apply -f setup/install_che/codewind-clusterrole.yaml
kubectl apply -f setup/install_che/codewind-rolebinding.yaml
oc adm policy add-scc-to-group privileged system:serviceaccounts:eclipse-che
oc adm policy add-scc-to-group anyuid system:serviceaccounts:eclipse-che
```
For example, I missed one earlier during the install process (I think it was one of the oc adm policy configurations), and was getting weird timeout errors/crashLoopBackoff on one of the pods (and it was unclear where the problem was coming from).

```
scc "anyuid" added to groups: ["system:serviceaccounts:eclipse-che"]
[root@okd-rbau-master codewind-che-plugin]# k get pod
NAME                                                           READY     STATUS             RESTARTS   AGE
che-2-8wlhf                                                    1/1       Running            0          3h
workspace83rq6sa134rybe83.che-workspace-pod-85b5b94886-gdqfk   2/3       CrashLoopBackOff   6          7m
```

And upon further investigation:
```
[root@okd-rbau-master codewind-che-plugin]# k logs workspace82wlt4kuaey0x15g.che-workspace-pod-dd65c8f98-rpwgr -c theia-idec83
... normal behavior ...
root INFO [hosted-plugin: 42] [INFO: 15:10:16.261 CodewindManager.js:170]: Healthcheck failed Error: connect ECONNREFUSED 127.0.0.1:9090

root ERROR [hosted-plugin: 42] Task plugin webSocket: Reconnecting...

root ERROR [hosted-plugin: 42] Unable to create ws connection for task plugin. Cause: Error: Unexpected server response: 503

root ERROR [hosted-plugin: 42] Task plugin webSocket: Reconnecting in 1000ms due to 

root ERROR [hosted-plugin: 42] Task plugin webSocket: Reconnecting...

root ERROR [hosted-plugin: 42] Unable to create ws connection for task plugin. Cause: Error: Unexpected server response: 503

root ERROR [hosted-plugin: 42] Task plugin webSocket: Reconnecting in 1000ms due to 

root ERROR [hosted-plugin: 42] Task plugin webSocket: Reconnecting...

root INFO [hosted-plugin: 42] [DBUG: 15:10:20.265 CodewindManager.js:189]: Waiting for Codewind to start, 40s have elapsed

root INFO [hosted-plugin: 42] [INFO: 15:10:20.266 CodewindManager.js:170]: Healthcheck failed Error: connect ECONNREFUSED 127.0.0.1:9090

root INFO [hosted-plugin: 42] [DBUG: 15:10:24.271 CodewindManager.js:189]: Waiting for Codewind to start, 44s have elapsed
```

Follow that up with 
```
[root@okd-rbau-master codewind-che-plugin]# k describe pod workspacenlnbatc0p53agm59.che-workspace-pod-6fd4bbbfcb-hj28c 
...
Events:
  Type     Reason     Age                 From                       Message
  ----     ------     ----                ----                       -------
  Normal   Scheduled  1h                  default-scheduler          Successfully assigned eclipse-che/workspacenlnbatc0p53agm59.che-workspace-pod-6fd4bbbfcb-hj28c to okd-rbau-worker1
  Normal   Pulling    1h                  kubelet, okd-rbau-worker1  pulling image "eclipse/che-machine-exec"
  Normal   Pulled     1h                  kubelet, okd-rbau-worker1  Successfully pulled image "eclipse/che-machine-exec"
  Normal   Created    1h                  kubelet, okd-rbau-worker1  Created container
  Normal   Started    1h                  kubelet, okd-rbau-worker1  Started container
  Normal   Pulling    1h                  kubelet, okd-rbau-worker1  pulling image "eclipse/che-theia:7.0.0-rc-3.0"
  Normal   Started    1h                  kubelet, okd-rbau-worker1  Started container
  Normal   Created    1h                  kubelet, okd-rbau-worker1  Created container
  Normal   Pulled     1h                  kubelet, okd-rbau-worker1  Successfully pulled image "eclipse/che-theia:7.0.0-rc-3.0"
  Normal   Created    1h (x3 over 1h)     kubelet, okd-rbau-worker1  Created container
  Normal   Started    1h (x3 over 1h)     kubelet, okd-rbau-worker1  Started container
  Normal   Pulled     1h (x4 over 1h)     kubelet, okd-rbau-worker1  Successfully pulled image "ibmcom/codewind-che-sidecar:0.2"
  Normal   Pulling    1h (x4 over 1h)     kubelet, okd-rbau-worker1  pulling image "ibmcom/codewind-che-sidecar:0.2"
  Warning  BackOff    46s (x449 over 1h)  kubelet, okd-rbau-worker1  Back-off restarting failed container
```

Then investigate the che-sidecar container >
```
[root@okd-rbau-master ~]# k logs workspace83rq6sa134rybe83.che-workspace-pod-85b5b94886-gdqfk -c codewind-che-sidecart7h
Generating a RSA private key
.......................................................................++++
[root@okd-rbau-master ~]# k logs workspace83rq6sa134rybe83.che-workspace-pod-85b5b94886-gdqfk -c codewind-che-sidecart7h
Generating a RSA private key
.......................................................................++++
.................................................................................................................++++
writing new private key to '/etc/nginx/conf.d/key.pem'
-----
Checking for any OCP routes
Error from server (Forbidden): routes.route.openshift.io is forbidden: User "system:serviceaccount:eclipse-che:che-workspace" cannot list routes.route.openshift.io in the namespace "eclipse-che": no RBAC policy matched
Created an empty deployment status file.
Unable to find claim-che-workspace PVC, Che workspace running in shared namespace
Error from server (Forbidden): persistentvolumeclaims is forbidden: User "system:serviceaccount:eclipse-che:che-workspace" cannot list persistentvolumeclaims in the namespace "eclipse-che": no RBAC policy matched
error executing jsonpath "{.items[0].metadata.name}": Error executing template: array index out of bounds: index 0, length 0. Printing more information for debugging the template:
	template was:
		{.items[0].metadata.name}
	object given to jsonpath engine was:
		map[string]interface {}{"apiVersion":"v1", "items":[]interface {}{}, "kind":"List", "metadata":map[string]interface {}{"resourceVersion":"", "selfLink":""}}
```
And you finally see information about the RBAC policy. I simply readded all the above configurations again and was able to get my che workspace up and running.

 It would be nice to have a message that could identify this more easily in the UI (and maybe via a more persistent ribbon, since the ones shown in this screen shot disappear almost immediately).

![image](https://user-images.githubusercontent.com/13971834/62571240-e03c5e00-b85e-11e9-91fe-6bd5cd74340a.png)

**Proposed solution:** see above

**Comment by rajivnathan** [comment] 2019-08-07 13:15
We do some problem determination in the sidecar. 2 things we need to do:

1. Check to see whether this specific problem is being caught, and if not cover it.
2. Update the Codewind extension to expose the detected problems to the user.

@tetchel We should discuss how we want to do # 2.

**Comment by tetchel** [comment] 2019-08-07 14:48
The plugin hits the `/environment` API when it initializes. Could we put errors in that response? 

Can errors appear after PFE is already running? In that case, we would have to send them in socket events too.

**Comment by rajivnathan** [comment] 2019-08-08 14:58
The problem is that PFE may not be up. If the user/cluster admin (whoever set up Che for Codewind) has missed some configuration required for Che (eg. RBAC issues, etc.) then only the sidecar will be up in the Che workspace, no PFE. In this case the sidecar will serve up a simple json file with error details but we need a way to expose that to users so that they have specific information about the problems that they can use to resolve issues.

**Comment by tetchel** [comment] 2019-08-08 17:07
> Is /environment the first endpoint that the plugin hits?
Yes

**Comment by johnmcollier** [comment] 2019-08-08 19:05
@beccabau https://github.com/eclipse/codewind/issues/36 is also open to address this

**Comment by rajivnathan** [comment] 2019-08-09 13:45
I updated #36 to include a section on 'How to provide status to the user' with Tim's proposal to use `/environment`

> The plugin hits the `/environment` API when it initializes. Could we put errors in that response?
> 
> Can errors appear after PFE is already running? In that case, we would have to send them in socket events too.

@beccabau @johnmcollier Are we okay to close this one given that it'll be covered by #36 ?

**Comment by beccabau** [comment] 2019-08-09 13:54
Yep, I'm okay to close. Thanks!

**Closed** 2020-02-10 14:32 UTC
Labels: area/iterative-dev, kind/enhancement
