### ISSUE TITLE
[OCP4] [Hybrid] Cwctl install fails on OCP4, can't find keycloak pod

### ISSUE THREAD

**Issue by johnmcollier** [eclipse/codewind#1373] opened 2019-12-04 19:24 UTC
I'm trying to install Hybrid Codewind on OCP4 (on Fyre) using the following command:
```
oc adm policy add-scc-to-group anyuid system:serviceaccounts:codewind
oc adm policy add-scc-to-group privileged system:serviceaccounts:codewind

./cwctl --insecure install remote \
    --namespace codewind \
    --kadminuser admin \
    --kadminpass admin \
    --krealm codewind \
    --kclient codewind \
    --kdevuser developer \
    --kdevpass developer \
    --ingress <namespace>.apps.<cluster-name>.os.fyre.ibm.com
```

However the install fails with the following error:
```
INFO[0001] Waiting for pod: codewind-keycloak-k3ro4zwt  
INFO[0001] codewind-keycloak-k3ro4zwt, phase: Pending Unschedulable  
INFO[0006] codewind-keycloak-k3ro4zwt, phase: Pending ContainersNotReady  
INFO[0025] codewind-keycloak-k3ro4zwt, phase: Pending ContainersNotReady  
ERRO[0085] Expected a Pod but found: <nil>              
```
Despite the errors, the Keycloak pod is up and running fine, without issue, so something else must be causing the check [here](https://github.com/eclipse/codewind-installer/blob/master/pkg/remote/util.go#L261) to fail

**Comment by johnmcollier** [comment] 2019-12-04 19:25
Both @makandre and I have seen this intermittently. There doesn't seem to be a sure-fire way to reproduce it, perhaps it's a timing issue? What's the timeout on the waitForPods function?

**Comment by tetchel** [comment] 2019-12-05 18:01
Just saw this too with the performance pod

**Comment by hhellyer** [comment] 2020-01-10 10:55
It looks like it was the watch on the pod timing out because the pull took too long, that would explain the <nil> value returned from the `Watch()` calls channel. (I could also reproduce that by explicitly setting a very short timeout.)

I've pushed a fix for this so we handle the watch for the pod timing out better. If you retest you should see cwctl wait for the pod to start, and warn that it is doing so.

**Comment by markcor11** [comment] 2020-01-16 11:06
example output : 

```
INFO[0036] Creating and setting Codewind PVC codewind-pfe-pvc-k5gmirtt to 1Gi  
INFO[0036] Deploying Codewind Service  
INFO[0036] Waiting for pod: codewind-pfe-k5gmirtt       
INFO[0036] codewind-pfe-k5gmirtt, phase: Pending Unschedulable  
WARN[0066] Watch for Pod codewind-pfe-k5gmirtt ended. Timeout or connection error. 
INFO[0066] Waiting for pod: codewind-pfe-k5gmirtt       
INFO[0066] codewind-pfe-k5gmirtt, phase: Pending Unschedulable  
WARN[0096] Watch for Pod codewind-pfe-k5gmirtt ended. Timeout or connection error. 
INFO[0096] Waiting for pod: codewind-pfe-k5gmirtt       
INFO[0096] codewind-pfe-k5gmirtt, phase: Pending Unschedulable  
WARN[0126] Watch for Pod codewind-pfe-k5gmirtt ended. Timeout or connection error. 
INFO[0126] Waiting for pod: codewind-pfe-k5gmirtt       
INFO[0126] codewind-pfe-k5gmirtt, phase: Pending Unschedulable  
INFO[0152] codewind-pfe-k5gmirtt, phase: Pending ContainersNotReady  
INFO[0155] codewind-pfe-k5gmirtt, phase: Running        
```

**Comment by jagraj** [comment] 2020-01-16 14:04
I am also getting into this issue, when I try to install remote codewind. 

```
time="2020-01-15T16:27:12-05:00" level=info msg="Checking namespace codewind exists\n"
time="2020-01-15T16:27:12-05:00" level=info msg="Creating codewind namespace\n"
time="2020-01-15T16:27:12-05:00" level=info msg="Using namespace : codewind\n"
time="2020-01-15T16:27:12-05:00" level=info msg="Container images : "
time="2020-01-15T16:27:12-05:00" level=info msg="eclipse/codewind-pfe-amd64:0.8.0"
time="2020-01-15T16:27:12-05:00" level=info msg="eclipse/codewind-performance-amd64:0.8.0"
time="2020-01-15T16:27:12-05:00" level=info msg="eclipse/codewind-keycloak-amd64:0.8.0"
time="2020-01-15T16:27:12-05:00" level=info msg="eclipse/codewind-gatekeeper-amd64:0.8.0"
time="2020-01-15T16:27:13-05:00" level=info msg="Running on openshift: true\n"
time="2020-01-15T16:27:13-05:00" level=info msg="Using ingress domain: apps.leith.os.fyre.ibm.com\n"
time="2020-01-15T16:27:13-05:00" level=info msg="Creating service account definition 'codewind-k5ftftf5'"
time="2020-01-15T16:27:13-05:00" level=info msg="Creating service account definition 'keycloak-k5ftftf5'"
time="2020-01-15T16:27:13-05:00" level=info msg="Creating codewind-keycloak-k5ftftf5.apps.leith.os.fyre.ibm.com server Key"
time="2020-01-15T16:27:13-05:00" level=info msg="Creating codewind-keycloak-k5ftftf5.apps.leith.os.fyre.ibm.com server certificate"
time="2020-01-15T16:27:13-05:00" level=info msg="Creating Codewind Keycloak PVC"
time="2020-01-15T16:27:13-05:00" level=info msg="Deploying Codewind Keycloak Secrets"
time="2020-01-15T16:27:13-05:00" level=info msg="Deploying Codewind Keycloak TLS Secrets"
time="2020-01-15T16:27:13-05:00" level=info msg="Waiting for pod: codewind-keycloak-k5ftftf5"
time="2020-01-15T16:27:14-05:00" level=info msg="codewind-keycloak-k5ftftf5, phase: Pending  \n"
time="2020-01-15T16:27:14-05:00" level=info msg="codewind-keycloak-k5ftftf5, phase: Pending ContainersNotReady \n"
time="2020-01-15T16:28:14-05:00" level=error msg="Expected a Pod but found: <nil>\n"
```

**Comment by hhellyer** [comment] 2020-01-16 14:46
@jagraj - What level of cwctl are you using? Since my change I wasn't expecting to see `Expected a Pod but found: <nil>` as we should catch the case where the returned object is `nil`.

**Comment by hhellyer** [comment] 2020-01-16 14:50
The last two messages have exactly a minute apart, which suggests a timeout, the fix I put in should have retried on timeouts. Could you check you are using the latest cwctl? Was this on 0.8.0 or master?

**Comment by jagraj** [comment] 2020-01-16 15:51
I installed eclipse 0.8.0 plugin yesterday afternoon. 

```
 .\cwctl.exe --version
cwctl version 0.8.0
```

**Comment by jagraj** [comment] 2020-01-16 15:52
```
    Directory: C:\Users\Administrator\.codewind\0.8.0


Mode                LastWriteTime         Length Name
----                -------------         ------ ----
-a----        1/15/2020   1:58 PM       26881024 appsody.exe
-a----        1/15/2020   1:58 PM       36922368 cwctl.exe
```

**Comment by malincoln** [comment] 2020-01-27 14:45
@jagraj are you still seeing issues or is this now resolved?

**Comment by jagraj** [comment] 2020-01-30 21:11
@malincoln @johnmcollier 
I do not see this problem, but I get into other problem after following our docs for remote codewind install and I opened this issue (https://github.com/eclipse/codewind/issues/1954) to track this.  Once we fix docs or CLI to install remote codewind then we are good.  Looks like John opened this issue are you ok to close this issue.?

**Closed** 2020-02-06 03:05 UTC
Labels: area/portal, kind/bug, priority/hot
