### ISSUE TITLE
new microprofile application - Could not determine application URL message

### ISSUE THREAD

**Issue by AndyRWatson** [eclipse/codewind#720] opened 2019-10-17 14:33 UTC
**Codewind version:**.  0.4
**OS:**. MacOS 10.15 (Catalina)

**Che version:**
**IDE extension version:**
**IDE version:**
**Kubernetes cluster:**

**Description:**

While trying to reproduce https://github.com/eclipse/codewind/issues/611#issuecomment-543063646.  on my newly installed machine I tried to also create a micro profile application.

Though all appears to have built,   the application URL is not available in my vs code application view and clicking on the open application results in 

> Could not determine application URL for myliberty.

I have looked at the docker ps output and can see that the container is running and an exposed port.

observations

- docker ps output showed container running and app on port 32772
- application is running when referencing from browser http://127.0.0.1:32772.   (unlike the node app which does not work from 127.0.0.1:32769)
- docker logs when viewed from codewind/vscode looks to have built ok
- docker logs for app seems to show a different url address ? (See image)

<img width="1680" alt="Screenshot 2019-10-17 at 15 12 58" src="https://user-images.githubusercontent.com/9268814/67018556-51b44a80-f0f3-11e9-8bb1-da3e8b594c26.png">

**Steps to reproduce:**

Create new microprofile application in viscose
**Workaround:**

**Comment by AndyRWatson** [comment] 2019-10-17 16:51
I have restarted my vscode and all now seems to work against the same running project/container.   Could be a timing issue or maybe resolved with a projects refresh (?)

**Comment by jopit** [comment] 2019-10-17 17:34
Could you find and upload the extension's logs as described in the [Troubleshooting](https://www.eclipse.org/codewind/mdt-vsc-troubleshooting.html) section?

**Comment by AndyRWatson** [comment] 2019-10-17 22:06
I can reproduce this also on another machine (as has @markcor11 )

<img width="1409" alt="Screenshot 2019-10-17 at 23 02 44" src="https://user-images.githubusercontent.com/9268814/67051187-5ba96e00-f132-11e9-865f-b24f2ced8cae.png">
[filewatcherd-1.log](https://github.com/eclipse/codewind/files/3741470/filewatcherd-1.log)
[codewind.log](https://github.com/eclipse/codewind/files/3741471/codewind.log)

**Comment by AndyRWatson** [comment] 2019-10-17 22:44
I reproduced again on a second project.   I waited a few seconds and hit project refresh and still the same.    I then waited around 30 seconds and did project refresh again and it then works as expected !

**Comment by jopit** [comment] 2019-10-18 13:21
Marked stop-ship at Marylin's request.  @tetchel can you please investigate.

**Comment by AndyRWatson** [comment] 2019-10-18 14:19
uploading application .inf file for reference

**Comment by tetchel** [comment] 2019-10-18 14:56
for some reason the app port was never passed to the IDE, though i can see it there in the .inf, do you have pfe logs?

**Comment by tetchel** [comment] 2019-10-18 15:37
I can reproduce this, for some reason all the `projectChanged` events are missing the port information, but they are there in the `projectCreation` event, which is bizarre.

**Comment by tetchel** [comment] 2019-10-18 15:40
the container ID is also missing from the projectChanged events

**Comment by tetchel** [comment] 2019-10-18 15:58
@makandre i think this is the same as your issue. i think it is a timing issue and likely happening with microprofile because it has by far the slowest container build.

**Comment by tetchel** [comment] 2019-10-18 17:20
I can work around this in the frontend, but I opened #720

**Comment by tetchel** [comment] 2019-10-18 17:29
however in the logs above you can see there is an 11s period where the app is started but there are no ports or container ID

**Comment by naveenkaratekid** [comment] 2019-10-18 17:50
I am able to reproduce the error when I try to run the application:

![webshpere liberty app url error](https://user-images.githubusercontent.com/19738071/67116279-188ce080-f1ae-11e9-96ad-16c5b319bca7.PNG)

**Comment by eharris369** [comment] 2019-10-18 18:51
I see this in Eclipse as well when I am on a fast machine (not my Windows machine).  The application goes into started state but it takes several seconds before the actual ports are updated in the overview page.  The PFE logs show the projectCreation event occurs 3s after the app goes into started state.

**Comment by makandre** [comment] 2019-10-19 01:38
Is there a fix on eclipse side as well?

**Comment by eharris369** [comment] 2019-10-21 13:07
On the eclipse side it already handles it because when it gets any update it does a full refresh.  So it shows the delay in getting the URL which can't be avoided but it never got stuck in starting state.

**Comment by jagraj** [comment] 2019-10-21 14:14
SVT team verifying this issue with the latest plugin and images. Here is the result from Sujeily..

```I no longer see the problem with the Standard MicroProfile endpoint UPR (#720) and I could not notice any delay in the application information population, using the latest images of Codewind 0.5.0 on Windows 10 and MacOS.```

Naveen and David also in the process of verifying with the latest.

**Comment by jagraj** [comment] 2019-10-21 15:53
More updates on this issue. With the latest plugin and images this issue has been fixed, David and Naveen's tests also ran successfully. We no longer see this problem. 

Thanks for the fix.

**Comment by tetchel** [comment] 2019-10-21 17:37
okay, #747 will improve this behaviour further, but I think we can close this for 0.5

**Closed by tetchel** 2019-10-21 17:37 UTC
Labels: area/iterative-dev, area/vscode-ide, kind/bug, priority/stopship
