### ISSUE TITLE
DELETE /api/v1/imagepushregistry should also remove the image push registry when user deletes from the UI

### ISSUE THREAD

**Issue by maysunfaisal** [eclipse/codewind#1440] opened 2019-12-09 18:45 UTC
**Codewind version:**
**OS:**

**Che version:**
**IDE extension version:**
**IDE version:**
**Kubernetes cluster:**

**Description:**
Should delete the imagepushregistry defined at `/codewind-workspace/.config/settings.json`

**Comment by rajivnathan** [comment] 2020-01-21 19:22
Closing this as a dupe of https://github.com/eclipse/codewind/issues/1746

**Closed by rajivnathan** 2020-01-21 19:22 UTC
Labels: area/iterative-dev, kind/bug
