### ISSUE TITLE
SVT: Eclipse : Windows : problem opening microprofile app view.

### ISSUE THREAD

**Issue by mmulholl** [eclipse/codewind#1552] opened 2019-12-16 18:45 UTC
**Codewind version:**   Codewind tech preview	0.7.0.v201912132118	
**OS:** Windows

**Che version:**
**IDE extension version:**
**IDE version:** 
Eclipse IDE for Enterprise Java Developers.
Version: 2019-09 R (4.13.0)
Build id: 20190917-1200
**Kubernetes cluster:**

**Description:**

After creating a WebSphere Liberty Microprofile application I try to open the application view a get this:

<img width="829" alt="Screen Shot 2019-12-16 at 1 36 26 PM" src="https://user-images.githubusercontent.com/16086270/70933624-50779f00-200a-11ea-89ae-e69c21e2fc75.png">

**Steps to reproduce:**

**Workaround:**

**Comment by jopit** [comment] 2019-12-16 19:01
This is a limitation of Eclipse's internal browser on windows -- see https://github.com/eclipse/codewind-eclipse/issues/126, particularly comment https://github.com/eclipse/codewind-eclipse/issues/126#issuecomment-506489535

**Comment by eharris369** [comment] 2020-01-07 14:31
This is a duplicate of https://github.com/eclipse/codewind/issues/438.

**Closed by eharris369** 2020-01-07 14:31 UTC
Labels: duplicate, kind/bug
