### ISSUE TITLE
'Cannot read property of concat' TypeError in Codewind server logs during MicroProfile project creation

### ISSUE THREAD

**Issue by jgwest** [eclipse/codewind#134] opened 2019-08-08 17:48 UTC
**Versions and OS:**
Tested on Windows, using Codewind and Codewind Eclipse built from a couple days old master branch.

**Description of the bug:**

When creating a new Microprofile project, on local Codewind, I am seeing the below concat error repeated every X seconds, in the logs. It goes away once the Liberty app has started.

```
[08/08/19 17:30:26 codewind-rogue-cloud-client] [ERROR] Failed to get logs for project 2f229fd0-ba02-11e9-badc-6fc83176b648
[08/08/19 17:30:26 codewind-rogue-cloud-client] [ERROR] TypeError: Cannot read property 'concat' of undefined
    at Object.getAppLog (/file-watcher/server/dist/projects/libertyProject.js:247:46)
    at process._tickCallback (internal/process/next_tick.js:68:7)
```
Rajiv mentioned to look at these lines in `libertyProject.ts` (and likely other project types)
https://github.com/eclipse/codewind/blob/2940d062a301848620c8984a18688280cb0c68e6/src/pfe/file-watcher/server/src/projects/libertyProject.ts#L278
and
https://github.com/eclipse/codewind/blob/2940d062a301848620c8984a18688280cb0c68e6/src/pfe/file-watcher/server/src/projects/libertyProject.ts#L285

**Steps to reproduce**:
1. In Eclipse Codewind, using local Codewind install, create a new Microprofile project. 
2. `docker tail -f (container id)` the PFE container, you should see the above TypeError.

**Comment by jgwest** [comment] 2019-08-08 17:49
PFE log:
[codewind-pfe-log.txt](https://github.com/eclipse/codewind/files/3483038/codewind-pfe-log.txt)

**Comment by ssh24** [comment] 2019-08-08 18:08
@jgwest Is this happening on windows only?

**Comment by jgwest** [comment] 2019-08-08 18:37
@ssh24 Not sure, have only tested on Windows.

**Comment by ssh24** [comment] 2019-08-12 14:22
@jgwest Still trying to find the root cause of the problem. Do you have the PFE logs by any chance?

**Comment by jgwest** [comment] 2019-08-13 13:53
@ssh24  Do the ones I posted above count?

**Comment by rajivnathan** [comment] 2019-09-05 19:56
@jgwest can you please verify whether this is now fixed?

**Comment by jgwest** [comment] 2019-09-10 15:46
Confirmed as fixed, thanks @ssh24 !

**Closed** 2019-09-10 15:46 UTC
Labels: area/iterative-dev, kind/bug
