### ISSUE TITLE
Unable to remove project from cloud connection in vscode-ide

### ISSUE THREAD

**Issue by tobespc** [eclipse/codewind#2561] opened 2020-03-30 07:06 UTC
**Codewind version:**
master
**OS:**
mac

**Description:**
I have manage to get my IDE into a state where I don't have a connection object for the the project I want to delete and as such, I can't now remove it from my list of projects in the IDE.  I get the following error when I try to remove it 

![Screenshot 2020-03-30 at 08 03 49](https://user-images.githubusercontent.com/13151286/77884600-48600a00-725d-11ea-86f2-f07022936e38.png)

So if CWCTL is unable to remove the connection (as its not there), what should the IDE do ?

**Comment by tetchel** [comment] 2020-03-30 14:16
I don't know what the IDE could do in this situation. How did you get into this state? It seems more like a cwctl bug to have a project tied to a non-existent connection

**Comment by tobespc** [comment] 2020-03-31 13:17
I don't how I got to the state of the connection object going but, given that it did, from an IDE perspective there seems to be no way to remove the project from the workspace.

**Comment by tetchel** [comment] 2020-03-31 13:19
Does the connection shows in the codewind explorer, even if you restart vs code?

**Comment by tetchel** [comment] 2020-04-06 14:29
@tobespc do you have more info or steps to reproduce?

**Comment by tobespc** [comment] 2020-04-07 08:46
I'll try a reproduce

**Comment by tetchel** [comment] 2020-04-30 16:10
have you seen this in the last month?

**Comment by tetchel** [comment] 2020-05-05 18:41
closing because we can't repro

**Closed by tetchel** 2020-05-05 18:41 UTC
Labels: area/vscode-ide, kind/bug
