### ISSUE TITLE
SVT : Eclipse : Mac : Did codewind just crash?

### ISSUE THREAD

**Issue by mmulholl** [eclipse/codewind#1828] opened 2020-01-21 16:12 UTC
**Codewind version:**  Codewind tech preview	0.8.0.v202001202137	
**OS:** Mac

**Che version:**
**IDE extension version:**
**IDE version:** Eclipse jee 2019-09
**Kubernetes cluster:**

**Description:**
Was running codewend had a few projects created and was just waiting on my new node project to be running when suddenly all projects disappeared from my list and a short time later:

<img width="662" alt="Screen Shot 2020-01-21 at 11 07 52 AM" src="https://user-images.githubusercontent.com/16086270/72821454-84179b80-3c3e-11ea-9e07-9fec17847608.png">

Hitting refresh has no effect.

pfe log: 
[pfe.log](https://github.com/eclipse/codewind/files/4092009/pfe.log)
 
workspace log:
[workspace.log](https://github.com/eclipse/codewind/files/4092018/workspace.log)

docker ps is slow but returns this:
[dockerps.log](https://github.com/eclipse/codewind/files/4092041/dockerps.log)

**Steps to reproduce:**

**Workaround:**

**Comment by mmulholl** [comment] 2020-01-21 16:20
As refresh does not work and codewind docker containers apparantley running my only option is to restart docker, which is not great. Guess I could have just stopped the containers.

**Comment by tetchel** [comment] 2020-01-21 16:38
pfe looks ok so tagged with eclipse, not sure what caused the socket timeout

**Comment by eharris369** [comment] 2020-01-23 18:42
Looking at the Eclipse .log file - it is trying to update the logs and metricsAvailable after a projectStatusChanged event.  Both of these time out even though for http requests the connect timeout is 10s and the read timeout is 10s.  After this it assumes that the connection is lost and tries to reconnect.  It is calling api/v1/ready but this times out as well.  It has a 5s timeout.

**Comment by eharris369** [comment] 2020-01-23 18:48
I also noticed at the end of the pfe log that 6 applications go to started state and then less than a minute later 3 of them go to stopped state for no apparent reason.

**Comment by eharris369** [comment] 2020-01-23 19:29
@mmulholl Given the above I think what happened is that docker was having trouble. I have seen this happen on Windows several times. It looks like docker is really slow but otherwise ok however it is not. Are you ok with closing this for now and re-opening if it happens again?

**Comment by eharris369** [comment] 2020-03-03 20:59
Closing as this is not reproducible. Please re-open if you run into this again.

**Closed by eharris369** 2020-03-03 20:59 UTC
Labels: area/eclipse-ide, kind/bug
