### ISSUE TITLE
(metrics) SVT : Eclipse : Mac : AppsodyOpenLiberty application metrics option messed up

### ISSUE THREAD

**Issue by mmulholl** [eclipse/codewind#1804] opened 2020-01-17 21:31 UTC
**Codewind version:**  Codewind tech preview	0.8.0.v202001161954
**OS:**Mac

**Che version:**
**IDE extension version:**
**IDE version:** Eclispse
**Kubernetes cluster:**

**Description:**

application monitor selection fails first time, works the second time.

**Steps to reproduce:**
1. Create an Appsody Open Liberty app and wait for it to be runnuing.
2. Right click on the project and select "application monitor", note performance dashboard is also an option.
3. The window which appears shows: Error 404: java.io.FileNotFoundException: SRVE0190E: File not found: /javametrics-dash/
4. Right click on the project, the  performance dashboard option is no longer available. 
5. Click on application metrics again and this time it works.

**Workaround:**

**Comment by tobespc** [comment] 2020-01-20 09:56
The appsodyOpenLiberty stack has been modified to no longer pull in javametrics-dash but instead just use microprofile metrics instead.

We should only get the dashboard appearing as displayed from the performance container (which I can see is whats happeneing).   Suspect there is a mismatch in timing logic but I don't believe this to be stop ship

**Comment by hhellyer** [comment] 2020-01-20 13:58
This looks like an interaction between the implementations of `openPerformanceDashboard()` and `openAppMonitorCmd()`, see:

https://github.com/eclipse/codewind-vscode/blob/0.8.0/dev/src/command/project/OpenPerfDashboard.ts#L23
and 
https://github.com/eclipse/codewind-vscode/blob/0.8.0/dev/src/command/project/OpenAppMonitor.ts#L19

When `Application Monitor` is selected `openAppMonitorCmd()` is called, it then calls the getter function appMonitorUrl(): https://github.com/eclipse/codewind-vscode/blob/0.8.0/dev/src/codewind/project/Project.ts#L619

This checks `metricsAvailable` which initially for the Appsody Open Liberty app is set to true. At this point you can use the `Application Monitor` menu option as many times as you like, it will open a non-existent page.

When you choose `Performance Dashboard` it calls `openPerformanceDashboard()` which calls `testPingAppMonitor()` - this call fails and a warning is displayed but `testPingAppMonitor()` sets `_metricsAvailable`: https://github.com/eclipse/codewind-vscode/blob/0.8.0/dev/src/codewind/project/Project.ts#L819

After this is set to false `appMonitorUrl()` drops down to it's second case and returns the correct url:
https://github.com/eclipse/codewind-vscode/blob/0.8.0/dev/src/codewind/project/Project.ts#L635

I'm not sure of all the history around these two commands but this looks like a bug in the vscode plugin (I assume it doesn't happen in the Eclipse plugin), I'll transfer it to area/vscode-ide as they probably understand why we have these two commands and especially the history of `openPerformanceDashboard()` and `testPingAppMonitor()`.

**Comment by eharris369** [comment] 2020-01-20 14:22
The same problem occurs in Eclipse (the issue was originally opened in Eclipse). The same person did the code changes for both VSCode and Eclipse so they have the same logic.

**Comment by mmulholl** [comment] 2020-01-20 14:39
If the fix is complex and risky I am OK to remove stop/ship.

**Comment by hhellyer** [comment] 2020-01-20 14:50
A menu item which should work doesn't work until the user tries a menu option which doesn't work and then tries the option that should work again.

We should fix this. ;-)

**Comment by tetchel** [comment] 2020-01-20 16:10
The problem is that /api/v1/projects/<id>/metrics reports `metricsAvailable` as `true` for appsody all the time, that's why we have the ping test. since injection was added this logic is all over the place. 

what is supposed to work with openliberty, the app monitor or the dashboard or both?

**Comment by tetchel** [comment] 2020-01-20 16:23
the IDEs do not have a way to tell the appsody openliberty project from any other appsody java project, also how should normal openliberty behave?

**Comment by jopit** [comment] 2020-01-20 17:00
So the root cause of this specific problem is number 1 in https://github.com/eclipse/codewind/issues/1804#issuecomment-576345322, where PFE reports that user installed metrics  are available when they're actually not?

**Comment by tetchel** [comment] 2020-01-20 17:06
yes, see #237, it's always been like that for appsody but was worked around by number 2, pinging the dash endpoint #258

**Comment by jopit** [comment] 2020-01-20 18:24
Is there anything we can do in the IDEs for 0.8.0, or do we need to wait for #1815?

**Comment by eharris369** [comment] 2020-01-20 19:03
I am trying some things but am worried about breaking other things.  It would be nice if there was a itemized list of what to do based on the various values of:
    alwaysHasAppMonitor (true when language is java or nodejs)
    metricsAvailable
    injectMetrics
    result of trying to ping the metrics URL

**Comment by malincoln** [comment] 2020-01-21 15:46
agreed to fix as enhancement for 0.9.0

**Comment by malincoln** [comment] 2020-01-21 16:24
@tobespc you can reassign and remove other areas if needed.  Thanks

**Comment by malincoln** [comment] 2020-02-04 16:21
@tobespc assigning to you for now

**Comment by malincoln** [comment] 2020-02-07 16:36
@tobespc is working via https://github.com/eclipse/codewind/issues/1815

**Comment by malincoln** [comment] 2020-02-07 20:00
waiting for 1815 to be merged.

**Comment by rwalle61** [comment] 2020-02-11 09:10
1815 makes PFE provide the IDEs with more metrics information. However, as Tim says there is currently no way to differentiate an appsody java project from an appsody open liberty project. So another way to know which metrics endpoints a project has is to live ping them, as the IDEs do currently. 

I suggest making PFE do this ping instead, so that PFE decides all the metrics behaviour in one place

**Comment by tetchel** [comment] 2020-02-11 16:38
I suggest moving this issue to verify because the original problem of the messed up OpenLiberty menu should be fixed. The menu should no longer appear at all for Appsody OL. 

Then we can use a separate issue to add metrics support to Appsody OL.

**Comment by malincoln** [comment] 2020-02-12 14:17
@tobespc to follow-up on the remaining pieces and will update defect with more info.

**Comment by rwalle61** [comment] 2020-02-13 13:56
fyi we have an issue opne to be able to detect open liberty projects https://github.com/eclipse/codewind/issues/1960, which will help whatever's left we need to do on this

**Comment by malincoln** [comment] 2020-02-17 14:15
@tobespc since we have 1960 opened for the follow-on work, can this one be closed?

**Comment by malincoln** [comment] 2020-02-18 18:52
@mmulholl pls verify and close. Thanks

**Comment by malincoln** [comment] 2020-02-24 21:15
@mmulholl pls verify and close. Thanks

**Comment by mmulholl** [comment] 2020-03-02 22:06
So I still see app metrics listed as an option, I select it and get a message pop-up to say it is not supported and then the option disappears.

**Comment by eharris369** [comment] 2020-03-03 20:56
This is expected behaviour for Eclipse IDE. If it tries to ping the app metrics when it is bringing up the menu the menu will be too slow. Instead, the first time the user tries to use the app metrics it pings and if it fails it will disable that menu item in the future. The fix is for portal to do the ping (or something) to give the IDEs the correct setting for the menu item up front. I think this is going to be covered in #1960.

**Comment by scottkurz** [comment] 2020-03-05 16:29
Reading through this issue and a couple others, I was expecting to see the observation that we introduced the MP metrics endpoint in the **java-openliberty** stack protected by authentication.

Is this being tracked somewhere already?    If not we have to decide how to address this.   

E.g. one way would be to have Codewind implement the logic reading the password from the default location (see [here](https://github.com/appsody/stacks/tree/master/incubator/java-openliberty#metrics-password)).   

Not sure how far this needs to generalize or what thought or support has been done for this type of scenario, so please let me know how we should track this (otherwise I'll just open a new issue in this repo).   Thanks

**Comment by malincoln** [comment] 2020-03-20 13:39
@tobespc @hhellyer  ^^^

**Comment by makandre** [comment] 2020-04-17 17:49
Adding tech-topic label to discuss how we can address @scottkurz https://github.com/eclipse/codewind/issues/1804#issuecomment-595320738 above

/label tech-topic

**Comment by tobespc** [comment] 2020-04-27 08:41
closing as this is being continued in #2712

**Closed by tobespc** 2020-04-27 08:41 UTC
Labels: area/appsody, area/eclipse-ide, area/portal, area/vscode-ide, kind/bug, priority/hot
