### ISSUE TITLE
Eclipse Panel help linked to default help

### ISSUE THREAD

**Issue by mattcolegate** [eclipse/codewind#785] opened 2019-10-22 10:50 UTC
**Codewind version:** latest hybrid
**OS:** Windows 10

**Che version:** N/A
**IDE extension version:** 0.5.0v201910171920
**IDE version:** 2019-06
**Kubernetes cluster:** N/A

**Description:** Pressing the ? icon to open the help on the following panels opens the help to the default Workbench Window help, which is not helpful.
- Manage Template Sources
- Add Template Source

**Steps to reproduce:** Navigate to the above panels and press the ? icon in the bottom left of the panel (or press F1).

**Workaround:** N/A

**Comment by eharris369** [comment] 2019-10-22 13:16
This is a duplicate of #773

**Closed by eharris369** 2019-10-22 13:16 UTC
Labels: duplicate, kind/bug
