### ISSUE TITLE
[Filewatcherd] Event loop exception in WatchedPath

### ISSUE THREAD

**Issue by keithchong** [eclipse/codewind#2726] opened 2020-04-21 17:00 UTC
**Codewind version:** latest
**OS:** Mac

**IDE extension version:** IntelliJ latest
**IDE version:** 2019.3.3 Community Edition
**Kubernetes cluster:** local

**Description:**
Getting an NPE from filewatcher:

```
Apr. 21 12:01:45.176 p.m. [553.304] !!! SEVERE !!! Unexpected event loop exception in WatchedPath java.lang.NullPointerException
	at java.base/sun.nio.fs.UnixPath.toUnixPath(UnixPath.java:196)
	at java.base/sun.nio.fs.UnixPath.resolve(UnixPath.java:410)
	at java.base/sun.nio.fs.UnixPath.resolve(UnixPath.java:43)
	at org.eclipse.codewind.filewatchers.JavaNioWatchService$WatchedPath.eventLoop(JavaNioWatchService.java:378)
	at org.eclipse.codewind.filewatchers.JavaNioWatchService$WatchedPath.eventLoopCatchAll(JavaNioWatchService.java:337)
	at org.eclipse.codewind.filewatchers.JavaNioWatchService$WatchedPath.access$200(JavaNioWatchService.java:206)
	at org.eclipse.codewind.filewatchers.JavaNioWatchService$WatchedPathThread.run(JavaNioWatchService.java:185)

```

**Steps to reproduce:**
I don't have any steps to reproduce but at the time, I created a Codewind Open Liberty project and showed the logs.  I cannot reproduce this NPE after repeating these steps.

**Comment by jgwest** [comment] 2020-04-21 17:06
Looks like the Java NIO Watch Service API may return a null in rare cases (the documentation does note this in `@returns` but [the Oracle  example code](https://docs.oracle.com/javase/tutorial/essential/io/notification.html) doesn't actually check it :P )

**Comment by jgwest** [comment] 2020-05-11 19:49
This should be fixed by the merged PR, but I'm closing this rather than asking Keith to verify, since it's intermittent and there are no reproduction steps (but feel free to reopen if it occurs).

**Closed by jgwest** 2020-05-11 19:49 UTC
Labels: area/iterative-dev, kind/bug
