### ISSUE TITLE
[Che] TS filewatcher in Theia triggering rebuild upon browser refresh

### ISSUE THREAD

**Issue by johnmcollier** [eclipse/codewind#1293] opened 2019-11-27 17:39 UTC
I've got a Che devfile with the Go filewatcher removed and replaced with the TS filewatcher in the Theia extension [here](https://raw.githubusercontent.com/johnmcollier/devfiles/master/codewind/tsfw.yaml).

I'm finding that whenever the browser is refreshed and Theia gets reloaded, the TS filewatcher kicks off a new `cwctl sync`. According to @jgwest this is expected, as the filewatcher is getting reinitialized again. However, this is causing PFE to do a full rebuild of the project as it's passing it a timestamp of `-t 0`:

The following is logged each time the browser is reloaded
```
[November 27, 17:15:19.313] [2.660] Path '/projects/gogogotest' added to WatchService for d23179c0-1138-11ea-ab63-652df5ddf7f9
[November 27, 17:15:19.320] [2.667] Added new project with path '/projects/gogogotest' to watch list, with watch directory: '/projects/gogogotest'
[November 27, 17:15:19.321] [2.668] HttpGetStatus - GET request loop complete.
[November 27, 17:15:19.357] [2.704] Initial scan of '/projects/gogogotest' complete. Ready for changes
[November 27, 17:15:19.359] [2.706] Calling cwctl project sync with: { [project] [sync] [-p] [/projects/gogogotest] [-i] [d23179c0-1138-11ea-ab63-652df5ddf7f9] [-t] [0] }
[November 27, 17:15:19.366] [2.713] Issuing PUT request to 'https://localhost:9090/api/v1/projects/d23179c0-1138-11ea-ab63-652df5ddf7f9/file-changes/09a2f5b5bc6b445127c3c8ac157f05cd/status?clientUuid=f2364f13ef1a701b7f372567b5074594' for d23179c0-1138-11ea-ab63-652df5ddf7f9
[November 27, 17:15:19.865] [3.212] Successfully ran installer command: [project] [sync] [-p] [/projects/gogogotest] [-i] [d23179c0-1138-11ea-ab63-652df5ddf7f9] [-t] [0] 
[November 27, 17:15:19.867] [3.214] Output:
[November 27, 17:15:19.868] [3.215] Updating timestamp to latest: 1574874919360
```

How can we handle this (on either the Portal or Filewatcher side) such that:
- We can use the TS filewatcher in the Theia extension
- A browser refresh doesn't trigger a full rebuild

**Comment by jgwest** [comment] 2019-11-27 18:28
On IDE startup, when FWd is first told to watch a directory, FWd is calling `cwctl project sync` in order to inform cwctl that the directory exists (which will, for example, ensure that any file changes made outside the IDE are kept in sync). We do this with timestamp (`-t`) 0 because we don't have (and have not received) another timestamp value to use here (since the IDE has restarted.)

If y'all (@tobespc et al) would like another timestamp value to be used here, let us know, and if so where to get it.

#### Some ideas for how to handle this issue:
A) `cwctl project sync` keeps track of when it last ran (`projectLastSyncTime`, thus ignoring `-t` param). BUT, cwctl is (last I heard) meant to be stateless, and this would mean introducing state. (FWIW filewatcherd will ensure that only one instance of `project sync` is running at a time, thus making it safe to persist state, at least when invoked by FWd)
or
B) `cwctl project sync` switches to use a non-timestamp based algorithm (eg similar to rsync)
or
C) Filewatcher could persist the previous (`-t` value). But filewatcher is ALSO stateless, and it seems odd for filewatcher to manage someone else's state :P.
or
D) Filewatcher could instead NOT call `project sync` when it is first told to watch a directory, e.g. fwd could instead wait until the first file change event is received (but I think this will break other scenarios like bind, which we would then need to make changes to handle)
or
E) Just deal with Theia rebuilding too often
or 
F) Filewatch
or
E) Other options?

**Comment by deboer-tim** [comment] 2019-12-05 15:04
Discussed at tech topics (without UK team). The problem in Theia is similar to restarting an IDE locally; although it's worse in Theia solving this problem will ideally make it possible to close and reopen your local IDE without a full rebuild as well.

Leaning towards cwctl storing the timestamp and passing it back to FW, possibly storing it in the project info file. John C will talk to UK team, if they disagree we'll discuss again next week.

**Comment by tobespc** [comment] 2019-12-12 15:55
We are fixing this in #1471 by adding the lastSyncTime to the project metadata.  The FWD will see this when the watchlist is queried and use that value rather than 0.   Moving this to close as a dupe of 1471

**Closed by tobespc** 2019-12-12 15:55 UTC
Labels: area/portal, kind/bug
