### ISSUE TITLE
SVT: [Che] Cannot create Codewind Projects

### ISSUE THREAD

**Issue by sujeilyfonseca** [eclipse/codewind#3166] opened 2020-06-18 18:45 UTC
**Codewind version:** 0.13.0 & Latest
**OS:** Red Hat Enterprise Linux 7 (64 bit)

**Che version:** 7.9.2 
**Kubernetes cluster:** OCP 4.3

**Description:** Cannot create Codewind Projects

<img width="1675" alt="Screen Shot 2020-06-18 at 2 34 18 PM" src="https://user-images.githubusercontent.com/49531960/85059797-3b72f880-b172-11ea-98d8-835bbd23e8f1.png">

**Steps to reproduce:**
**Steps to reproduce the problem:**
1. Install Che 
2. Click on "Create New Project" 
3. Users will be prompt to select a template source
4. Select a template source or "Template Source Manager"
5. Nothing happens after that, even when the template options are displayed in Codewind log

**Logs:**
[codewind-workspaceespb5lrwtnp6yygv-6ccb48c5b8-jngl7.txt](https://github.com/eclipse/codewind/files/4800569/codewind-workspaceespb5lrwtnp6yygv-6ccb48c5b8-jngl7.txt)
[theia-ide6wn.txt](https://github.com/eclipse/codewind/files/4800570/theia-ide6wn.txt)

@jagraj

**Comment by malincoln** [comment] 2020-06-18 21:20
@johnmcollier can you take a look?  Thanks

**Comment by naveenkaratekid** [comment] 2020-06-19 12:41
I too can reproduce this issue. When I installed Che, and clicked ```Template Source Manager```, I noticed that multiple templates were already selected. If I click on ```No projects (Click here to create a project)``` to create a new project, nothing happens, even though multiple templates are selected.

![image](https://user-images.githubusercontent.com/19738071/85133045-f7323780-b207-11ea-99eb-adc8ab4865e7.png)

**Comment by jagraj** [comment] 2020-06-19 13:52
@johnmcollier 
More info on this issue, we have automation tests running for 0.11.0, 0.12.0, 0.13.0 releases and these tests do not target with old version of Che releases with latest Codewind 0.13.0 release. Automation tests for Codewind 0.13.0 release against Che 7.12.2 running fine and no issues. Looks like it is just failing with older version of Che 7.9.2 with Codewind 0.13.0 release. Do we tell users that we support back level version of Che releases with latest Codewind releases.?

Based on our automation tests, we do not see same problem with Che versions that we verified for specific Codewind releases.

**Comment by johnmcollier** [comment] 2020-06-22 18:06
@jagraj We only tell users to install the version of Che that we tested with the most recent release.

Since we don't see this issue on Che 7.12.0 and with @sujeilyfonseca's PR merged, I think we can close this issue out. Any concerns @sujeilyfonseca @jagraj?

**Closed** 2020-06-24 14:44 UTC
Labels: kind/bug, priority/stopship
