### ISSUE TITLE
SVT: Appsody Python Flask projects are being imported with Java as the language

### ISSUE THREAD

**Issue by sujeilyfonseca** [eclipse/codewind#486] opened 2019-09-18 21:28 UTC
**Codewind version:** 0.4.0
**OS:** Windows 10 and MacOS Mojave (10.14.6)

**IDE extension version:** 0.4.0
**IDE version:** 1.38.1

**Description:** Due to [eclipse/codewind#445](https://github.com/eclipse/codewind/issues/445), appsodyExtension must be selected manually to properly import a project into VS Code.

However, Appsody Python Flask projects are being imported with Java as the language, after selecting appsodyExtension.

<img width="720" alt="Screen Shot 2019-09-18 at 5 23 18 PM" src="https://user-images.githubusercontent.com/49531960/65187132-30e7cf00-da39-11e9-951c-021c6adc1dd3.png">

<img width="600" alt="Screen Shot 2019-09-18 at 5 24 18 PM" src="https://user-images.githubusercontent.com/49531960/65187137-3218fc00-da39-11e9-9ae9-fea55b7d790f.png">

<img width="721" alt="Screen Shot 2019-09-18 at 5 24 27 PM" src="https://user-images.githubusercontent.com/49531960/65187142-334a2900-da39-11e9-9661-fd6852fbcbe0.png">

**Steps:**
1. Install Codewind
2. Start Codewind
3. Create an Appsody Python Flask project
4. Remove the created project from Codewind
5. Import the project
6. Select appsodyExtension

**Comment by tetchel** [comment] 2019-09-18 21:54
yep, i see the bug. there is a logic error in this 'wizard' for extension project types

**Comment by mmulholl** [comment] 2019-09-18 22:05
Seeing this issue with all appsody project types.

For example when importing an existing Appsody Node Skaffold project, by default the type is set to Node.js - if i install that way it will not build. However, If I change the type to appsody and language to Node.js all is fine.

Making the stop/ship because it is both bad and a regression.

**Comment by tetchel** [comment] 2019-09-18 22:06
i don't think this is a stopship but the fix is ready either way

**Comment by tetchel** [comment] 2019-09-18 22:08
please open a different bug for eclipse, there was an error in the vs code logic which is what this issue is for (and it's fixed now)

**Comment by mmulholl** [comment] 2019-09-18 22:09
will do

**Comment by tetchel** [comment] 2019-09-18 22:09
i'm pretty sure the eclipse issue is just https://github.com/eclipse/codewind/issues/445

**Comment by tetchel** [comment] 2019-09-18 22:10
also, erin may already have it under control https://github.com/eclipse/codewind-eclipse/pull/309

**Comment by makandre** [comment] 2019-09-18 23:36
Since we are talking about python, this is possibly related to https://github.com/eclipse/codewind/issues/398 as well

**Comment by sujeilyfonseca** [comment] 2019-09-19 18:42
I tested this issue on 2019-09-19 and I no longer see the problem.

**Closed** 2019-09-19 19:44 UTC
Labels: area/vscode-ide, kind/bug, priority/stopship
