### ISSUE TITLE
Error starting Codewind: Unknown error Starting Codewind 0.4.0

### ISSUE THREAD

**Issue by nheidloff** [eclipse/codewind#509] opened 2019-09-23 08:22 UTC
**Codewind version:** 0.4.0
**OS:** Mac 10.14.6

**IDE version:** Visual Studio Code 1.13.1

**Description:**
I just installed the Visual Studio Code plugin for 0.4.0, but now Codewind doesn't start anymore. I only get this message:

Error starting Codewind: Unknown error Starting Codewind 0.4.0

I had previously installed 0.3.x which worked. I also uninstalled everything and then reinstalled, but without success.

**Steps to reproduce:**

Install in VS Code.

**Workaround:** 
No

**Comment by rwalle61** [comment] 2019-09-23 11:06
I'm getting this as well, so trying the temp fix (`docker system prune -a`) recommended in https://github.com/eclipse/codewind/issues/411#issuecomment-532181522. (This may be a duplicate of https://github.com/eclipse/codewind/issues/411 and https://github.com/eclipse/codewind/issues/433)

**Closed** 2019-10-17 13:34 UTC
Labels: kind/bug
