### ISSUE TITLE
SVT:IntelliJ:Assertion failed: Write access is allowed inside write-action only

### ISSUE THREAD

**Issue by jagraj** [eclipse/codewind#2168] opened 2020-02-12 20:46 UTC
**Codewind version:** 0.9.0
**OS:** Windows

**Che version:**
**IDE extension version:** 0.9.0
**IDE version:** IntelliJ 2019.3.3
**Kubernetes cluster:**

**Description:**
After installing codewind plugin from Intellij plugin manager when I restart IDE then in the notification panel I see this exception and I am not sure if this causes any functional issues but I do see this exception in the notification panel.

![image](https://user-images.githubusercontent.com/713849/74375675-c308bf00-4dae-11ea-9268-1b3c11b365e9.png)

```
java.lang.Throwable: Assertion failed: Write access is allowed inside write-action only (see com.intellij.openapi.application.Application.runWriteAction())
	at com.intellij.openapi.diagnostic.Logger.assertTrue(Logger.java:180)
	at com.intellij.openapi.application.impl.ApplicationImpl.assertWriteAccessAllowed(ApplicationImpl.java:1174)
	at com.intellij.openapi.roots.impl.ProjectRootManagerImpl.fireBeforeRootsChanged(ProjectRootManagerImpl.java:348)
	at com.intellij.openapi.roots.impl.ProjectRootManagerImpl.access$100(ProjectRootManagerImpl.java:35)
	at com.intellij.openapi.roots.impl.ProjectRootManagerImpl$BatchSession.beforeRootsChanged(ProjectRootManagerImpl.java:85)
	at com.intellij.openapi.roots.impl.ProjectRootManagerComponent.beforeRootsChange(ProjectRootManagerComponent.java:156)
	at com.intellij.openapi.roots.impl.ProjectRootManagerComponent.access$000(ProjectRootManagerComponent.java:63)
	at com.intellij.openapi.roots.impl.ProjectRootManagerComponent$1.beforeFileTypesChanged(ProjectRootManagerComponent.java:87)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	at com.intellij.util.messages.impl.MessageBusImpl.invokeListener(MessageBusImpl.java:518)
	at com.intellij.util.messages.impl.MessageBusConnectionImpl.deliverMessage(MessageBusConnectionImpl.java:142)
	at com.intellij.util.messages.impl.MessageBusImpl.doPumpMessages(MessageBusImpl.java:438)
	at com.intellij.util.messages.impl.MessageBusImpl.pumpWaitingBuses(MessageBusImpl.java:398)
	at com.intellij.util.messages.impl.MessageBusImpl.pumpMessages(MessageBusImpl.java:388)
	at com.intellij.util.messages.impl.MessageBusImpl.sendMessage(MessageBusImpl.java:372)
	at com.intellij.util.messages.impl.MessageBusImpl.lambda$createTopicHandler$1(MessageBusImpl.java:241)
	at com.sun.proxy.$Proxy43.beforeFileTypesChanged(Unknown Source)
	at com.intellij.openapi.fileTypes.impl.FileTypeManagerImpl.fireBeforeFileTypesChanged(FileTypeManagerImpl.java:1288)
	at com.intellij.openapi.fileTypes.impl.FileTypeManagerImpl.associate(FileTypeManagerImpl.java:1737)
	at com.intellij.openapi.fileTypes.impl.FileTypeManagerImpl.associate(FileTypeManagerImpl.java:1277)
	at org.eclipse.codewind.intellij.core.filetypes.CwSettingsFileTypeDetector.<init>(CwSettingsFileTypeDetector.java:29)
	at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.base/java.lang.reflect.Constructor.newInstance(Constructor.java:490)
	at com.intellij.serviceContainer.PlatformComponentManagerImpl.instantiateClass(PlatformComponentManagerImpl.kt:457)
	at com.intellij.openapi.extensions.impl.ExtensionComponentAdapter.instantiateClass(ExtensionComponentAdapter.java:54)
	at com.intellij.openapi.extensions.impl.XmlExtensionAdapter$SimpleConstructorInjectionAdapter.instantiateClass(XmlExtensionAdapter.java:95)
	at com.intellij.openapi.extensions.impl.ExtensionComponentAdapter.createInstance(ExtensionComponentAdapter.java:45)
	at com.intellij.openapi.extensions.impl.XmlExtensionAdapter.createInstance(XmlExtensionAdapter.java:63)
	at com.intellij.openapi.extensions.impl.ExtensionPointImpl.processAdapter(ExtensionPointImpl.java:442)
	at com.intellij.openapi.extensions.impl.ExtensionPointImpl.processAdapters(ExtensionPointImpl.java:398)
	at com.intellij.openapi.extensions.impl.ExtensionPointImpl.getExtensionList(ExtensionPointImpl.java:238)
	at com.intellij.openapi.extensions.ExtensionPointName.getExtensionList(ExtensionPointName.java:43)
	at com.intellij.psi.search.FileTypeIndexImpl.getVersion(FileTypeIndexImpl.java:61)
	at com.intellij.util.indexing.FileBasedIndexImpl.registerIndexer(FileBasedIndexImpl.java:349)
	at com.intellij.util.indexing.FileBasedIndexImpl.access$5300(FileBasedIndexImpl.java:107)
	at com.intellij.util.indexing.FileBasedIndexImpl$FileIndexDataInitialization.lambda$initAssociatedDataForExtensions$0(FileBasedIndexImpl.java:2448)
	at com.intellij.util.indexing.IndexInfrastructure$DataInitialization.executeNestedInitializationTask(IndexInfrastructure.java:173)
	at com.intellij.util.indexing.IndexInfrastructure$DataInitialization.runParallelNestedInitializationTasks(IndexInfrastructure.java:161)
	at com.intellij.util.indexing.IndexInfrastructure$DataInitialization.call(IndexInfrastructure.java:122)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at com.intellij.util.concurrency.BoundedTaskExecutor.doRun(BoundedTaskExecutor.java:222)
	at com.intellij.util.concurrency.BoundedTaskExecutor.access$200(BoundedTaskExecutor.java:30)
	at com.intellij.util.concurrency.BoundedTaskExecutor$1.execute(BoundedTaskExecutor.java:201)
	at com.intellij.util.ConcurrencyUtil.runUnderThreadName(ConcurrencyUtil.java:221)
	at com.intellij.util.concurrency.BoundedTaskExecutor$1.run(BoundedTaskExecutor.java:190)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.lang.Thread.run(Thread.java:834)
```

**Steps to reproduce:**
1. Install Codewind plugin.
2. Restart IntelliJ IDE.
3. Notification panel shows this exception. 

**Workaround:**

**Comment by jopit** [comment] 2020-02-12 21:30
I'm guessing this is intermittent since I've not seen it on Window (or Mac or Linux). From the exception, the root cause is
```
org.eclipse.codewind.intellij.core.filetypes.CwSettingsFileTypeDetector.<init>(CwSettingsFileTypeDetector.java:29)
```
so I'm guessing that the only consequence will be that, if it does happen, the `.cw-settings` file won't be recognized as Java.  @keithchong, could you please take a look

**Comment by jopit** [comment] 2020-02-13 14:34
I think the problem is here:
https://github.com/eclipse/codewind-intellij/blob/54ba11b1728418221d622199bbd5e113ef48c395/dev/src/main/java/org/eclipse/codewind/intellij/ui/tasks/UninstallCodewindTask.java#L39

Instead of passing `null` as the version, it should pass `InstallUtil.getVersion()`

**Comment by keithchong** [comment] 2020-02-20 16:28
I could not reproduce this either.  I will try moving this initialization code elsewhere to see if it makes a difference.

**Comment by keithchong** [comment] 2020-02-21 18:54
I was able to reproduce this on Windows, if initially you have the IDE started with no projects opened, you then install Codewind for IntelliJ.  If instead you opened a project, the detector is fine.  The same scenario on Mac is fine.

**Closed** 2020-02-21 20:57 UTC
Labels: area/intellij-ide, kind/bug
