### ISSUE TITLE
SVT : Mac  : Cannot create or import Appsody Kitura projects 

### ISSUE THREAD

**Issue by mmulholl** [eclipse/codewind#2699] opened 2020-04-16 17:58 UTC
**Codewind version:**0.11.0.v202004091756
**OS:**Mac

**Che version:**
**IDE extension version:**
**IDE version:**Eclipse jee 2019-09, VSCode
**Kubernetes cluster:**

**Description:**
Appsody kitura project will not create or import using eclipse or VSCode. Wizards do not show an error but the project fails to appear in the codewind project list. For example see this in the pfe logs:

[16/04/20 16:05:42 /portal/routes/projects/remoteBind.route.js] [ERROR] Project creation failed for project appsodyKituraTest011. Error: { [Error: EACCES: permission denied, open ‘/mounted-workspace/appsodyKituraTest011/.appsody/AppsodyKitura/Tests/LinuxMain.swift’]
 errno: -13,
 code: ‘EACCES’,
 syscall: ‘open’,
 path:
  ‘/mounted-workspace/appsodyKituraTest011/.appsody/AppsodyKitura/Tests/LinuxMain.swift’ }

**Steps to reproduce:**
Try creating a new appsodt kiutra project

**Workaround:**

**Comment by sujeilyfonseca** [comment] 2020-04-16 18:01
**Codewind version:** 0.11.0
**OS:** Mac OS Mojave 10.14.6, VM with Windows 10, Linux/Ubuntu

**IDE extension version:** 0.11.0
**IDE version:** Code 1.44.0

I reproduced the problem on Mac, using Appsody Kitura. I attempted to create/import the project, but nothing happened:

<img width="1672" alt="Screen Shot 2020-04-16 at 1 07 28 PM" src="https://user-images.githubusercontent.com/49531960/79490329-affeaf00-7fea-11ea-8977-a06329efc4b7.png">

I was not able to reproduce the problem on Linux and Windows:

![Screen Shot 2020-04-16 at 1 18 11 PM](https://user-images.githubusercontent.com/49531960/79490351-b725bd00-7fea-11ea-8351-a015b83d3c4b.png)

![Screen Shot 2020-04-16 at 1 19 20 PM](https://user-images.githubusercontent.com/49531960/79490356-b856ea00-7fea-11ea-8d8e-00b16b38d86d.png)

![Screen Shot 2020-04-16 at 1 19 36 PM](https://user-images.githubusercontent.com/49531960/79490359-b8ef8080-7fea-11ea-92ec-41437e035232.png)

![Screen Shot 2020-04-16 at 1 20 22 PM](https://user-images.githubusercontent.com/49531960/79490362-ba20ad80-7fea-11ea-8c9e-e925c8c92d6f.png)

**Comment by mmulholl** [comment] 2020-04-16 18:02
I re-installed Codewind 0.9.0 and appsody kitura projects worked OK.

**Comment by makandre** [comment] 2020-04-16 18:07
Sigh... I think my fix for Quarkus #2657 exposed this problem.  The file in question `.appsody/AppsodyKitura/Tests/LinuxMain.swift` has only read access in the stack.  So when I preserved the timestamp I think it's also preserving the access bits?  I think I can work around this...

**Comment by makandre** [comment] 2020-04-16 18:57
I've put up new PRs to refine my previous fix for Quarkus.

Somehow, when `preserveTimestamps` is enabled for `fs.copy`, it will try to modify that `LinuxMain.swift` file which has only read access as I mentioned previously.  This failed the project creation in `bind/end` function.

The new fix adds a param to the `copyProject` function to control whether we want to preserve timestamp or not:  defaults to `false` in `bind/end` (so Kitura will work), and pass in `true` in `upload/end` (required for Quarkus to work)

When we update a file in a Kitura project we'll still see the `EACCES` error in the log but I verified it seems harmless and my change is reflected in the application.  I suggest we can track this issue separately.

**Comment by hhellyer** [comment] 2020-04-17 10:38
I've raised #2705 as an alternative fix for this after some googling showed this was actually a bug in fs-extra. It's fixed in the latest release and my PR just updgrades to that.

The fs-extra issue is here:
https://github.com/jprichardson/node-fs-extra/issues/629

I *think* it's probably the correct fix but there's an argument for going with @makandre's fix in 0.11.0 as it doesn't involve updating a package and potentially the notices file. It also means we don't have to retest just in case fs-extra 9.0.0 has any new bugs.


I'll discuss this with @makandre when he comes online.

**Comment by makandre** [comment] 2020-04-17 11:43
@hhellyer thanks for finding that.  I agree we should fix it the right way (updating `fs-extra`) in master, and go with my workaround fix for 0.11.0 to avoid more churn.

**Closed** 2020-04-20 07:15 UTC
Labels: area/appsody, kind/bug, priority/stopship
