### ISSUE TITLE
Builds blocked by jenkins docker login failures.

### ISSUE THREAD

**Issue by hhellyer** [eclipse/codewind#2606] opened 2020-04-03 10:04 UTC
**Codewind version:** 0.11.0
**OS: NA**

**Description:**
The codewind 0.11.0 builds here:
https://ci.eclipse.org/codewind/job/Codewind/job/codewind/job/0.11.0/
have all failed recently when Jenkins attempts to login to dockerhub with it's own credentials via the `withDockerRegistry` statement in the Jenkins file:
```
[Pipeline] withDockerRegistry
00:04:57.442  $ docker login -u codewindbot -p ******** https://index.docker.io/v1/
00:04:57.488  WARNING! Using --password via the CLI is insecure. Use --password-stdin.
00:04:57.816  Error saving credentials: error storing credentials - err: exit status 1, out: `Cannot autolaunch D-Bus without X11 $DISPLAY`
[Pipeline] // withDockerRegistry
```
which means we haven't pushed any new  0.11.0 images for 2 days.

I think the other branches will also be affected but they haven't had changes merged to them so recently.

**Steps to reproduce:**
Run a build here: https://ci.eclipse.org/codewind/job/Codewind/job/codewind/job/0.11.0 or merge a fix.

**Workaround:**

**Comment by malincoln** [comment] 2020-04-03 13:22
@josephca pls investigate. Thanks

**Comment by hhellyer** [comment] 2020-04-03 14:38
A master build that ran on `ub18-01` just passed: https://ci.eclipse.org/codewind/job/Codewind/job/codewind/job/master/654/consoleFull
The failing builds appear to be running on `s8p2d-ubuntu1804`:
https://ci.eclipse.org/codewind/job/Codewind/job/codewind/job/0.11.0/6/consoleFull
https://ci.eclipse.org/codewind/job/Codewind/job/codewind/job/0.11.0/5/consoleFull

**Comment by josephca** [comment] 2020-04-03 15:42
I believe the root cause of the issue is recent 'docker-compose' install on 's8p2d-ubuntu1804'
I added a comment to fix the issue by reopening the existing Bugzilla bug against Eclipse: 
https://bugs.eclipse.org/bugs/show_bug.cgi?id=561659

Copying my own comment here: 

After 'docker-compose' is installed, Codewind is experiencing the following error. By the way, this issue is not reproducible in our own docker-build agent. 

I'd like to get 'docker-compose' uninstalled if we don't get a quick fix for this as we can use a workaround. 
 
Error message: 

$ docker login -u codewindbot -p ******** https://index.docker.io/v1/
09:54:58  WARNING! Using --password via the CLI is insecure. Use --password-stdin.
09:54:58  Error saving credentials: error storing credentials - err: exit status 1, out: `Cannot autolaunch D-Bus without X11 $DISPLAY`

Jenkins build log for more detail: 

https://ci.eclipse.org/codewind/view/Codewind/job/Codewind/job/codewind-che-plugin/job/master/148/console

I found that some others had the same issue after installing 'docker-compose'
https://github.com/docker/compose/issues/6023 

I agree with a comment for the root cause of the issue : 
Copying from (https://github.com/docker/compose/issues/6023 ) - 'this issue is compounded by the fact the Ubuntu packages and the "official" docker packages are disjointed.'

**Comment by josephca** [comment] 2020-04-06 17:18
This issue is fixed on all docker-build agents. Closing.

**Closed by josephca** 2020-04-06 17:18 UTC
Labels: area/releng, kind/bug, priority/stopship
