### ISSUE TITLE
SVT:ODO projects status always says "Starting" even though log says deployed successfully

### ISSUE THREAD

**Issue by jagraj** [eclipse/codewind#710] opened 2019-10-17 12:10 UTC
**Codewind version:** 0.5.0
**OS:** RHEL

**Che version:** 7.2.0
**IDE extension version:** 0.5.0
**IDE version:**7.1.0
**Kubernetes cluster:**
OKD Cluster

**Description:**
I created ODO projects and projects are getting stuck at "Starting" state even though log says it is successfully deployed. Rest of the projects created from default templates running fine and the status is all good but not ODO projects. 

**Steps to reproduce:**
1. Install Codewind che with 0.5.0 devfile.
2. Create ODO projects.
3. Wait until project is deployed successfully and the pod is running successfully.
4. At this point, the "Status" in Theia says "Starting" rather "Running".

Here is more info from my cluster.

```
kubectl get pods
NAME                                                              READY     STATUS    RESTARTS   AGE
che-7fbd6b89b4-5m9vn                                              1/1       Running   0          2d
che-operator-6f59664648-j5qlp                                     1/1       Running   0          2d
codewind-performance-workspacemc5rag046ckgzog9-65ffb466dc-9qgzb   1/1       Running   0          15h
codewind-workspacemc5rag046ckgzog9-55687966b5-csb4x               1/1       Running   0          15h
cw-dotnetokdcw05svt-app-1-hjpnr                                   1/1       Running   0          2d
cw-gookdcw05svt-72760160-f0d4-11e9-a249-ccc58cb66-cr2b2           1/1       Running   0          9m
cw-httpdokdcw05svt-app-1-bmbks                                    1/1       Running   0          2d
cw-javaokdcw05svt-5f62bc30-f0d4-11e9-a249-6b96c57b6b-sb2j8        1/1       Running   0          5m
cw-lagomokdcw05svt-7eb8e410-f0d4-11e9-a249-6c7cf657bd-9b7px       1/1       Running   0          2m
cw-odonodejs1cw05svt-app-1-smxst                                  1/1       Running   0          15h
cw-odonodejscw05svt-app-1-bl4pg                                   1/1       Running   0          21h
cw-odopython1cw05svt-app-1-wnc5z                                  1/1       Running   0          12m
cw-pythonodookdcw05svt-app-1-dx4jf                                1/1       Running   0          2d
devfile-registry-5c774759b5-q8zpt                                 1/1       Running   0          2d
keycloak-66c74b7599-snk7v                                         1/1       Running   0          2d
plugin-registry-69765c8c79-j6d95                                  1/1       Running   0          2d
postgres-864b695569-nhs8q                                         1/1       Running   0          2d
tiller-deploy-57bcbcbbc8-m7hjw                                    1/1       Running   0          2d
workspacemc5rag046ckgzog9.che-jwtproxy-6c94c484-9vnrn             1/1       Running   0          15h
workspacemc5rag046ckgzog9.che-workspace-pod-6979885949-whksm      3/3       Running   0          15h
```

![image](https://user-images.githubusercontent.com/713849/67007075-9bca0b80-f0b4-11e9-9a5f-f409383029a7.png)

[pfe.txt](https://github.com/eclipse/codewind/files/3739092/pfe.txt)
[theia.txt](https://github.com/eclipse/codewind/files/3739093/theia.txt)

**Workaround:**

**Comment by jagraj** [comment] 2019-10-17 12:12
@tetchel 
When you get a chance, can you take a look at the Theia logs that I attached to this issue.?
I see these errors in the log.

```
With stack trace: Error: Unknown actor WebviewsMain
    at RPCProtocolImpl.doInvokeHandler (/home/theia/node_modules/@theia/plugin-ext/lib/common/rpc-protocol.js:200:19)
    at RPCProtocolImpl.invokeHandler (/home/theia/node_modules/@theia/plugin-ext/lib/common/rpc-protocol.js:192:41)
    at RPCProtocolImpl.receiveRequest (/home/theia/node_modules/@theia/plugin-ext/lib/common/rpc-protocol.js:154:45)
    at RPCProtocolImpl.receiveOneMessage (/home/theia/node_modules/@theia/plugin-ext/lib/common/rpc-protocol.js:123:22)
    at /home/theia/node_modules/@theia/plugin-ext/lib/common/rpc-protocol.js:55:89
    at /home/theia/node_modules/@theia/plugin-ext/lib/common/rpc-protocol.js:233:17
    at /home/theia/node_modules/@theia/core/lib/common/event.js:162:33
    at CallbackList.invoke (/home/theia/node_modules/@theia/core/lib/common/event.js:177:39)
    at Emitter.fire (/home/theia/node_modules/@theia/core/lib/common/event.js:265:29)
    at ChildProcess.<anonymous> (/home/theia/node_modules/@theia/plugin-ext/lib/hosted/node/hosted-plugin-process.js:145:21)
root ERROR [hosted-plugin: 191] Promise rejection not handled in one second: Error: Unknown actor TreeViewsMain
With stack trace: Error: Unknown actor TreeViewsMain
    at RPCProtocolImpl.doInvokeHandler (/home/theia/node_modules/@theia/plugin-ext/lib/common/rpc-protocol.js:200:19)
    at RPCProtocolImpl.invokeHandler (/home/theia/node_modules/@theia/plugin-ext/lib/common/rpc-protocol.js:192:41)
    at RPCProtocolImpl.receiveRequest (/home/theia/node_modules/@theia/plugin-ext/lib/common/rpc-protocol.js:154:45)
    at RPCProtocolImpl.receiveOneMessage (/home/theia/node_modules/@theia/plugin-ext/lib/common/rpc-protocol.js:123:22)
    at /home/theia/node_modules/@theia/plugin-ext/lib/common/rpc-protocol.js:55:89
    at /home/theia/node_modules/@theia/plugin-ext/lib/common/rpc-protocol.js:233:17
    at /home/theia/node_modules/@theia/core/lib/common/event.js:162:33
    at CallbackList.invoke (/home/theia/node_modules/@theia/core/lib/common/event.js:177:39)
    at Emitter.fire (/home/theia/node_modules/@theia/core/lib/common/event.js:265:29)
    at ChildProcess.<anonymous> (/home/theia/node_modules/@theia/plugin-ext/lib/hosted/node/hosted-plugin-process.js:145:21)
Promise rejection not handled in one second: Error: Unknown actor WebviewsMain
```

**Comment by tetchel** [comment] 2019-10-17 12:58
`Error: Unknown actor TreeViewsMain` has been around for a while; it is not related to this.

The issue is here, in the last few lines of the PFE log.
```
[32m[17/10/19 12:01:03 odopython1cw05svt] [INFO][39m Pod name: cw-odopython1cw05svt-app-1-wnc5z
[91m[17/10/19 12:01:03 odopython1cw05svt] [ERROR][39m [31m[ File Name: /file-watcher/server/dist/utils/kubeutil.js | Function Name: getApplicationContainerInfo | Line Number: 167] [39mFailed to get the service internal/exposed port for project: odopython1cw05svt
[91m[17/10/19 12:01:03 odopython1cw05svt] [ERROR][39m [31m[ File Name: /file-watcher/server/dist/utils/kubeutil.js | Function Name: getApplicationContainerInfo | Line Number: 168] [39mTypeError: Cannot read property 'deploymentconfig' of undefined
[32m[17/10/19 12:01:03 odopython1cw05svt] [INFO][39m pingInTransitApplications: Application state error message: could not retrieve the port for the project
```

**Comment by ssh24** [comment] 2019-10-17 13:16
I just tried it out with latest 0.5 image and the projects come up running fine for me

<img width="1320" alt="Screen Shot 2019-10-17 at 9 15 35 AM" src="https://user-images.githubusercontent.com/15173354/67012113-ce790180-f0be-11e9-8b1f-ab799ca378cc.png">

**Comment by jagraj** [comment] 2019-10-17 14:17
@ssh24 
It does not for me and all this works fine for default template projects. What else might be going with my cluster.?

**Comment by maysunfaisal** [comment] 2019-10-17 14:25
@jagraj, if you can, pls do a quick test by visiting the endpoint in the browser manually. If you cant hit the endpoint, then there is something wrong with your application. If you can, then there is something wrong with Codewind and cannot ping it for some reason

**Comment by ssh24** [comment] 2019-10-17 14:26
@jagraj Which devfile did you use? I used https://raw.githubusercontent.com/eclipse/codewind-che-plugin/master/devfiles/0.5.0/devfile.yaml

**Comment by GeekArthur** [comment] 2019-10-17 14:29
@ssh24 Thanks Sakib for testing this!
@jagraj Although your application pod is up and running, I think the application service is not deployed successfully due to the vLaunch network issue, I tried my OKD cluster this morning and it works fine for me, but still face the slowness network issue. You don't need to do anything for your OKD cluster, you can either wait the network issue is resolved or switch to use another OKD cluster. (ODO project uses different build engine which is binding with ODO CLI, so the network issue may only affect the build engine that ODO uses)

![Screen Shot 2019-10-17 at 10 24 17 AM](https://user-images.githubusercontent.com/15131537/67017834-50b9f380-f0c8-11e9-85fb-ba37678f5bd3.png)

**Comment by GeekArthur** [comment] 2019-10-17 14:34
For ODO application, we use `deploymentconfig` as selector to get the service then use service to ping the application to decide if the app status is `Starting` or `Running`. @jagraj For your case, we can't get the service (service is deployed by ODO CLI) due to the network issue so that your ODO application gets stuck on `Starting` state

**Comment by jagraj** [comment] 2019-10-17 14:40
I just noticed, When I click on "Open app" and I can hit the endpoint but status never changes in IDE.
Here is the app endpoint. (http://cw-odonodejs1cw05svt-app-che.9.42.41.28.nip.io/).

I am sure this is not network issue, I have been using this cluster from past three releases and there are no issues with default template applications.

**Comment by jagraj** [comment] 2019-10-17 14:48
@ssh24 
Yes, I am using 0.5.0 devfile. (https://raw.githubusercontent.com/eclipse/codewind-che-plugin/master/devfiles/0.5.0/devfile.yaml).

**Comment by jagraj** [comment] 2019-10-17 14:51
You do not see this error in your cluster.?
https://github.com/eclipse/codewind/issues/710#issuecomment-543162343

**Comment by elsony** [comment] 2019-10-17 18:10
Based on discussion on today's checkpoint call,removing stopship since it looks like the problem is specific to cluster that SVT is using.

**Comment by jagraj** [comment] 2019-10-17 20:07
I and Jingfu had a call and did more debugging, the major differences between my cluster and other clusters are that I have GlusterFS, metering, monitoring, Tekton, Istio, Knative serving services enabled as part of the Kabanero foundation stack.  We are going to keep debugging this issue why ODO app status fails on this cluster with those services enabled.

**Comment by malincoln** [comment] 2019-10-17 20:57
@jagraj does that difference also affect 715 since this one is not stopship but 715 is?

**Comment by GeekArthur** [comment] 2019-10-17 21:21
@malincoln This one is on Kube (OKD) but 715 is on Local, Jag's OKD cluster issue is only related with Kube not Local, so they are different cases.

**Comment by GeekArthur** [comment] 2019-11-06 20:54
@rajivnathan We can close this one, Jag already opened a new issue to tracking issues against his cluster specifically: https://github.com/eclipse/codewind/issues/827, we can use that one for investigation.

**Comment by elsony** [comment] 2019-11-07 14:36
Closing based on the last comment.

**Closed by elsony** 2019-11-07 14:36 UTC
Labels: area/iterative-dev, kind/bug, priority/hot
