### ISSUE TITLE
Design issue for developing locally, building and running in kube (hybrid scenario)

### ISSUE THREAD

**Issue by jopit** [eclipse/codewind#393] opened 2019-09-06 18:13 UTC
This is the design issue for the user experience for what we've been calling the hybrid scenario. That scenario involves developing locally in the IDE but building and running the application in a kube cluster.  Hybrid is probably not a good "official" name for this capability, no-one will understand it without an explanation and without an explanation  people may think its something to do with could developing specifically for Hybrid Cloud.

Some initial thoughts on what the user needs to do

- Create, update and delete the connection for the kube cluster to be used as the remote.  Information they would need to provide is the URL for the remote cluster,  which Docker registry to push/pull application images from, and possiblhy whatever info is required for authentication (probably either username and password or some sort of authentication token).  It's possible for the first release we'll only support one remote connection, but we should keep in mind that we may eventually support more than one

- Connect and disconnect the remote connection.  It may be that this action is a better place for the user to provide authentication information.

- Move an existing Codewind project from the "local" connection to the remote connection.

- Move an existing Codewind project from the "remote" connection to the local connection.

- Add an existing project to the remote connection

- Create a new project associated with the remote connection

- Delete a project from the remote connection

Note that the current technical design requires the user to explicitly invoke build on the project in order to push the changes to the remote and have them built -- i.e. there is no auto-build function.  That will probably change at some point.

**Comment by jopit** [comment] 2019-09-06 18:14
@holmesk fyi.

**Comment by jopit** [comment] 2019-09-06 18:23
@kimholmes fyi

**Comment by jopit** [comment] 2019-09-10 14:47
@thisguy-1 fyi

**Comment by thisguy-1** [comment] 2019-09-27 21:39
Hybrid Flow: 

![1  Jane Creates a connection](https://user-images.githubusercontent.com/52169824/65803777-a6485380-e14d-11e9-95ea-5c5b4668fafd.png)
![2  Jane gets editable Remote Connection form](https://user-images.githubusercontent.com/52169824/65803778-a6e0ea00-e14d-11e9-90d2-0ba94a9e4bd9.png)
![3  Jane gets an error and decides to exit without saving](https://user-images.githubusercontent.com/52169824/65803779-a6e0ea00-e14d-11e9-98fd-0cddbaa75122.png)
![4  Jane returns to Remote Connection Page](https://user-images.githubusercontent.com/52169824/65803780-a6e0ea00-e14d-11e9-90c7-a7e0431f4e4f.png)
![5  Jane Succeeds at Connecting](https://user-images.githubusercontent.com/52169824/65803781-a6e0ea00-e14d-11e9-8ff7-c72b97584e89.png)
![6  Jane's Authentication Fails](https://user-images.githubusercontent.com/52169824/65803782-a6e0ea00-e14d-11e9-8eaf-33571ac50d51.png)
![7  Janes Authentication fails](https://user-images.githubusercontent.com/52169824/65803783-a6e0ea00-e14d-11e9-8ce0-c712df6ca0bd.png)
![8  Jane's Authentication Succeeds](https://user-images.githubusercontent.com/52169824/65803784-a6e0ea00-e14d-11e9-896b-72ed01f4c00c.png)

**Comment by thisguy-1** [comment] 2019-09-27 21:40
<img width="911" alt="Screen Shot 2019-09-27 at 5 39 41 PM" src="https://user-images.githubusercontent.com/52169824/65803832-d263d480-e14d-11e9-8c37-b67d6bceb3b0.png">

**Comment by thisguy-1** [comment] 2019-09-27 21:42
During Create New Project, Jane would select where she would like to build and run her app.

<img width="733" alt="Screen Shot 2019-09-27 at 5 41 19 PM" src="https://user-images.githubusercontent.com/52169824/65803897-09d28100-e14e-11e9-9cfa-8125688fbae4.png">

**Comment by thisguy-1** [comment] 2019-09-27 21:54
@sishida we need ID for the following (@tetchel please verify):
<img width="733" alt="Screen Shot 2019-09-27 at 5 41 19 PM" src="https://user-images.githubusercontent.com/52169824/65804000-6e8ddb80-e14e-11e9-836c-41dede416953.png">

What should be the title of this? What should go in the bar? Any instruction bellow?:
<img width="742" alt="Screen Shot 2019-09-27 at 5 45 18 PM" src="https://user-images.githubusercontent.com/52169824/65804123-d17f7280-e14e-11e9-909c-cf484509bc08.png">

If they dont fill out a description what should go in this area?
We need an alternative to Deployment as this happens before a pipeline run. Any suggestions?
What instruction should go under the headers of the each form?:
<img width="833" alt="Screen Shot 2019-09-27 at 5 46 56 PM" src="https://user-images.githubusercontent.com/52169824/65804144-e1975200-e14e-11e9-8fae-45e7f61900be.png">

There are at least three possible notifications that could go under a severed remote connection all of which you can click to open up the remote connection page. work with @tetchel to write it out.:
<img width="316" alt="Screen Shot 2019-09-27 at 5 50 20 PM" src="https://user-images.githubusercontent.com/52169824/65804306-6c784c80-e14f-11e9-9755-acca8ca3334e.png">
<img width="318" alt="Screen Shot 2019-09-27 at 5 49 55 PM" src="https://user-images.githubusercontent.com/52169824/65804307-6c784c80-e14f-11e9-9832-85890def6232.png">

**Comment by thisguy-1** [comment] 2019-09-27 21:55
@sishida we also need a page for the "learn more".

**Comment by sishida** [comment] 2019-10-03 15:42
1. Click Cloud with plus sign (add remote connection). The "Add remote connection" window appears.
2. Enter a name for your connection and click "Enter" to create the remote connection. The remote connection page appears.
3. From this page...
- Two remote connections are required: where your project is being created and your connection to the cloud.
   - To be deployed: Where your project is being created
   - Docker registry: You need a connection to Docker to build and run.
- Enter the URL that you need to log in to your cloud.
- Enter your usernames and passwords.
- Save your information. If your info is correct, you will see your username without the password. Error appears if info is incorrect.
- Connection appears if your info is correct.
- You can then disconnect or delete your connection.

Upcoming:
- Add notification for deleting connection. "Are you sure?"
- Should there be a warning for disconnecting or connecting--does connection/disconnection come with consequences? (Ask Tim E.)

**Comment by tetchel** [comment] 2019-10-15 19:11
[Icons](https://github.com/eclipse/codewind/issues/155)

**Comment by sishida** [comment] 2019-12-16 17:06
@thisguy-1 I understand that we might still want to make changes to the UI in the future, but because we already have a functional remote scenario for 0.7.0, is this issue good to close?

I'm thinking if we want to add changes in 0.8.0 and onward, we can open a separate issue.

**Comment by sishida** [comment] 2019-12-17 19:58
Confirmed with Guy and John P. that we can close this issue and then open a new one as we continue to iterate on the design.

**Closed by sishida** 2019-12-17 19:58 UTC
Labels: area/design, area/docs
