### ISSUE TITLE
Improve visibility of code blocks and code phrases

### ISSUE THREAD

**Issue by sishida** [eclipse/codewind#517] opened 2019-09-05 18:58 UTC
Add a grey background behind code blocks and code phrases so that they stand out more on the website.

Note: For large blocks of code, it's best if we can make the grey background appear as a single block instead of highlighting each line in grey. When we worked on Microclimate, we got feedback that indicated that highlighting each line was not ideal.
For example...
- Not like this code block: https://microclimate.dev/installkibanafilter#doc
- This code block is good: https://docs.docker.com/docker-for-aws/iam-permissions/

**Comment by sishida** [comment] 2019-09-23 16:23
@travis1111 Could you please implement the grey backgrounds to the code blocks and code phrases? Please let me know if I can help in any way.

@kimholmes I'm not sure if you/the design team need or want to be involved with this issue, but because it involves a visual component of the website, I wanted to at least tag you for awareness. 😃 

Thanks, team!

**Comment by travis1111** [comment] 2019-09-23 16:53
Hi, @sishida please assign this to me :-)

**Comment by tetchel** [comment] 2019-12-12 17:13
Want to bump this, our multiline code blocks look really bad. 
![image](https://user-images.githubusercontent.com/8888438/70733681-c9a88680-1cd8-11ea-8e24-c955027e522a.png)

They should be one block, not blocked per-line.

![image](https://user-images.githubusercontent.com/8888438/70733704-d4631b80-1cd8-11ea-9cb7-11e343948bc3.png)

**Comment by travis1111** [comment] 2019-12-12 17:54
This was caused by not using correct markdown syntax.  

Add `sh` solves the problem.

![image](https://user-images.githubusercontent.com/35569780/70736528-87824380-1cde-11ea-9bdc-5d41721812b1.png)


![image](https://user-images.githubusercontent.com/35569780/70736563-979a2300-1cde-11ea-9a87-c1d9b1aa70c3.png)

**Comment by travis1111** [comment] 2019-12-12 17:56
also this issue can be closed, the code formatting was delivered a couple months ago.

Thanks

**Comment by travis1111** [comment] 2019-12-12 18:08
This PR contains the MD file fix:

https://github.com/eclipse/codewind-docs/pull/262

**Comment by sghung** [comment] 2020-01-06 17:12
Closing as this work has been done

**Closed by sghung** 2020-01-06 17:12 UTC
Labels: area/design, area/website
