### ISSUE TITLE
Eclipse Project Selection Panel: can tab into non-editable area

### ISSUE THREAD

**Issue by mattcolegate** [eclipse/codewind#788] opened 2019-10-22 10:58 UTC
**Codewind version:** latest hybrid
**OS:** Windows 10

**Che version:** N/A
**IDE extension version:** 0.5.0v201910171920
**IDE version:** 2019-06
**Kubernetes cluster:** N/A

**Description:** Tabbing through the panel tabs into the label 'Select the project to add to Codewind'.

**Steps to reproduce:** Start Codewind and right click Local in the Codewind Explorer view. Select Add Existing Project... then press the tab key to cycle through the fields in the new resulting panel. As well as editable fields and the buttons, the above label also can be selected.

**Workaround:** N/A

**Comment by eharris369** [comment] 2019-10-22 13:04
This is a duplicate of #776

**Closed by eharris369** 2019-10-22 13:04 UTC
Labels: duplicate, kind/bug
