### ISSUE TITLE
SVT: [Che] Java spring projects not deleting

### ISSUE THREAD

**Issue by DavidG1011** [eclipse/codewind#310] opened 2019-08-28 14:39 UTC
Codewind version: 0.3
OS: RHEL
Che version: 7.0.0
IDE extension version: Theia plugin 0.3
IDE version: Theia 7.0-rc4
Kubernetes cluster: OpenShift

**Description:**
Java spring projects have permission issues and thus can't be removed from the project workspace.

**Steps to reproduce:**
1. Create Java spring project
2. Remove project from codewind/delete directory

Result: Project remains in explorer.

Manual removal attempt:

![Screen Shot 2019-08-28 at 10 36 29 AM](https://user-images.githubusercontent.com/30476587/63865577-d26e8a00-c97f-11e9-9d81-b1024603cf2e.png)

**Comment by GeekArthur** [comment] 2019-08-28 21:38
For project deletion issue: the cache image including `.m2` folder with 777 permission is ready, Joseph will push it to Dockerhub tomorrow.

For project creation issue: I just give a try, reproduce steps are:
1 Delete spring project
2 Create spring project with the same project name that just deleted
This is due to the target folder still exist under spring project not from the `.m2` folder

**Comment by GeekArthur** [comment] 2019-08-29 16:12
Cache image has pushed to Dockerhub with the `.m2` folder permission that can be removed, so Spring project deletion and creation should work, please verify.

**Comment by DavidG1011** [comment] 2019-08-29 19:38
Seeing this error now:
![image](https://user-images.githubusercontent.com/30476587/63970789-01195d00-ca73-11e9-82a9-a3d1751d13e4.png)

**Comment by GeekArthur** [comment] 2019-08-30 03:04
@DavidG1011 I can reproduce this error as well, Portal handles the project files (including `<project>/target/classes`) deletion, from my understanding Portal shouldn't have permission issue to delete that folder because Portal also belongs to PFE and should use root user for deletion. I would suggest move this issue to Portal to see why Portal can't delete it or if some changes on project deletion recently affect this.

@rajivnathan FYI, I can confirm we can simply use `Remove project` button from IDE to delete the project, so should not related with using Theia to delete directly/non-root Theia container. If you think it's okay you can move this issue to Portal.

**Comment by GeekArthur** [comment] 2019-08-30 15:16
Also I can delete the project files when I shell into the PFE container to delete, if Portal uses the same way then those files should be deleted.

**Comment by GeekArthur** [comment] 2019-08-30 15:52
Here is the processes running in PFE before and after the project deletion

Before
```
[root@codewind-workspaceihzd3wkt36lomj8w-6fbdb8f6b8-g624c /]# ps -aux
USER        PID %CPU %MEM    VSZ   RSS TTY      STAT START   TIME COMMAND
root          1  0.0  0.0  11684  1452 ?        Ss   15:15   0:00 sh -c  /file-watcher/scripts/root-watcher.sh ${HOST_WORKSPACE_DIRECTORY} ${CONTAINER_WORKSPACE_DIRECTORY} ; cd /portal ; npm start ;
root         86  0.0  0.3 734308 30308 ?        Sl   15:15   0:00 npm
root         99  0.0  0.0  11824  1480 ?        S    15:15   0:00 /bin/bash ./npm-start.sh
root        100  0.0  0.3 734308 30380 ?        Sl   15:15   0:00 npm
root        111  0.3  1.1 949868 90272 ?        Sl   15:15   0:06 node server.js
root      19837  0.0  0.0  11824  1496 ?        S    15:19   0:00 /bin/bash /usr/local/bin/kubectl logs -f pod/cw-spring-4ce76bc0-cb39-11e9-af49-75498975d8-ldpcb
root      19856  0.0  0.2 145656 20556 ?        Sl   15:19   0:00 _kubectl logs -f pod/cw-spring-4ce76bc0-cb39-11e9-af49-75498975d8-ldpcb --namespace eclipse-che
root      25626  0.0  0.0  11824  1936 ?        Ss   15:41   0:00 bash
root      25642  0.0  0.0  51744  1736 ?        R+   15:43   0:00 ps -aux
```

After
```
[root@codewind-workspaceihzd3wkt36lomj8w-6fbdb8f6b8-g624c /]# ps -aux
USER        PID %CPU %MEM    VSZ   RSS TTY      STAT START   TIME COMMAND
root          1  0.0  0.0  11684  1452 ?        Ss   15:15   0:00 sh -c  /file-watcher/scripts/root-watcher.sh ${HOST_WORKSPACE_DIRECTORY} ${CONTAINER_WORKSPACE_DIRECTORY} ; cd /portal ; npm start ;
root         86  0.0  0.3 734308 30308 ?        Sl   15:15   0:00 npm
root         99  0.0  0.0  11824  1480 ?        S    15:15   0:00 /bin/bash ./npm-start.sh
root        100  0.0  0.3 734308 30380 ?        Sl   15:15   0:00 npm
root        111  0.3  1.1 949868 90312 ?        Sl   15:15   0:06 node server.js
root      25626  0.0  0.0  11824  1936 ?        Ss   15:41   0:00 bash
root      25681  0.0  0.0  51744  1736 ?        R+   15:45   0:00 ps -aux
```

Given that, I don't any process from Turbine hold the `target` folder. Worth having Portal investigate more.

**Comment by rajivnathan** [comment] 2019-08-30 15:55
Thanks @GeekArthur, @tobespc we've looked at it from a Turbine perspective and don't see anything we're missing on cleanup before handing back to Portal. Can you please take a look from a Portal perspective?

**Comment by tobespc** [comment] 2019-09-03 09:18
How are you deleting the project ?   Under codewind, portal does not lock or write any files to the filesystem after the initial creation.  We also don't have a delete project api anymore as we assume the editors will handle all that

**Comment by GeekArthur** [comment] 2019-09-04 15:24
Fix has been merged to both master and 0.3.1 branch, please verify.

**Comment by DavidG1011** [comment] 2019-09-04 18:09
Verified fixed on latest

**Comment by rajivnathan** [comment] 2019-09-05 02:13
Thanks, closing

**Closed by rajivnathan** 2019-09-05 02:13 UTC
Labels: area/iterative-dev, kind/bug, priority/hot
