### ISSUE TITLE
[Remote] [Che] Cannot build ODO projects

### ISSUE THREAD

**Issue by ssh24** [eclipse/codewind#897] opened 2019-10-29 15:05 UTC
**Codewind version:** Master
**OS:** MacOS

**Che version:** 7.2.0
**IDE extension version:** Master
**IDE version:** Master
**Kubernetes cluster:** OKD

**Description:**
After creating an ODO project on che, the project fails to build on validation of the `Dockerfile`. This should not be happening because ODO projects don't have `Dockerfile` to begin with, so somehow the validation code is being injected which causes this error. Saw this on Node.js and Python ODO projects but I suspect happening for all types of ODO project.

```
[29/10/19 14:17:21 FileWatcher.js] [DEBUG] projectStatusChanged: failed (project d0e68310-fa56-11e9-9c74-4f202a6e33cb)
[29/10/19 14:17:21 FileWatcher.js] [TRACE] projectStatusChanged: failed (project: {
  "projectID": "d0e68310-fa56-11e9-9c74-4f202a6e33cb",
  "buildStatus": "failed",
  "detailedBuildStatus": "The build failed because required files are missing. See validation results for details.",
  "lastbuild": 1572358641655
})
[29/10/19 14:17:21 myodonod] [INFO] Validating project using operationId: 1ff095cce09347319b27e235f6d413dc
[29/10/19 14:17:21 Turbine] [TRACE] {"projectType":"nodejs","location":"/codewind-workspace/myodonod","projectID":"d0e68310-fa56-11e9-9c74-4f202a6e33cb"}
[29/10/19 14:17:21 myodonod] [INFO] Checking for required files
[29/10/19 14:17:21 myodonod] [INFO] Checking for required file /Dockerfile
[29/10/19 14:17:21 Turbine] [TRACE] Key translated. Returning message: Missing required file
[29/10/19 14:17:21 Turbine] [TRACE] Key translated. Returning message: Dockerfile is required but was not found.
[29/10/19 14:17:21 Turbine] [TRACE] Key translated. Returning message: Generate missing files
[29/10/19 14:17:21 Turbine] [TRACE] Key translated. Returning message: Generate missing required files.
[29/10/19 14:17:21 myodonod] [INFO] Checking for required file /package.json
[29/10/19 14:17:21 myodonod] [INFO] Sending validation result
[29/10/19 14:17:21 FileWatcher.js] [DEBUG] Portal's event listener: projectValidated
[29/10/19 14:17:21 FileWatcher.js] [DEBUG] Portal's event listener: {"operationId":"1ff095cce09347319b27e235f6d413dc","projectType":"nodejs","location":"/codewind-workspace/myodonod","projectID":"d0e68310-fa56-11e9-9c74-4f202a6e33cb","status":"failed","results":[{"severity":"error","filename":"Dockerfile","filepath":"myodonod/Dockerfile","type":"missing","label":"Missing required file","details":"Dockerfile is required but was not found.","quickfix":{"fixID":"generateMissingFiles","name":"Generate missing files","description":"Generate missing required files."}}]}
[29/10/19 14:17:21 FileWatcher.js] [ERROR] projectValidated: failed (project: {
  "operationId": "1ff095cce09347319b27e235f6d413dc",
  "projectType": "nodejs",
  "location": "/codewind-workspace/myodonod",
  "projectID": "d0e68310-fa56-11e9-9c74-4f202a6e33cb",
  "status": "failed",
  "results": [
    {
      "severity": "error",
      "filename": "Dockerfile",
      "filepath": "myodonod/Dockerfile",
      "type": "missing",
      "label": "Missing required file",
      "details": "Dockerfile is required but was not found.",
      "quickfix": {
        "fixID": "generateMissingFiles",
        "name": "Generate missing files",
        "description": "Generate missing required files."
      }
    }
  ]
})
[29/10/19 14:17:21 FileWatcher.js] [DEBUG] projectValidated: failed (project d0e68310-fa56-11e9-9c74-4f202a6e33cb)
[29/10/19 14:17:21 FileWatcher.js] [TRACE] projectValidated: failed (project: {
  "operationId": "1ff095cce09347319b27e235f6d413dc",
  "projectType": "nodejs",
  "location": "/codewind-workspace/myodonod",
  "projectID": "d0e68310-fa56-11e9-9c74-4f202a6e33cb",
  "status": "failed",
  "results": [
    {
      "severity": "error",
      "filename": "Dockerfile",
      "filepath": "myodonod/Dockerfile",
      "type": "missing",
      "label": "Missing required file",
      "details": "Dockerfile is required but was not found.",
      "quickfix": {
        "fixID": "generateMissingFiles",
        "name": "Generate missing files",
        "description": "Generate missing required files."
      }
    }
  ]
})
[29/10/19 14:17:21 myodonod] [INFO] Build state changed for project: d0e68310-fa56-11e9-9c74-4f202a6e33cb from: unknown, to: failed, with message: buildscripts.buildFailMissingFile
[29/10/19 14:17:21 myodonod] [INFO] Emitting event 
 message: projectStatusChanged
 data: {
  "projectID": "d0e68310-fa56-11e9-9c74-4f202a6e33cb",
  "buildStatus": "failed",
  "detailedBuildStatus": "The build failed because required files are missing. See validation results for details.",
  "lastbuild": 1572358641655
}
```

**Comment by GeekArthur** [comment] 2019-10-29 16:07
@lentheivendra FYI, below is the project validation for 0.5.0 without remote architecture gets in
```
[28/10/19 20:14:04 odo-nodejs] [INFO] Kicking off validation for project: 644f5020-f9bf-11e9-891b-67cf4f9fbf7d
[28/10/19 20:14:04 odo-nodejs] [INFO] Emitting event 
 message: projectValidated
 data: {
  "operationId": "8fcad8d169b119af165c42ef92970432",
  "projectType": "odo",
  "location": "/codewind-workspace/odo-nodejs",
  "projectID": "644f5020-f9bf-11e9-891b-67cf4f9fbf7d",
  "status": "success",
  "results": []
}
```

I think either this error won’t cause the build fail before (that means the hybrid master has other errors cause the build fail, I assume you see the build is failed) or the hybrid master expose the validation code (that means the validation code doesn’t work before for OpenShift projects).

odo uses the ImageStream directly instead of using Dockerfile to build the image, so validation shouldn’t check Dockerfile if ON_OPENSHIFT environment is detected, so either way from the two cases above, fixing validation code should resolve this issue

**Comment by lentheivendra** [comment] 2019-10-29 17:05
Problem appears to be due to PFE thinking the project type is node.js as opposed to odo, so therefore validateRequiredFiles() fails. If the correct project type of odo was discovered, then it should go into the odo extension project type's validation codepath where the list of required files specified in the extension config is currently non-existent and this wouldn't happen.

Interestingly, this happens when I select the ODO node.js template on project creation, but not for ODO python. But not sure if that's due to the pre-existing ODO node project. The ODO Python project also remains in 'disabled' state. Will try ODO python with a clean workspace just to see if can reproduce the required files validation error. Also seeing other errors probably related to the new architecture (log file attached).
[pfelog.txt](https://github.com/eclipse/codewind/files/3784836/pfelog.txt)

**Comment by lentheivendra** [comment] 2019-10-29 20:13
From what I can see, when in https://github.com/eclipse/codewind/blob/master/src/pfe/portal/modules/FileWatcher.js#L230 the project type is incorrect, so think this is a portal issue where the installer/CLI is determining an incorrect project type on project creation, which then leads to other problems.

**Comment by GeekArthur** [comment] 2019-10-29 20:16
I can reproduce the same error that @lentheivendra saw, currently the new remote architecture uses `cwctl` to call the bind API, the issue is when user try to create new OpenShift/odo projects through IDE, `cwctl` specify the wrong project type when calling the bind API (expected project type is `odo` instead of `nodejs`). We can also verify this from the IDE below: 

![Screen Shot 2019-10-29 at 4 11 27 PM](https://user-images.githubusercontent.com/15131537/67805145-cb8af300-fa66-11e9-8e77-e8036cf14a6f.png)

**Comment by ssh24** [comment] 2019-10-29 20:21
I think we can easily use the cwctl to point it to the ODO node.js type. Something like this:

```
./cwctl project create --url=<ODO_URL> --type odo:nodejs /projects
```

**Comment by rajivnathan** [comment] 2019-10-29 20:25
@tobespc This appears to be an issue with cwctl based on @GeekArthur 's comment above https://github.com/eclipse/codewind/issues/897#issuecomment-547609731

**Comment by tobespc** [comment] 2019-10-30 10:52
@ebuckle can you look at this as well please

**Comment by ebuckle** [comment] 2019-10-30 10:53
Will do

**Comment by lentheivendra** [comment] 2019-10-30 16:03
@tobespc Yes like appsody but need a OKD cluster + Che. You can create a ODO project with usual create command/menu-item and then choose Openshift Templates and then one of the three OpenShift templates (try node.js)

**Comment by ebuckle** [comment] 2019-11-01 15:54
Have found the problem. 

The CLI pulls in from ``api/v1/extensions``:

> [
>   {
>     "name": "appsodyExtension",
>     "path": "/codewind-workspace/.extensions/codewind-appsody-extension",
>     "version": "0.6.0",
>     "description": "Appsody extension for Codewind",
>     "projectType": "appsodyExtension",
>     "commands": [
>       {
>         "name": "postProjectValidate",
>         "command": "appsody",
>         "args": [
>           "init"
>         ]
>       },
>       {
>         "name": "postProjectValidateWithType",
>         "command": "appsody",
>         "args": [
>           "init",
>           "$subtype",
>           "none"
>         ]
>       }
>     ],
>     "detection": ".appsody-config.yaml",
>     "templates": null,
>     "config": {
>       "containerAppRoot": "/project/user-app",
>       "needsMount": true
>     }
>   },
>   {
>     "name": "odoExtension",
>     "path": "/codewind-workspace/.extensions/codewind-odo-extension",
>     "version": "0.4.0",
>     "description": "odo extension for Codewind",
>     "projectType": "odo",
>     "commands": [],
>     "detection": ".odo",
>     "templates": null,
>     "config": {}
>   }
> ]
> 

The "detection" field is what's used for the CLI to determine if a project is an extension or not, it checks the project dir to see if that file exists.

Appsody projects all have ``.appsody-config.yaml`` but ODO projects do not have ``.odo`` present, so the CLI cannot identify them.

Is this something that needs to be fixed in the templates instead?

**Comment by tobespc** [comment] 2019-11-01 16:19
so I think the fix for this is that the cwctl needs to be passed the type of odo when its called as there is no way of detecting it up front.

**Comment by jopit** [comment] 2019-11-01 17:14
ODO is only supported on Che I believe, so this is a vscode-in-theia issue, and doesn't apply to eclipse.

**Comment by jopit** [comment] 2019-11-01 17:19
According to the doc for the project creation api
```
--type type:subtype, -t type:subtype  Known type and subtype of project (type:subtype). Ignored when URL is given
```
So unless the doc is wrong, having the IDEs specify the type (even if we know it, which I'm not sure we do) isn't going to work.
@tetchel can you please look into this?

**Comment by jopit** [comment] 2019-11-01 17:39
@makandre has confirmed that the `-t` flag is ignored when creating a project from a template.  So the IDEs can't fix this either.  Passing this issue back to iterative-dev to figure out what to do here.

**Comment by elsony** [comment] 2019-11-01 20:16
I am not sure if I fully understand the problem.  When a project is being created, the user pick and choose the template and by that time, the type is already determined. Why do we have to detect the type that we just create?  Should we already know the type already given that the template is coming from the odo extension?  In terms of the templates, the templates is coming from the repos from Red Hat directly and it is not something that we can control, i.e. we can't add .odo to the project.

**Comment by makandre** [comment] 2019-11-01 20:27
That's a good point...

I think it's just how things have been: IDE tells cwctl (used to be the initialize container) to pull down template archive, it runs some validation and returns the detected project type back to IDE.  IDE uses what's returned rather than the attribute from the template.

**Comment by jopit** [comment] 2019-11-02 00:03
So someone needs to change cwctl project create to honour the -t flag, and the IDEs need to specify that flag when creating a project from a template.  I'll add the IDE tags back and we can make that change.  Then once cwctl has been updated it should work.

**Comment by tetchel** [comment] 2019-11-04 18:58
@tobespc why doesn't portal pick up the ODO type from the index.json like the regular codewind projects? 
https://github.com/eclipse/codewind-odo-extension/blob/master/templates/master-index.json#L6

**Comment by makandre** [comment] 2019-11-04 19:12
The detection part run by CLI is necessary to run commands for extension project types, such as `appsody init`

**Comment by tetchel** [comment] 2019-11-04 19:22
The IDEs don't currently run the validation command in the create case, is that what we are being asked to change? it seems like it makes more sense to put it into the project creation command

**Comment by jopit** [comment] 2019-11-04 19:26
@tobespc is asking us to pass the `-t odo` flag when creating a project

**Comment by jopit** [comment] 2019-11-04 19:29
From what I understand, the cwctl create command is already running the detection/validation, the problem is that for ODO projects can't detect that the type is ODO.

**Comment by tetchel** [comment] 2019-11-04 19:30
the validation also cannot tell that a go project is go language, but the create still 'detects' that properly. let me investigate a little

**Comment by jopit** [comment] 2019-11-04 19:40
Maybe because go projects aren't provided by an extension?

**Comment by tetchel** [comment] 2019-11-04 20:08
OK, so here's what is going on:

1. IDE calls `cwctl create` with a `url` to a git repo to download into a `path`
2. cwctl downloads the repo into that path, and also responds with an object: `projectType: { language: string, projectType: string }`
3. IDE calls `cwctl bind` with the project name, and the `type`, `language`, and `path` from above.

The problem with ODO is that in step 2, the `projectType.projectType` is a regular Codewind one (here's it's `nodejs`), not an ODO one, presumably because of the broken detection logic Edward pointed out above. I know that for _newly created_ projects, the detection step used to be skipped since the project type and language are already available in the template, but that appears to have been removed with the shift to cwctl, causing this issue as well as #789.
```
[INFO: 19:58:55.345 CLIWrapper.js.on():142]: Successfully ran CLI command cwctl --json --insecure project create /projects/osnode --url https://github.com/sclorg/nodejs-ex
[DBUG: 19:58:55.346 CLIWrapper.js.on():148]: CLI object output: {"status":"success","projectPath":"/projects/osnode","result":{"language":"nodejs","projectType":"nodejs"}}
root INFO [hosted-plugin: 153] [INFO: 19:58:55.347 CLIWrapper.js:101]: Running CLI command: cwctl --json --insecure project bind --conid local --name osnode --language nodejs --type nodejs --path /projects/osnode
```

so, now I see why passing the `projectType` (and possibly language too) from the selected template to override the flawed detection will fix this bug. the detection should not need to run in new project scenarios.

We can fix this without a fix from portal by simply ignoring the project type passed back from step 1, since we already know the `language` and `projectType` from the template.

**Comment by jopit** [comment] 2019-11-04 20:18
OK, let's fix this on the IDE side.  @eharris369 fyi/fya

**Comment by eharris369** [comment] 2019-11-04 21:17
Eclipse already ignores the project type passed back on the create request.  It uses the project type from the template for the bind request.

**Comment by yangcao77** [comment] 2019-11-04 23:01
I'm not able to build odo project on che, seeing this error: 
```
[04/11/19 23:00:32 odopython1] [INFO] projectInfo.deploymentRegistry: undefined
[04/11/19 23:00:32 odopython1] [INFO] Deployment Registry: docker.io/yangcao77
[04/11/19 23:00:32 Turbine] [ERROR] [File Name: /file-watcher/server/dist/utils/utils.js | Function Name: asyncReadDir | Line Number: 167] Error reading directory /codewind-workspace/odopython1/chart
[04/11/19 23:00:32 Turbine] [ERROR] [File Name: /file-watcher/server/dist/utils/utils.js | Function Name: asyncReadDir | Line Number: 168] Error: ENOENT: no such file or directory, scandir '/codewind-workspace/odopython1/chart'
[04/11/19 23:00:32 odopython1] [ERROR] [ File Name: /file-watcher/server/dist/projects/projectUtil.js | Function Name: buildAndRun | Line Number: 1190] The container failed to start for project odopython1
  Cause: dirList is not iterable
 TypeError: dirList is not iterable
    at containerBuildAndRun (/file-watcher/server/dist/projects/projectUtil.js:1314:32)
[04/11/19 23:00:32 FileWatcher.js] [ERROR] projectCreation: failed (project: {
  "operationId": "a3f895086499204de0577f3e06e3701e",
  "projectID": "e53b4d50-ff56-11e9-b5e2-8b2e8bcf86e6",
  "status": "failed",
  "ignoredPaths": [
    "/.project",
    "*/node_modules*",
    "*/.git/*",
    "*/.DS_Store",
    "*/*.swp",
    "*/*.swx",
    "*/4913",
    "/load-test*",
    "*/.dockerignore",
    "*/.gitignore",
    "*/*~",
    "/.settings"
  ],
  "isHttps": false,
  "error": "The container failed to start for project odopython1"
})
```

**Comment by jopit** [comment] 2019-11-05 15:50
This has been fixed with PR https://github.com/eclipse/codewind-vscode/pull/263.  Please verify this @ssh24

**Comment by GeekArthur** [comment] 2019-11-05 17:52
@tetchel @jopit Thanks for fixing this, the current design for `create` case makes more sense for me, if we can know project type from user (templates), we don't need to use detection code to get the project type again even the detection code logic has no problem but currently it has logic issues. I just try the latest devfile and the issue gets fixed.

**Closed** 2019-11-05 18:07 UTC
Labels: area/vscode-ide, kind/bug, priority/stopship, remote

**Comment by ssh24** [comment] 2019-11-05 19:02
I am still seeing build failures on ODO projects:

```
[05/11/19 18:59:35 FileWatcher.js] [ERROR] projectStatusChanged: failed (project: {
  "projectID": "56f5b4b0-fffe-11e9-a56b-65d759d8b67a",
  "buildStatus": "failed",
  "detailedBuildStatus": "Failed to build or deploy odo application",
  "lastbuild": 1572980375788
})
[05/11/19 18:59:35 myodonod] [INFO] Validating project using operationId: 5e767cf2a749560bbf78f453594d12ba
[05/11/19 18:59:35 myodonod] [INFO] Checking for required files
[05/11/19 18:59:35 myodonod] [INFO] Sending validation result
[05/11/19 18:59:35 myodonod] [INFO] Build state changed for project: 56f5b4b0-fffe-11e9-a56b-65d759d8b67a from: inProgress, to: failed, with message: buildscripts.odoBuildPushFailMsg
[05/11/19 18:59:35 myodonod] [INFO] Emitting event 
 message: projectStatusChanged
 data: {
  "projectID": "56f5b4b0-fffe-11e9-a56b-65d759d8b67a",
  "buildStatus": "failed",
  "detailedBuildStatus": "Failed to build or deploy odo application",
  "lastbuild": 1572980375788
}
[05/11/19 18:59:35 myodonod] [INFO] Kicking off validation for project: 56f5b4b0-fffe-11e9-a56b-65d759d8b67a
[05/11/19 18:59:35 myodonod] [INFO] Emitting event 
 message: projectValidated
 data: {
  "operationId": "5e767cf2a749560bbf78f453594d12ba",
  "projectType": "odo",
  "location": "/codewind-workspace/myodonod",
  "projectID": "56f5b4b0-fffe-11e9-a56b-65d759d8b67a",
  "status": "success",
  "results": []
}
[05/11/19 18:59:35 myodonod] [ERROR] [ File Name: /file-watcher/server/dist/projects/projectUtil.js | Function Name: processManager.spawnDetached | Line Number: 320] Error code: 1 - The container failed to start for application /codewind-workspace/myodonod
[05/11/19 18:59:35 FileWatcher.js] [ERROR] projectStatusChanged: failed (project: {
  "projectID": "56f5b4b0-fffe-11e9-a56b-65d759d8b67a",
  "buildStatus": "failed",
  "detailedBuildStatus": "Creating image for build failed",
  "lastbuild": 1572980375804
})
[05/11/19 18:59:35 myodonod] [INFO] Validating project using operationId: e5fa39e2e5da7088fb4193d83bf681a2
[05/11/19 18:59:35 myodonod] [INFO] Checking for required files
[05/11/19 18:59:35 myodonod] [INFO] Sending validation result
[05/11/19 18:59:35 FileWatcher.js] [ERROR] projectCreation: failed (project: {
  "operationId": "559477ae27eae566b3bf539c721978a1",
  "projectID": "56f5b4b0-fffe-11e9-a56b-65d759d8b67a",
  "isHttps": false,
  "status": "failed",
  "error": "The container failed to start for application /codewind-workspace/myodonod"
})
[05/11/19 18:59:35 myodonod] [ERROR] executeBuildScript : 315 | | The command /codewind-workspace/.extensions/codewind-odo-extension/odo-extension-entrypoint.sh /codewind-workspace/myodonod,56f5b4b0-fffe-11e9-a56b-65d759d8b67a,create,nodejs,cw-myodonod,myodonod-56f5b4b0-fffe-11e9-a56b-65d759d8b67a,true failed with exit code 1
[05/11/19 18:59:35 myodonod] [INFO] Build state changed for project: 56f5b4b0-fffe-11e9-a56b-65d759d8b67a from: failed, to: failed, with message: buildscripts.buildFail
[05/11/19 18:59:35 myodonod] [INFO] Emitting event 
 message: projectStatusChanged
 data: {
  "projectID": "56f5b4b0-fffe-11e9-a56b-65d759d8b67a",
  "buildStatus": "failed",
  "detailedBuildStatus": "Creating image for build failed",
  "lastbuild": 1572980375804
}
[05/11/19 18:59:35 myodonod] [INFO] Kicking off validation for project: 56f5b4b0-fffe-11e9-a56b-65d759d8b67a
[05/11/19 18:59:35 myodonod] [INFO] Emitting event 
 message: projectValidated
 data: {
  "operationId": "e5fa39e2e5da7088fb4193d83bf681a2",
  "projectType": "odo",
  "location": "/codewind-workspace/myodonod",
  "projectID": "56f5b4b0-fffe-11e9-a56b-65d759d8b67a",
  "status": "success",
  "results": []
}
[05/11/19 18:59:35 myodonod] [INFO] Emitting event 
 message: projectCreation
 data: {
  "operationId": "559477ae27eae566b3bf539c721978a1",
  "projectID": "56f5b4b0-fffe-11e9-a56b-65d759d8b67a",
  "isHttps": false,
  "status": "failed",
  "error": "The container failed to start for application /codewind-workspace/myodonod"
}
```

**Comment by GeekArthur** [comment] 2019-11-05 19:15
@ssh24 Please post the odo.build.log, once we ensure both build is successful and new log architecture is good, then we can close both issues.

**Comment by tetchel** [comment] 2019-11-05 19:17
the project type in the logs above is correct, so open a new issue if you are seeing a problem

**Comment by ssh24** [comment] 2019-11-05 19:23
Weird, it worked now when I tried again

**Comment by GeekArthur** [comment] 2019-11-05 19:25
Cool, for the successful build, the log from IDE is also working? If so, we can merge the PR of ODO extension repository

**Comment by ssh24** [comment] 2019-11-05 19:26
Yup, see https://github.com/eclipse/codewind-odo-extension/pull/17#issuecomment-549980769
