### ISSUE TITLE
SVT:Bunch of Java,Nodejs and Swift projects failed to run on Windows

### ISSUE THREAD

**Issue by jagraj** [eclipse/codewind#960] opened 2019-11-04 18:58 UTC
**Codewind version:** latest
**OS:** Windows

**Che version:**
**IDE extension version:** latest
**IDE version:** Eclipse 2019-09
**Kubernetes cluster:** N/A

**Description:**
WIth the latest from master bunch of Java, Nodejs and Swift projects does not work. They all say creating image but build failed. 

![image](https://user-images.githubusercontent.com/713849/68148624-5dcd4400-ff0a-11e9-9e8f-6da1a7a4459e.png)

[pfe_11042019.txt](https://github.com/eclipse/codewind/files/3805577/pfe_11042019.txt)

**Steps to reproduce:**
1. Install codewind latest from eclipse plugin.
2. Create all projects using codewind default templates. All projects failed to build except "Go and Python". 

Please find the log and screenshot attached to this issue.

**Workaround:**

**Comment by johnmcollier** [comment] 2019-11-04 19:16
@jagraj Do you have any logs from the build failures?

**Comment by johnmcollier** [comment] 2019-11-04 19:17
@jagraj Can you share the docker.build.log for the failed projects too?

**Comment by ssh24** [comment] 2019-11-04 20:54
One thing I noticed:

**MacOS**
```
~/workspace/dev/projects/codewind/src/pfe/file-watcher/server/test$ depfe
[root@a660bb63a141 /]# echo $REMOTE_MODE
true
```

**Windows**
```
PS C:\Users\Administrator> docker exec -it 3777996764c1 bash
[root@3777996764c1 /]# echo $REMOTE_MODE
```

**Comment by jagraj** [comment] 2019-11-04 21:05
I can not get the logs for these projects from the codewind explorer. Here is what I have...

```
docker ps -a
CONTAINER ID        IMAGE                                                            COMMAND                  CREATED             STATUS              PORTS                                                  NAMES
541946b06671        cw-swiftcwlatestsvt-422162d0-ff33-11e9-bc82-c564c3e7a1a1-build   "/swift-utils/tools-…"   2 hours ago         Created             1024-1025/tcp, 8080/tcp                                cw-swiftcwlatestsvt-422162d0-ff33-11e9-bc82-c564c3e7a1a1-build
59a3c3b53db8        cw-springcwlatestsvt-15f7ff20-ff33-11e9-bc82-c564c3e7a1a1        "/scripts/new_entryp…"   2 hours ago         Created             127.0.0.1:32817->7777/tcp, 127.0.0.1:32816->8080/tcp   cw-springcwlatestsvt-15f7ff20-ff33-11e9-bc82-c564c3e7a1a1
c3a603331166        cw-nodejscwlatestsvt-be6be320-ff32-11e9-bc82-c564c3e7a1a1        "docker-entrypoint.s…"   2 hours ago         Created             127.0.0.1:32813->3000/tcp, 127.0.0.1:32812->9229/tcp   cw-nodejscwlatestsvt-be6be320-ff32-11e9-bc82-c564c3e7a1a1
7bf339fc618a        cw-pythoncwlatestsvt-f7033120-ff32-11e9-bc82-c564c3e7a1a1        "python app.py"          2 hours ago         Up 2 hours          127.0.0.1:32809->5000/tcp                              cw-pythoncwlatestsvt-f7033120-ff32-11e9-bc82-c564c3e7a1a1
9b0a72913247        cw-gocwlatestsvt-b7dcd900-fc09-11e9-9517-5d162b6abaa9            "/app/main"              7 hours ago         Up 7 hours          127.0.0.1:32808->8000/tcp                              cw-gocwlatestsvt-b7dcd900-fc09-11e9-9517-5d162b6abaa9
f9c8cbc0a159        codewind-pfe-amd64:latest                                        "sh -c ' /file-watch…"   7 hours ago         Up 7 hours          127.0.0.1:10000->9090/tcp                              codewind-pfe
13058dfcdead        codewind-performance-amd64:latest                                "docker-entrypoint.s…"   7 hours ago         Up 7 hours          127.0.0.1:9095->9095/tcp                               codewind-performance
```

**Comment by jopit** [comment] 2019-11-04 21:14
Tests shouldn't be run with $REMOTE_MODE set because it may mask problems.

**Comment by ssh24** [comment] 2019-11-04 21:16
REMOTE_MODE is by default set to true when codewind is built from master. Nothing the test does.

**Comment by jopit** [comment] 2019-11-04 21:29
It's still invalid -- if the tests are running with REMOTE_MODE set, they're not valid.

**Comment by ssh24** [comment] 2019-11-04 21:31
I don't understand:
> if the tests are running with REMOTE_MODE set, they're not valid.

**Comment by jopit** [comment] 2019-11-04 21:37
User's don't run with REMOTE_MODE set.  Setting it changes the behaviour of PFE.  Therefore running tests with it set means we're not testing the code as a user will run it.  We know of instances where problems occur when REMOTE_MODE is not set, but don't occur when REMOTE_MODE is set.

**Comment by rajivnathan** [comment] 2019-11-04 21:52
@jopit I'm confused as well. The current, (latest in master) as of this comment has `REMOTE_MODE=true` when you use `run.sh` to start up the PFE container. Are you saying that is not correct?

**Comment by jopit** [comment] 2019-11-04 21:58
Yes, that is not correct.  The cwctl command does not set REMOTE_MODE.  Which is why sometimes things work when people use `run.sh`, but fail when they run in the IDEs, which use cwctl.

**Comment by ssh24** [comment] 2019-11-04 22:19
If we turn off the REMOTE_MODE that means it is not testing any of the new architecture changes?

Also I think that is what is caused the windows PFE above in  https://github.com/eclipse/codewind/issues/960#issuecomment-549542330 to not have REMOTE_MODE set to true because it was installed using cwctl.

So does cwctl set REMOTE_MODE before installing? There seems to be a discrepancy here.

**Comment by rajivnathan** [comment] 2019-11-04 22:49
Did an `echo $REMOTE_MODE` inside PFE for each case:

1. Local with run.sh
Result: `true`
2. Local with VSCode bringing up PFE (I'm assuming cwctl is bringing up PFE)
Result: not set
3. Che
Result: not set

@tobespc Can you please confirm what's expected? @elsony FYI

**Comment by tetchel** [comment] 2019-11-05 00:54
toby did say this morning that he was removing all the REMOTE_MODE code paths so hopefully by tomorrow it won't matter

**Comment by maysunfaisal** [comment] 2019-11-05 17:57
FYI, I cannot create projects on Windows using VS Code latest

I made sure the PFE container spun up by VS Code had the code commits as of Nov 5..

```
[05/11/19 17:49:42 Turbine] [INFO] The current log level is trace
[05/11/19 17:49:42 /portal/routes/logging.route.js] [INFO] logging level set to trace
[05/11/19 17:49:42 server.js] [TRACE] responded to PUT /api/v1/logging with status 200 and body { level: 'trace' }
[05/11/19 17:50:13 server.js] [TRACE] GET /api/v1/projects/watchlist called with
 req.body {}
[05/11/19 17:50:13 User.js] [DEBUG] The watch list: {"projects":[{"pathToMonitor":"/c/codewind-data/.config","projectID":"c6ecfe5835adf90002d0a58ac47d0f30","ignoredPaths":[],"projectWatchStateId":"badc4a4648eeb17bca722e49b3481373","type":"non-project"}]}
[05/11/19 17:50:13 server.js] [TRACE] responded to GET /api/v1/projects/watchlist with status 200 and body {}
[05/11/19 17:50:19 server.js] [TRACE] GET /api/v1/templates called with
 req.body {}, and
 req.query { showEnabledOnly: 'true' }
[05/11/19 17:50:23 Templates.js] [INFO] Repository list updated.
[05/11/19 17:50:25 server.js] [TRACE] responded to GET /api/v1/templates with status 200 and body {}
[05/11/19 17:50:50 server.js] [TRACE] GET /api/v1/extensions called with
 req.body {}
[05/11/19 17:50:50 server.js] [TRACE] responded to GET /api/v1/extensions with status 200 and body {}
[05/11/19 17:50:51 server.js] [TRACE] Checking origin host  matches expected host 127.0.0.1:10000
[05/11/19 17:50:51 server.js] [TRACE] POST /api/v1/projects/bind/start called with
 req.body { language: 'java',
  projectType: 'liberty',
  name: 'libertywin1',
  path:
   'c:\\Users\\Administrator\\Downloads\\maysunworkspace\\libertywin1' }
[05/11/19 17:50:51 server.js] [TRACE] responded to POST /api/v1/projects/bind/start with status 404 and body { language: 'java',
  projectType: 'liberty',
  name: 'libertywin1',
  path:
   'c:\\Users\\Administrator\\Downloads\\maysunworkspace\\libertywin1' }
[05/11/19 17:51:32 server.js] [TRACE] GET /api/v1/templates called with
 req.body {}, and
 req.query { showEnabledOnly: 'true' }
```

![Screen Shot 2019-11-05 at 12 51 26 PM](https://user-images.githubusercontent.com/31771087/68232763-c9c3b100-ffcb-11e9-85a7-7f3ac379fbb0.png)

**Comment by rajivnathan** [comment] 2019-11-07 15:15
I can no longer reproduce this issue. I think some of the recent fixes have resolved this issue. @jagraj can you please verify?

**Comment by ssh24** [comment] 2019-11-07 16:32
I am still seeing liberty projects failing to build on windows with our test automation
```
[07/11/19 16:15:10 codewindtestliberty] [TRACE] Run command to start the container: /file-watcher/idc/artifacts/run_docker.sh cw-codewindtestliberty-liberty1573141310334 cw-codewindtestliberty-liberty1573141310334 "-p 127.0.0.1::7777 -P" /codewind-workspace/.idc/docker/docker-c6f926dbd9ee2b9006ad19e42c84133e14bfafec C:\codewind-data "codewindtestliberty-liberty1573141310334"

[07/11/19 16:15:10 codewindtestliberty] [TRACE] Running codewind app container for /codewind-workspace/codewindtestliberty using container name cw-codewindtestliberty-liberty1573141310334
Application path used for volume mounting is: C:codewind-data/codewind-workspace/codewindtestliberty
Log path used for volume mounting is: C:codewind-data/.logs/codewindtestliberty-liberty1573141310334

[07/11/19 16:15:10 codewindtestliberty] [ERROR] executeBuildScript : 45 | docker: Error response from daemon: invalid mode: /home/default/app.
See 'docker run --help'.

[07/11/19 16:15:10 codewindtestliberty] [TRACE] The first attempt to run the container was unsuccessful. Exit code: 125
Retrying start container stage
[07/11/19 16:15:10 codewindtestliberty] [TRACE]
Run command to start the container: /file-watcher/idc/artifacts/run_docker.sh cw-codewindtestliberty-liberty1573141310334 cw-codewindtestliberty-liberty1573141310334 "-p 127.0.0.1::7777 -P" /codewind-workspace/.idc/docker/docker-c6f926dbd9ee2b9006ad19e42c84133e14bfafec C:\codewind-data "codewindtestliberty-liberty1573141310334"

[07/11/19 16:15:11 codewindtestliberty] [TRACE] Running codewind app container for /codewind-workspace/codewindtestliberty using container name cw-codewindtestliberty-liberty1573141310334
Application path used for volume mounting is: C:codewind-data/codewind-workspace/codewindtestliberty
Log path used for volume mounting is: C:codewind-data/.logs/codewindtestliberty-liberty1573141310334

[07/11/19 16:15:11 codewindtestliberty] [ERROR] executeBuildScript : 45 | Start container stage failed: failed to get containerID

[07/11/19 16:15:11 codewindtestliberty] [ERROR] executeBuildScript : 45 | Unable to start container.

[07/11/19 16:15:11 codewindtestliberty] [ERROR] [ File Name: /file-watcher/server/src/projects/projectUtil.ts | Function Name: processManager.spawnDetached | Line Number: 45] Error code: 3 - The container failed to start for application /codewind-workspace/codewindtestliberty
[07/11/19 16:15:11 Turbine] [TRACE] Key translated. Returning message: Creating image for build failed
[07/11/19 16:15:11 codewindtestliberty] [TRACE] idc build finished for /codewind-workspace/codewindtestliberty Thu Nov  7 16:15:11 UTC 2019

[07/11/19 16:15:11 codewindtestliberty] [INFO] Validating project using operationId: f2018dcd787fbcf5b8e972568196c9ae
[07/11/19 16:15:11 Turbine] [TRACE] {"projectType":"liberty","location":"/codewind-workspace/codewindtestliberty","projectID":"liberty1573141310334"}
[07/11/19 16:15:11 codewindtestliberty] [INFO] Checking for required files
[07/11/19 16:15:11 codewindtestliberty] [INFO] Checking for required file /Dockerfile | /Dockerfile-lang
[07/11/19 16:15:11 codewindtestliberty] [TRACE] idc build failed for /codewind-workspace/codewindtestliberty with exit code 3 Thu Nov  7 16:15:11 UTC 2019

[07/11/19 16:15:11 codewindtestliberty] [INFO] Checking for required file /Dockerfile-build
[07/11/19 16:15:11 codewindtestliberty] [INFO] Checking for required file /pom.xml
[07/11/19 16:15:11 codewindtestliberty] [ERROR] executeBuildScript : 45 | | The command /file-watcher/scripts/liberty-container.sh /codewind-workspace/codewindtestliberty,C:\codewind-data,liberty1573141310334,update,cw-codewindtestliberty-liberty1573141310334,true,cw-liberty1573141310334-c6f926dbd9ee2b9006ad19e42c84133e14bfafec,run,7777,REBUILD,codewindtestliberty-liberty1573141310334,, failed with exit code 3
[07/11/19 16:15:11 codewindtestliberty] [INFO] Build state changed for project: liberty1573141310334 from: inProgress, to: failed, with message: buildscripts.buildFail
[07/11/19 16:15:11 codewindtestliberty] [INFO] Emitting event
 message: projectStatusChanged
 data: {
  "projectID": "liberty1573141310334",
  "buildStatus": "failed",
  "detailedBuildStatus": "Creating image for build failed",
  "lastbuild": 1573143311210
}
```

**Comment by maysunfaisal** [comment] 2019-11-07 19:17
Even tho the issue title does not say Spring, Spring failed on Win latest:

I see this in the Spring app container, the files are in quotation marks?

```
root@b4d393624136:~/app# ls -la
total 132
drwxrwxr-x 4 root root  4096 Nov  7 19:06  .
drwx------ 1 root root  4096 Nov  7 19:05  ..
-rw-rw-r-- 1 root root   213 Nov  7 19:05  .cw-settings
-rw-rw-r-- 1 root root    40 Nov  7 19:05  .gitignore
drwxrwxrwx 3 root root  4096 Jun 18 20:06  .m2
-rw-rw-r-- 1 root root   277 Nov  7 19:05  Dockerfile
-rw-rw-r-- 1 root root  2409 Nov  7 19:05  Dockerfile-build
-rw-rw-r-- 1 root root   325 Nov  7 19:05  Dockerfile-tools
-rw-rw-r-- 1 root root  1814 Nov  7 19:05  README.md
-rw-rw-r-- 1 root root    95 Nov  7 19:05 'chart\springjavatemplate\Chart.yaml'
-rw-rw-r-- 1 root root   825 Nov  7 19:05 'chart\springjavatemplate\bindings.yaml'
-rw-rw-r-- 1 root root  1171 Nov  7 19:05 'chart\springjavatemplate\templates\basedeployment.yaml'
-rw-rw-r-- 1 root root  1197 Nov  7 19:05 'chart\springjavatemplate\templates\deployment.yaml'
-rw-rw-r-- 1 root root   806 Nov  7 19:05 'chart\springjavatemplate\templates\hpa.yaml'
-rw-rw-r-- 1 root root   413 Nov  7 19:05 'chart\springjavatemplate\templates\istio.yaml'
-rw-rw-r-- 1 root root   315 Nov  7 19:05 'chart\springjavatemplate\templates\service.yaml'
-rw-rw-r-- 1 root root   672 Nov  7 19:05 'chart\springjavatemplate\values.yaml'
-rw-rw-r-- 1 root root  3091 Nov  7 19:05  pom.xml
-rw-rw-r-- 1 root root   556 Nov  7 19:05 'src\main\java\application\Info.java'
-rw-rw-r-- 1 root root   445 Nov  7 19:05 'src\main\java\application\SBApplication.java'
-rw-rw-r-- 1 root root   449 Nov  7 19:05 'src\main\java\application\rest\HealthEndpoint.java'
-rw-rw-r-- 1 root root   734 Nov  7 19:05 'src\main\java\application\rest\v1\Example.java'
-rw-rw-r-- 1 root root     0 Nov  7 19:05 'src\main\resources\application-local.properties'
-rw-rw-r-- 1 root root     0 Nov  7 19:05 'src\main\resources\application.properties'
-rw-rw-r-- 1 root root 34158 Nov  7 19:05 'src\main\resources\public\index.html'
-rw-rw-r-- 1 root root  1054 Nov  7 19:05 'src\test\java\application\HealthEndpointTest.java'
drwxr-xr-x 3 root root  4096 Nov  7 19:06  target
root@b4d393624136:~/app# pwd
/root/app
```

Maven failed:
```
[INFO] Downloading from central: https://repo.maven.apache.org/maven2/org/apache/maven/wagon/wagon-provider-api/1.0-beta-6/wagon-provider-api-1.0-beta-6.jar
[INFO] Downloaded from central: https://repo.maven.apache.org/maven2/org/codehaus/plexus/plexus-io/2.3.2/plexus-io-2.3.2.jar (74 kB at 52 kB/s)
[INFO] Downloading from central: https://repo.maven.apache.org/maven2/asm/asm-commons/3.3.1/asm-commons-3.3.1.jar
[INFO] Downloaded from central: https://repo.maven.apache.org/maven2/org/apache/maven/maven-compat/3.0/maven-compat-3.0.jar (285 kB at 190 kB/s)
[INFO] Downloading from central: https://repo.maven.apache.org/maven2/asm/asm-tree/3.3.1/asm-tree-3.3.1.jar
[INFO] Downloaded from central: https://repo.maven.apache.org/maven2/asm/asm/3.3.1/asm-3.3.1.jar (44 kB at 28 kB/s)
[INFO] Downloaded from central: https://repo.maven.apache.org/maven2/org/apache/maven/wagon/wagon-provider-api/1.0-beta-6/wagon-provider-api-1.0-beta-6.jar (53 kB at 34 kB/s)
[INFO] Downloading from central: https://repo.maven.apache.org/maven2/org/jdom/jdom/1.1/jdom-1.1.jar
[INFO] Downloading from central: https://repo.maven.apache.org/maven2/org/apache/maven/shared/maven-dependency-tree/2.1/maven-dependency-tree-2.1.jar
[INFO] Downloaded from central: https://repo.maven.apache.org/maven2/asm/asm-tree/3.3.1/asm-tree-3.3.1.jar (22 kB at 13 kB/s)
[INFO] Downloading from central: https://repo.maven.apache.org/maven2/org/vafer/jdependency/0.7/jdependency-0.7.jar
[INFO] Downloaded from central: https://repo.maven.apache.org/maven2/asm/asm-commons/3.3.1/asm-commons-3.3.1.jar (38 kB at 22 kB/s)
[INFO] Downloading from central: https://repo.maven.apache.org/maven2/commons-io/commons-io/1.3.2/commons-io-1.3.2.jar
[INFO] Downloaded from central: https://repo.maven.apache.org/maven2/org/apache/maven/shared/maven-dependency-tree/2.1/maven-dependency-tree-2.1.jar (60 kB at 33 kB/s)
[INFO] Downloading from central: https://repo.maven.apache.org/maven2/asm/asm-analysis/3.2/asm-analysis-3.2.jar
[INFO] Downloaded from central: https://repo.maven.apache.org/maven2/log4j/log4j/1.2.17/log4j-1.2.17.jar (490 kB at 263 kB/s)
[INFO] Downloading from central: https://repo.maven.apache.org/maven2/asm/asm-util/3.2/asm-util-3.2.jar
[INFO] Downloaded from central: https://repo.maven.apache.org/maven2/org/jdom/jdom/1.1/jdom-1.1.jar (153 kB at 82 kB/s)
[INFO] Downloaded from central: https://repo.maven.apache.org/maven2/org/vafer/jdependency/0.7/jdependency-0.7.jar (12 kB at 6.2 kB/s)
[INFO] Downloaded from central: https://repo.maven.apache.org/maven2/commons-io/commons-io/1.3.2/commons-io-1.3.2.jar (88 kB at 44 kB/s)
[INFO] Downloaded from central: https://repo.maven.apache.org/maven2/asm/asm-analysis/3.2/asm-analysis-3.2.jar (18 kB at 8.9 kB/s)
[INFO] Downloaded from central: https://repo.maven.apache.org/maven2/asm/asm-util/3.2/asm-util-3.2.jar (37 kB at 17 kB/s)
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time:  27.184 s
[INFO] Finished at: 2019-11-07T19:06:32Z
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal org.springframework.boot:spring-boot-maven-plugin:1.5.15.RELEASE:repackage (default) on project cUsersAdministratorDownloadsmaysunworkspacesprrr: Execution default of goal org.springframework.boot:spring-boot-maven-plugin:1.5.15.RELEASE:repackage failed: Unable to find main class -> [Help 1]
[ERROR]
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR]
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/PluginExecutionException
```

**Comment by rajivnathan** [comment] 2019-11-07 19:57
I was not able to reproduce the issue with spring.

**Comment by mattcolegate** [comment] 2019-11-07 20:27
Me either

**Comment by mattcolegate** [comment] 2019-11-07 21:06
Node, Swift, Spring and Liberty all coming up fine on my system
Windows 10
VSCode plugin: codewind-0.6.0-201911071811.vsix
PFE image: codewind-pfe-amd64 latest sha256:c641dd7f23b7f422d5d1c02caf6e7073d5bb7883fd333c4156bda12f187f6ec3

**Comment by jagraj** [comment] 2019-11-07 22:42
Projects are creating and building now on my Windows machine.

**Comment by maysunfaisal** [comment] 2019-11-08 00:43
fixed. closing as verified.

**Comment by tetchel** [comment] 2019-11-08 00:46
only committers or the person who opened the issue can close issues, thx for verify

**Closed by tetchel** 2019-11-08 00:46 UTC
Labels: area/iterative-dev, kind/bug, priority/stopship
