### ISSUE TITLE
Getting started link in eclipse marketplace returns 404

### ISSUE THREAD

**Issue by AndyRWatson** [eclipse/codewind#2425] opened 2020-03-06 21:14 UTC
**Codewind version:**  0.9
**OS:**

**Che version:**
**IDE extension version:**
**IDE version:**
**Kubernetes cluster:**

**Description:**

Similar to intelliJ https://github.com/eclipse/codewind/issues/2372 , the eclipse marketplace information contains a "getting started link' which is currently returning a 404.   

Need to update the link to reflect the recent docs changes https://github.com/eclipse/codewind/issues/2373

**Steps to reproduce:**

Goto eclipse marketplace pages and following "getting started" link

https://marketplace.eclipse.org/content/codewind

https://www.eclipse.org/codewind/mdteclipsegettingstarted.html

**Workaround:**

**Comment by AndyRWatson** [comment] 2020-03-06 21:16
https://github.com/eclipse/codewind/issues/2372

**Comment by sghung** [comment] 2020-03-06 21:27
I setup a redirect page to fix the problem. It has our header and redirects after 5 seconds (a link if someone wants to press it sooner). I confirmed that you cannot use .htaccess to do redirect because eclipse.org doesn't support that (I confirmed by trying out redirects on eclipse che's website). As a result, the second best option is a redirect page.

**Comment by sghung** [comment] 2020-03-06 21:28
[redirects.zip](https://github.com/eclipse/codewind/files/4300493/redirects.zip)

**Comment by josephca** [comment] 2020-03-06 21:57
Verified the fix. Closing it on behalf of @AndyRWatson

**Closed by josephca** 2020-03-06 21:57 UTC
Labels: area/releng, area/website, kind/bug
