### ISSUE TITLE
SVT:Open liberty app created from the template fails to start

### ISSUE THREAD

**Issue by jagraj** [eclipse/codewind#236] opened 2019-08-20 19:17 UTC
**Codewind version:** Latest
**OS:** Windows

**Che version:**
**IDE extension version:**   
Codewind tech preview	0.3.0.v201908161735	org.eclipse.codewind.feature.group	IBM

**IDE version:**
Eclipse IDE for Enterprise Java Developers.

Version: 2019-06 (4.12.0)
Build id: 20190614-1200

**Kubernetes cluster:**

**Description:**
Open liberty app does not start which is created from the template available in the codewind.

**Steps to reproduce:**
1. Install eclipse.
2. Install codewind eclipse plugin
3. Create generic "Open liberty" project from the templates.
4. I see app failed to start exception in the log.

```
[err]   at java.lang.Thread.run(Thread.java:818)
[ERROR   ] CWWKZ0002E: An exception occurred while starting the application io.openliberty.sample.getting.started. The exception message was: com.ibm.ws.container.service.state.StateChangeException: org.jboss.weld.exceptions.DefinitionException: Exception List with 1 exceptions:
Exception 0 :
java.lang.NumberFormatException: null
        at java.lang.Integer.parseInt(Integer.java:554)
        at java.lang.Integer.parseInt(Integer.java:627)
        at io.openliberty.sample.config.CustomConfigSource.getOrdinal(CustomConfigSource.java:32)
        at com.ibm.ws.microprofile.config.impl.ConfigSourceComparator.compare(ConfigSourceComparator.java:38)
        at com.ibm.ws.microprofile.config.impl.ConfigSourceComparator.compare(ConfigSourceComparator.java:19)
        at java.util.TreeMap.put(TreeMap.java:563)
        at java.util.TreeSet.add(TreeSet.java:266)
        at java.util.AbstractCollection.addAll(AbstractCollection.java:355)
        at java.util.TreeSet.addAll(TreeSet.java:323)
        at com.ibm.ws.microprofile.config.impl.SortedSources.addAll(SortedSources.java:50)
        at com.ibm.ws.microprofile.config13.impl.Config13BuilderImpl.getSources(Config13BuilderImpl.java:61)
        at com.ibm.ws.microprofile.config.impl.AbstractConfigBuilder.build(AbstractConfigBuilder.java:143)
        at com.ibm.ws.microprofile.config.impl.AbstractProviderResolver.getConfig(AbstractProviderResolver.java:257)
        at com.ibm.ws.microprofile.config.impl.AbstractProviderResolver.getConfig(AbstractProviderResolver.java:225)
        at org.eclipse.microprofile.config.ConfigProvider.getConfig(ConfigProvider.java:93)
        at com.ibm.ws.microprofile.faulttolerance.cdi.FaultToleranceCDIExtension.afterTypeDiscovery(FaultToleranceCDIExtension.java:221)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:90)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:55)
        at java.lang.reflect.Method.invoke(Method.java:508)
        at org.jboss.weld.injection.StaticMethodInjectionPoint.invoke(StaticMethodInjectionPoint.java:95)
        at org.jboss.weld.injection.StaticMethodInjectionPoint.invoke(StaticMethodInjectionPoint.java:85)
        at org.jboss.weld.injection.MethodInvocationStrategy$SimpleMethodInvocationStrategy.invoke(MethodInvocationStrategy.java:168)
        at org.jboss.weld.event.ObserverMethodImpl.sendEvent(ObserverMethodImpl.java:330)
        at org.jboss.weld.event.ExtensionObserverMethodImpl.sendEvent(ExtensionObserverMethodImpl.java:123)
        at org.jboss.weld.event.ObserverMethodImpl.sendEvent(ObserverMethodImpl.java:308)
        at org.jboss.weld.event.ObserverMethodImpl.notify(ObserverMethodImpl.java:286)
        at javax.enterprise.inject.spi.ObserverMethod.notify(ObserverMethod.java:124)
        at org.jboss.weld.util.Observers.notify(Observers.java:166)
        at org.jboss.weld.event.ObserverNotifier.notifySyncObservers(ObserverNotifier.java:285)
        at org.jboss.weld.event.ObserverNotifier.notify(ObserverNotifier.java:273)
        at org.jboss.weld.event.ObserverNotifier.fireEvent(ObserverNotifier.java:177)
        at org.jboss.weld.event.ObserverNotifier.fireEvent(ObserverNotifier.java:171)
        at org.jboss.weld.bootstrap.events.AbstractContainerEvent.fire(AbstractContainerEvent.java:53)
        at org.jboss.weld.bootstrap.events.AbstractDefinitionContainerEvent.fire(AbstractDefinitionContainerEvent.java:44)
        at org.jboss.weld.bootstrap.events.AfterTypeDiscoveryImpl.fire(AfterTypeDiscoveryImpl.java:45)
        at org.jboss.weld.bootstrap.WeldStartup.startInitialization(WeldStartup.java:425)
        at org.jboss.weld.bootstrap.WeldBootstrap.startInitialization(WeldBootstrap.java:79)
        at com.ibm.ws.cdi.impl.CDIContainerImpl$2.run(CDIContainerImpl.java:144)
        at com.ibm.ws.cdi.impl.CDIContainerImpl$2.run(CDIContainerImpl.java:141)
        at java.security.AccessController.doPrivileged(AccessController.java:647)
        at com.ibm.ws.cdi.impl.CDIContainerImpl.startInitialization(CDIContainerImpl.java:141)
        at com.ibm.ws.cdi.liberty.CDIRuntimeImpl.applicationStarting(CDIRuntimeImpl.java:443)
        at com.ibm.ws.container.service.state.internal.ApplicationStateManager.fireStarting(ApplicationStateManager.java:51)
        at com.ibm.ws.container.service.state.internal.StateChangeServiceImpl.fireApplicationStarting(StateChangeServiceImpl.java:50)
        at com.ibm.ws.app.manager.module.internal.SimpleDeployedAppInfoBase.preDeployApp(SimpleDeployedAppInfoBase.java:550)
        at com.ibm.ws.app.manager.module.internal.SimpleDeployedAppInfoBase.installApp(SimpleDeployedAppInfoBase.java:511)
        at com.ibm.ws.app.manager.module.internal.DeployedAppInfoBase.deployApp(DeployedAppInfoBase.java:347)
        at com.ibm.ws.app.manager.war.internal.WARApplicationHandlerImpl.install(WARApplicationHandlerImpl.java:65)
        at com.ibm.ws.app.manager.internal.statemachine.StartAction.execute(StartAction.java:140)
        at com.ibm.ws.app.manager.internal.statemachine.ApplicationStateMachineImpl.enterState(ApplicationStateMachineImpl.java:1266)
        at com.ibm.ws.app.manager.internal.statemachine.ApplicationStateMachineImpl.run(ApplicationStateMachineImpl.java:881)
        at com.ibm.ws.threading.internal.ExecutorServiceImpl$RunnableWrapper.run(ExecutorServiceImpl.java:239)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1160)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
        at java.lang.Thread.run(Thread.java:818)

```

**Workaround:**

**Comment by naveenkaratekid** [comment] 2019-08-20 19:22
I too see some exceptions when I run the Open Liberty App.

OS: MacOS Mojave Version 10.14.6

IDE: Eclipse IDE for Java EE v 4.12.0
Codewind version: 0.3.0v20198161735


I attached the log file below:
[my-openliberty-59983410-b704-11e9-acbe-859539e8bb52.log](https://github.com/eclipse/codewind/files/3522248/my-openliberty-59983410-b704-11e9-acbe-859539e8bb52.log)

**Comment by sujeilyfonseca** [comment] 2019-08-20 19:22
**Codewind version:** 0.3
**OS:** Windows 10 and MacOS Mojave (10.14.5)

**IDE extension version:** latest
**IDE version:** VS Code 1.37.1 and Eclipse 2019-06 (4.12.0)

**Description:** I'm also seeing this problem with VS Code.

**Logs:**
[app.log](https://github.com/eclipse/codewind/files/3522247/app.log)

**Comment by tetchel** [comment] 2019-08-20 19:30
tagging with portal because it appears to be an issue with the OL template

**Comment by markcor11** [comment] 2019-08-21 13:31
I have not been able to reproduce this using v0.2 or v0.3 of the Codewind Plugin.   I've also tried pulling down the template sample and running the maven build manually which also worked as does running the docker build .  

If this is still an issue,  could you check your <LibertyProject>/resources/CustomConfigSource file.  It should look like this (specifically config_ordinal which your logs suggest appears to be missing or incorrectly formatted): 

```json
{
"config_ordinal":500,
"io_openliberty_sample_system_inMaintenance":false,
"io_openliberty_sample_testConfigOverwrite":"CustomSource"
}
```

**Comment by jagraj** [comment] 2019-08-22 11:46
@markcor11 
After going through the logs, it is complaining about missing file which does not exist in the docker container itself that we are building.

```
[AUDIT   ] CWWKT0016I: Web application available (default_host): http://0b5b80efd5cc:9080/jwt/
[err] java.io.FileNotFoundException: /opt/ol/wlp/output/defaultServerresources/CustomConfigSource.json (No such file or directory)
[AUDIT   ] CWWKT0016I: Web application available (default_host): http://0b5b80efd5cc:9080/openapi/
```
You can take a look at the log above and the path specified in the template is wrong. 

```
public class CustomConfigSource implements ConfigSource {

  String fileLocation = System.getProperty("user.dir").split("target")[0]
      + "resources/CustomConfigSource.json";
```

In the docker container, file is missing even though we are copying it in Dockerfile.

```
FROM maven:3.5.4-jdk-8-alpine AS builder
COPY pom.xml .
COPY src src/
COPY resources resources/
RUN mvn install -DskipTests

FROM open-liberty as server-setup
COPY --from=builder /target/LibertyProject.zip /config/
USER root
RUN apt-get update \
    && apt-get install -y --no-install-recommends unzip \
    && unzip /config/LibertyProject.zip \
    && mv /wlp/usr/servers/sampleAppServer/* /config/ \
    && rm -rf /config/wlp \
    && rm -rf /config/LibertyProject.zip 

FROM open-liberty
LABEL maintainer="Graham Charters" vendor="IBM" github="https://github.com/WASdev/ci.maven"
COPY --chown=1001:0 --from=server-setup /config/ /config/
EXPOSE 9080 9443
```

```
default@12c4cdc1df23:/$ find / -name CustomConfigSource.json -print
find: '/var/cache/apt/archives/partial': Permission denied
find: '/var/cache/ldconfig': Permission denied
find: '/proc/tty/driver': Permission denied
find: '/root': Permission denied
find: '/etc/ssl/private': Permission denied
```

**Comment by jagraj** [comment] 2019-08-22 12:27
@tobespc 
If we are going to support open liberty template from codewind then this issue seems to be "stopship". 
Let me know what do you think.

**Comment by tobespc** [comment] 2019-08-22 12:54
@jagraj If a change is needed then it would be with the template so that shouldn't hold up the release.   Have you tried making this run outside of codewind ?  Mark has tested this both inside and outside of codewind and we can't get it to fail.  One thought we have had is wondering whether you have an older version of the liberty docker image installed and its that that is causing the issue.

**Comment by rajivnathan** [comment] 2019-08-22 23:15
Think there's some confusion because the project will still be in running state and the open liberty server shows a default page so it appears that the app is running but the sample application contents don't appear to be there and there are errors in the server logs.

I investigated a bit and there appear to be a couple problems. Here's a PR that fixed it (at least for me):
https://github.com/microclimate-dev2ops/openLibertyTemplate/pull/1
@jagraj can you see if those changes work for you as well?

Here is what I was seeing before:
![image](https://user-images.githubusercontent.com/20015929/63555997-09244a80-c511-11e9-8fb8-920a2147d06c.png)


This is what I see with the changes:
![image](https://user-images.githubusercontent.com/20015929/63555857-931fe380-c510-11e9-8036-cd4b3874f4b3.png)

And if you scroll down a bit more and expand the Config section you should see the following if the sample is working correctly:
![image](https://user-images.githubusercontent.com/20015929/63555897-bcd90a80-c510-11e9-9a9c-48206db1fd07.png)

@mmulholl ^Should probably use those contents in the test verification steps

**Comment by jagraj** [comment] 2019-08-23 03:10
@rajivnathan 
Thanks for the fix, now app starts fine and no more exceptions in the log. 

@tobespc 
Verification is done, Please go ahead and merge this PR. (https://github.com/microclimate-dev2ops/openLibertyTemplate/pull/1)

**Comment by tobespc** [comment] 2019-08-23 08:37
merging done, closing issue

**Closed by tobespc** 2019-08-23 08:37 UTC
Labels: area/portal, kind/bug
