### ISSUE TITLE
Document how to run the Turbine functional tests on Kube and Local

### ISSUE THREAD

**Issue by johnmcollier** [eclipse/codewind#1369] opened 2019-12-04 18:11 UTC
Currently we don't have much in terms of documentation telling folks how to run the functional tests for Turbine code changes(https://github.com/eclipse/codewind/tree/master/src/pfe/file-watcher/server/test) or what prerequisites there are (There's an implicit OKD/OCP requirement right now https://github.com/eclipse/codewind/issues/370)

In order to make it easier for external users to contribute (as well as making it easier for us to run our tests), we need to have clear documentation outlining:
- What's required to run the tests (including the test machine and test cluster)
- How to run the tests and view your results
    - Including running the functional tests against your changes
- Should be linked to from the Turbine readme.md and/or Codewind's [CONTRIBUTING.md](https://github.com/eclipse/codewind/blob/master/CONTRIBUTING.md) doc

**Comment by ssh24** [comment] 2019-12-04 18:13
Duplicate of https://github.com/eclipse/codewind/issues/315

**Comment by johnmcollier** [comment] 2019-12-04 18:13
Closing as a dupe of #315 and #316

**Closed by ssh24** 2019-12-04 18:13 UTC
Labels: area/iterative-dev, kind/test
