### ISSUE TITLE
Avoid entering registries and template sources for each connection

### ISSUE THREAD

**Issue by eharris369** [eclipse/codewind#1264] opened 2019-11-25 19:20 UTC
It would be nice if the user did not have to enter the same registries and template sources for each connection.  Perhaps the IDEs could find a way to hide this from the user and keep one set of registries and template sources.

**Comment by tobespc** [comment] 2020-01-17 10:54
closing as dupe of #1667

**Closed by tobespc** 2020-01-17 10:54 UTC
Labels: area/eclipse-ide, area/vscode-ide, kind/enhancement
